<3주차 과제 1: To-do 테스트 작성하기>
CodeSoom/week3-assignment-1 pull request #148
Opened 2022-08-16 11:57 UTC by xunxee

강의를 보고 Input.test.jsx 파일을 생성하여 기본적인 테스트 코드를 생성했습니다.

2022-08-16 13:27 UTC, daadaadaah requested changes
빠른 PR 너무 좋습니다!👍 

[BDD 스타일](https://ko.javascript.info/testing-mocha#ref-1068)을 사용해서 나머지 테스트 코드도 작성해봅시다!💪

참고
- https://marocchino.net/2016/12/04/about-rspec/

2022-08-16 13:27 UTC, daadaadaah commented on src/Input.test.jsx
> +  fireEvent.click(getByText('추가'));
"추가" 버튼을 클릭했을 때, 어떤 동작을 기대하는지 테스트 코드가 빠졌습니다! 추가해주세요~!ㅎㅎ

2022-08-16 13:27 UTC, daadaadaah commented on src/Input.test.jsx
> +    <Input
Input 컴포넌트에는 어떤 props들이 있는 확인 한번 해주세요~!ㅎㅎ

2022-08-16 13:27 UTC, daadaadaah commented on src/Input.test.jsx
> +      onChange={handleClickAdd}
보통 props와 이름을 맞춥니다! `handleChange` 이런 식으로용!ㅎㅎ

2022-08-16 13:27 UTC, daadaadaah commented on src/Input.test.jsx
> +});
- 지금 총 2가지 테스트를 분리하지 않고 1개의 테스트에 작성하신 것 같아요!
    - 테스트 1 : 할일이 있을때
    - 테스트 2 : 추가 버튼 클릭할 때 
- describe-context(필요한 경우만)-it 패턴을 사용해서 1개의 테스트에 1개의 테스트 목적이 되도록 여러개의 테스트 시나리오로 쪼개봅시다!
`describe` 는 테스트 대상을 서술하고, 
`context` 는 when, with, without 만을 사용해 주어진 상황(맥락)을 서술하며, 
`it` 은 예상되는 동작(=테스트 내용)을 서술합니다.
- Input 컴포넌트로 기대하는 동작이 또 있는데, 그 동작에 대한 테스트도 추가해주세요!

2022-08-17 13:58 UTC, daadaadaah requested changes
잘하셨어요!👏👏 Input.test.jsx 좀만 다듬고 다른 컴포넌트도 한번 테스트 코드 작성해봅시다!
테스트를 영어로 작성해보시는 건 어떠신가요? ㅎㅎ어려우시겠지만 패턴이 정해져 있어서 한번 도전해봐도 괜찮을 것 같아요!ㅎㅎ

2022-08-17 13:58 UTC, daadaadaah commented on src/Input.test.jsx
> +    });
- expect 문이 빠졌네요? 이 테스트로 어떤 결과를 기대하셨는지 테스트 코드를 작성해주세요!

2022-08-17 13:58 UTC, daadaadaah commented on src/Input.test.jsx
> +  context('할 일이 입력되면', () => {
[context](https://www.betterspecs.org/#contexts)는 대비되는 상황에서 사용하는 것인데, 완료 버튼을 누른다는 상황과 대비되는 상황이 없습니다. 따라서, 그냥 it문으로만 표현해주셔도 될 거예요!

2022-08-17 13:58 UTC, daadaadaah commented on src/Input.test.jsx
> +    it('input의 value가 변경된다', () => {
지금 총 2가지 테스트를 1개의 테스트로 작성하신 것 같아요!
- 테스트 1 : `renders "할일", "추가"` ->  요소들이 보이는 테스트
- 테스트 2 : `listens change events` -> 할일 입력 테스트

it 문을 2개 사용해서 테스트를 한번 분리해줍시다!ㅎㅎ

2022-08-17 13:58 UTC, daadaadaah commented on src/Input.test.jsx
> +      const handleClick = jest.fn();
지금 테스트 상황에서 describe 바로 밑에 선언해주시면, 2번 작성 안해주셔도 될 거예요!ㅎㅎ

2022-08-18 13:50 UTC, daadaadaah requested changes
테스트 코드 작성 어느정도 감을 잡으신 것 같아서 너무 좋습니다!😊
다음 PR 기다리고 있을게요~ㅎㅎ

2022-08-18 13:50 UTC, daadaadaah commented on src/Input.test.jsx
> +describe('Input', () => {
`describe`-`context`-`it` 각각의 구문에 적어놓으신 테스트 설명이 한문장처럼 읽히도록 기재해주시는게 좋아요!
지금 상황에서 Input 을 예로 들면,
`Input 컴포넌트(describe)`은 `Rendered component(it)` 한다. 라고 읽히는데, 
한문장처럼 느껴지시지 않죠? 
반면, 아래처럼 작성하게 되면, 
```jsx
describe('Input', () => {
    it('renders 추가 button', () => {
    
    });
});
```
 `Input 컴포넌트(describe)`은 `renders 추가 button (it)` 한다. 로 읽혀서 한문장처럼 읽혀지시지 않아용?ㅎㅎit 문을 `renders a button to add task` 등 여러 방식으로 적어주실 수 있겠지만, 한문장처럼 읽혀지도록 한번 바꿔봅시당!!ㅎㅎ

2022-08-18 13:50 UTC, daadaadaah commented on src/Input.test.jsx
> +    ));
1. render~ 이부분 여러 테스트에서 사용되고 있어요~ 함수로 한번 묶어줘서 함수를 재사용해봅시당!ㅎㅎ
2. Input 컴포넌트의 빠진 prop들 다 기재해주시는게 다른 동료가 Input 컴포넌트를 파악하는데 더 수월하지 않을까요?ㅎㅎ

2022-08-18 13:50 UTC, daadaadaah commented on src/Input.test.jsx
> +    fireEvent.change(input, { target: { value: '잠자기' } });
추가 버튼 클릭 테스트 이므로, 이부분 생략해주셔도 괜찮을 것 같아요!

2022-08-18 13:50 UTC, daadaadaah commented on src/Input.test.jsx
> +    expect(handleClick).toBeCalled();
맥락 구분을 위해 한줄 띄어줍시당!ㅎㅎ

2022-08-18 13:50 UTC, daadaadaah commented on src/Input.test.jsx
> +    expect(input).toBeEnabled();
- Input에 있는 요소들이 render 되는지를 테스트 하는 것이므로, `toBeEnabled` 활성화 여부는 알필요가 없을 것 같아요!ㅎㅎ 따라서, 17줄, 18줄 테스트는 생략하셔도 괜찮을 것 같습니다. 만약, render되지 않았다면 30번째 줄에서 에러를 발생해서, 그쪽에서 파악할 수 있는 내용이거든요!ㅎㅎ`getBy*`를 사용했을 때, 에러도 잡아 낼수 있는 특징 때문에, 21번 째 줄 테스트를 아래처럼 기재해줌으로써 input 요소(Input 컴포넌트 X)의 테스트를 한곳에서 관리해줄 수 있도록 작성해 줄 수 있습니다!ㅎㅎ 한번 참고하세요~
```js
it('render input to listens to change event', () => {

});
```

2022-08-18 13:50 UTC, daadaadaah commented on src/List.test.jsx
> +  it('nothing to-do', () => {
20번째 줄과 대비되는 상황(예 : with tasks/without tasks)이므로 [context](https://www.betterspecs.org/#contexts)를 활용해 봅시다.

2022-08-18 13:50 UTC, daadaadaah commented on src/List.test.jsx
> +    expect(handleClick).toBeCalledWith();
맥락 구분을 위해 한줄 띄어줍시다!ㅎㅎ

2022-08-19 11:57 UTC, xunxee reviewed
안녕하세요🙏🏼

daadaa님의 정성스런 리뷰 감사합니다 ㅎㅎ

Input 컴포넌트의 리뷰를 반영했습니다.
- it 구문이 한 문장처럼 읽힐 수 있도록 나름? 수정을 해보았습니다.
- 중복되는 render를 함수로 만들어 재사용할 수 있도록 수정했습니다.

처음 test code를 작성하다보니
어디까지 테스트를 해야하는지 그 범위를 잘 모르겠더군용 ㅠㅠ
fireEvent로 바뀐 value를, jest-dom API 등으로 가져와보려했으나 잘 가져오지 못했습니당
그러다보니 생각보다 코드를 많이 짜지 못했군요 🥲

List 컴포넌트는 리뷰를 반영하지 못했습니닷 🐥
PR을 우선 급하게 남기고,
토요일까지 조금더 수정하며 이번주 마무리해보겠습니다!  🥹

2022-08-19 11:57 UTC, xunxee commented on src/Input.test.jsx
> +      onChange={handleClickAdd}
알겟습니당!

2022-08-19 11:57 UTC, xunxee commented on src/Input.test.jsx
> +  fireEvent.click(getByText('추가'));
onChange 이벤트와 onClick 이벤트가 발생하는 상황으로 테스트를 분리해서 진행해야겠군요!

2022-08-19 11:57 UTC, xunxee commented on src/Input.test.jsx
> +    });
넹! expect 문 작성하겠습니당

2022-08-19 11:57 UTC, xunxee commented on src/Input.test.jsx
> +  context('할 일이 입력되면', () => {
해당부분 수정했습니다! 감사합니당👍

2022-08-19 11:57 UTC, xunxee commented on src/Input.test.jsx
> +describe('Input', () => {
확실히 전달력이 있네요! 수정하겟습니당 ㅎㅎ

2022-08-19 13:28 UTC, daadaadaah requested changes
잘하셨어요!👏 it문에서 테스트 표현만 테스트 대상을 중심으로 해주시면, 괜찮을 것 같아요!
다음 PR 기다리고 있을게요~ 🚀

2022-08-19 13:28 UTC, daadaadaah commented on src/Input.test.jsx
> +  it('Click the Add button to add a task', () => {
`renders the Add button to add a task`라는 표현이 Input 컴포넌트 입장에서 좀더 적절할 것 같아요
Click은 사용자가 하는 것이구, Input 컴포넌트는 클릭할 수 있는 button을 render 하기 때문이예요!ㅎㅎ

2022-08-19 13:28 UTC, daadaadaah commented on src/Input.test.jsx
> +  it('Enter a task and a change event will occur', () => {
이 it문도 Input 컴포넌트 입장에서 한번 작성해봅시다!ㅎㅎ

2022-08-19 13:28 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
이 테스트는 어느 상황에서 어떤 결과를 기대하시고 작성하신 테스트이신가요?ㅎㅎ
input에 입력을 했을 때, 그 값이 보인다는 것을 테스트하고 싶으셨나요? 
아니면, Input 컴포넌트가 "잠자기"라는 값을 가질 때, input 요소가 "잠자기"라는 값을 가진다는 것을 테스트 하고 싶으셨나요?

2022-08-22 03:43 UTC, merged