To-do 테스트 작성하기
CodeSoom/week3-assignment-1 pull request #149
Opened 2022-08-17 11:59 UTC by ChoJinmok

2022-08-17 14:43 UTC, daadaadaah requested changes
무엇을 테스트 해야 하는지에 대해 잘 인지하고 계신 것 같아요!💪
남겨드린 코멘트를 기반으로 한번 다듬어 주세요!🚀

2022-08-17 14:43 UTC, daadaadaah commented on src/Input.test.jsx
> +  const button = utils.container.querySelector('button');
querySelector 보다 getByText 등 [query](https://testing-library.com/docs/queries/about)를 활용해봅시다!

2022-08-17 14:43 UTC, daadaadaah commented on src/Input.test.jsx
> +});
3개의 테스트 케이스로 나누신 거 너무 잘하셨어요!👍

[BDD 스타일](https://ko.javascript.info/testing-mocha#ref-1068)로 한번 바꿔봅시다! 💪 

참고
- https://marocchino.net/2016/12/04/about-rspec/
- https://johngrib.github.io/wiki/junit5-nested/

2022-08-17 14:43 UTC, daadaadaah commented on src/Input.test.jsx
> +const setup = () => {
테스트 코드에서도 중복적으로 사용되는 것들 묶어주신 것까지 생각하신 점 너무 잘하셨어요!👏
다만, 각각 value가 달라질 수도 있거나 호출 형태가 달라질 수 있는 것들은 따로 빼주시는게 좋을 것 같아요!

2022-08-17 14:43 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
이 코드는 어떤 의도로 작성하신건가용?ㅎㅎ

2022-08-17 14:43 UTC, daadaadaah commented on src/Input.test.jsx
> +  const utils = render(<Input onChange={handleChange} onClick={handleClick} />);
value라는 props가 빠졌어요!ㅎㅎ

2022-08-17 14:43 UTC, daadaadaah commented on src/Input.test.jsx
> +  const text = '코드숨 리액트 11기 화이팅!';
이번주도 화이팅!💪💪💪💪

2022-08-18 08:51 UTC, ChoJinmok commented on src/Input.test.jsx
> +  const button = utils.container.querySelector('button');
좋은 리뷰 감사합니다!

2022-08-18 12:01 UTC, ChoJinmok reviewed
BDD 반영을 하는 중인데 맞게 하고 있는지 모르겠습니당 ㅠㅠ

2022-08-18 12:01 UTC, ChoJinmok commented on src/Input.test.jsx
> +  });
handleClick함수가 실행됐을 때 input의 value를 비워주고 싶었습니다! 이런식으로 구현하는게 맞는지 고민중입니다😭

2022-08-18 12:01 UTC, ChoJinmok commented on src/Input.test.jsx
> +  const utils = render(<Input onChange={handleChange} onClick={handleClick} />);
테스트에서 사용이 안되는 것 같아서 넣어주지 않았는데 테스트에서 사용되지 않는 props도 꼭 넣어줘야할까요?~

2022-08-18 12:01 UTC, ChoJinmok commented on src/Input.test.jsx
> +});
좋은 리뷰, 자료 감사합니다!🙂

2022-08-18 12:06 UTC, ChoJinmok commented on src/Input.test.jsx
> +const setup = () => {
처음이다보니 따로 빼주는 것도 쉽지가 않네용 😭

2022-08-18 13:01 UTC, daadaadaah commented on src/Input.test.jsx
> +const setup = () => {
그래도, 과제 완성 후 중복을 제거해야겠다 라고 생각하신건 진짜 좋은 프로세스였습니다👍

2022-08-18 14:30 UTC, daadaadaah commented on src/Input.test.jsx
> +  const utils = render(<Input onChange={handleChange} onClick={handleClick} />);
넵! 다 넣어주는게 좋아요! 다른 동료가 테스트 코드를 보고, Input 컴포넌트를 이해하려고 했을 때, 다 있는 것과 각 테스트마다 일부만만 있는거 중 어느게 코드를 파악하는데 더 수월할지에 대해 생각해보시면 될 것 같아요!ㅎㅎ

2022-08-18 14:53 UTC, daadaadaah requested changes
테스트 정말 꼼꼼히 작성하신 것 같아요!👍
it 문 하나로 각각의 테스트들을 간단히 할 수 있으니, 한번 도전해봅시당!👊

2022-08-18 14:53 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
```jsx
    it('renders input to listen to change event', () => {
      const { getByPlaceholderText } = render((
        <Input />
      ));

      expect(handleChange).not.toBeCalled();

      const text = '코드숨 리액트 11기 화이팅!';

      fireEvent.change(getByPlaceholderText('할 일을 입력해 주세요'), { target: { value: text } });

      expect(handleChange).toBeCalled();
    });
```

2022-08-18 14:53 UTC, daadaadaah commented on src/Input.test.jsx
> +  context('When Input render', () => {
[context](https://www.betterspecs.org/#contexts)는 대비되는 상황에서 사용하는 것인데, Render 상황과 대비되는 상황이 없습니다. 따라서, 그냥 it문으로만 표현해주셔도 될 거예요! 지금 context로 표현된 것들 다 it문 하나로 간단히 표현해줄 수 있을 거예요! input change 테스트로 간단히 [예시 코드](https://github.com/CodeSoom/react-week3-assignment-1/pull/149#discussion_r949239418) 적어놨습니다! 한번 참고하세요

2022-08-18 14:53 UTC, daadaadaah commented on src/Input.test.jsx
> +      fireEvent.change(input, { target: { value: text } });
추가 버튼 클릭에 대한 테스트 이므로, 생략해주셔도 괜찮을 것 같아요!

2022-08-18 14:53 UTC, daadaadaah commented on src/Input.test.jsx
> +};
현재 context로 표현된 테스트들을 It문으로 변경하시면, render 만 중복될 거예요!
따라서, render 함수만 따로 함수로 빼서 재사용해봅시다!ㅎㅎ

2022-08-18 15:08 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
음..input의 value가 비워지는 상황은 handleClick함수가 실행됐을 때가 아니라 추가 버튼을 클릭했을 때로 보는게 더 맞을 것 같아요!ㅎㅎ
`input의 value가 비워지는 것`을 테스트하고 싶어서 만들었던 코드였나용?ㅎㅎ

2022-08-19 05:38 UTC, ChoJinmok commented on src/Input.test.jsx
> +  });
맞습니당!!~ 정확하세용!! `추가 버튼을 클릭했을 때 input의 value가 비워지는 것`을 테스트 하고 싶엇습니다!
계속 고민을 했었는데 Input 컴포넌트에서는 `추가 버튼을 클릭했을 때 input의 value가 비워지는 것`까지는 테스트 안해줘도 될 거 같다고 결론이 난 것 같습니당!! 맞나요..?😭

2022-08-19 05:38 UTC, ChoJinmok commented on src/Input.test.jsx
> +  const utils = render(<Input onChange={handleChange} onClick={handleClick} />);
아하!!~ 그렇네요!! 좋은 리뷰 감사합니다!!

2022-08-19 08:12 UTC, ChoJinmok commented on src/Input.test.jsx
> +  });
it에는 하나의 expect만 있으면 좋다는 걸 봤는데 꼭 하나만 있을 필요는 없는 건가요?~🤔

2022-08-19 08:12 UTC, ChoJinmok commented on src/Input.test.jsx
> +  context('When Input render', () => {
예시 감사합니다!! 테스트 코드에대해 더 이해할 수 있었습니다!👍

2022-08-19 08:14 UTC, ChoJinmok commented on src/Input.test.jsx
> +      fireEvent.change(input, { target: { value: text } });
아하!! 좋은 리뷰 감사합니다!!🙂

2022-08-19 08:15 UTC, ChoJinmok commented on src/Input.test.jsx
> +};
네!! 한번 바꿔봤습니다!! 🙂
좋은 리뷰 감사합니다!!

2022-08-19 12:05 UTC, ChoJinmok reviewed
List, Page 같은 컴포넌트들이 모이는 컴포넌트들에서 렌더링 테스트 해줄 때 자식 컴포넌트들의 모든 요소들을 모두 확인 해줘야 할까요?🙋🏻‍♂️

2022-08-19 12:48 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
정답은 없어요!ㅎㅎ정말 테스트 코드는 팀에서 다함께 결정하는 것이라서, 다른 팀원분들이 비워져야하는 것 까지 있어야 코드 이해가 더 될것 같다면, 적어주시면 되고, 굳이 이거까지 테스트 할 필요 없다라고 결론이 나면, 안해도 됩니다!ㅎㅎ질하셨어요👍

2022-08-19 12:58 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
it 문 1개의 expect 1개가 있으면 좋겠다는 의미가 it문 1개에 기대하는 결과가 1개이면 좋겠다는 의미인데, 이게 무조건 expect 1개가 아니라 관심사 1개를 의미하는 거였어요!ㅎㅎ 예를 들어, List 의 여러 아이템이 render 되는 것을 확인하고 싶으면, 아래처럼 it문 1개의 expect 여러개가 들어가지만, 결국 아이템들이 보인다는 결과 1개를 뜻하는 것이므로, expect 여러개가 들어갈 수 있겠죠! 
```jsx
    it('renders tasks', () => {
      const tasks = [
        { id: 1, title: 'Task-1' },
        { id: 2, title: 'Task-2' },
      ];

      const { getByText } = renderList(tasks);

      expect(getByText(/Task-1/)).not.toBeNull();
      expect(getByText(/Task-2/)).not.toBeNull();
    });
```

2022-08-19 13:16 UTC, daadaadaah requested changes
> List, Page 같은 컴포넌트들이 모이는 컴포넌트들에서 렌더링 테스트 해줄 때 자식 컴포넌트들의 모든 요소들을 모두 확인 해줘야 할까요?

저는 모두 작성하는 편이예요! 왜냐하면, List 컴포넌트만 따로 테스트할 때 동작하던 것이 Page 내에 넣었을 때 동작하지 않을 수 있다는 생각 때문에, 둘다 작성하는 편입니다!(그렇다고 고대로 작성하지 않고, 나름 부모 컴포넌트를 기준으로 작성하므로, 살짝 다를 수 있어요!) 테스트 작성 범위를 어느정도로 할 것이냐는 정답이 없는 것 같아요! 지금 훈련단계이므로, 많이 작성해보시는 걸 추천드려요! 많이 작성해보신 후 나는 이정도 테스트는 생략해도 괜찮을 것 같다. 이부분 다른 테스트로 대신할 수 있어서 생략할 수 있을 것 같다 등의 기준이 생기거든요!ㅎㅎ

2022-08-19 13:16 UTC, daadaadaah commented on src/List.test.jsx
> +  context('When tasks is empty', () => {
context를 적절한 상황에 잘 쓰셨어요! 잘하셨어요!👏

2022-08-19 13:16 UTC, daadaadaah commented on src/List.test.jsx
> +    it('List render', () => {
describe-context-it 에 기재된 테스트 설명을 봤을 때 한문장처럼 읽혀야 됩니다.
지금 작성해놓으신걸로 문장을 만든다면, 아래처럼 문장이 만들어집니다.
`List component 는 when tasks is empty 상황에서 List render 한다.`
여기서,`List 컴포넌트가 List를 render한다` 말은 좀 어색한 것 같아요!
List component가 무엇을 렌더하는지에 대해 생각해봅시다!ㅎㅎ(예 : `List component(describe) 는 when tasks is empty 상황(context)에서 renders XXX(it)한다`)
또한, 다른 테스트도 동일하게 한문장으로 읽히는지 한번 체크해주세요!

2022-08-19 13:16 UTC, daadaadaah commented on src/List.test.jsx
> +      }
forEach로 하면 좀더 간단히 표현할 수 있을 것 같아요!

2022-08-19 13:16 UTC, daadaadaah commented on src/Input.test.jsx
> +  const setup = (value = '') => render(
맥락 구분을 위해 한줄 띄어줍시당! ㅎㅎ

2022-08-19 13:23 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
이 테스트는 어느 상황에서 어떤 결과를 기대하시고 작성하신 테스트이신가요?ㅎㅎ지금 작성해 놓으신 it문만으로 파악하기 어렵네요😅

2022-08-20 10:12 UTC, ChoJinmok commented on src/Input.test.jsx
> +  });
아!~ 정답이 있는건 아니었군용?~ 확실히 앞으로 계속 고민하고 생각해봐야할 것 같네요!!ㅎㅎ
좋은 리뷰 감사합니다!!

2022-08-20 10:19 UTC, ChoJinmok commented on src/List.test.jsx
> +  context('When tasks is empty', () => {
리뷰해주신대로 대비되는 상황에 사용했습니당!! 감사합니다!! ㅎㅎ

2022-08-20 10:43 UTC, ChoJinmok commented on src/Input.test.jsx
> +  });
아하! it문에 1개의 관심사만 있으면 되는거군요!?ㅎㅎ 좋은 리뷰감사합니다!

2022-08-20 10:44 UTC, ChoJinmok commented on src/List.test.jsx
> +      }
forEach를 사용하니 가독서이 훨씬 좋은 것 같습니다!! 좋은 리뷰 감사합니다!!

2022-08-20 10:45 UTC, ChoJinmok commented on src/Input.test.jsx
> +  const setup = (value = '') => render(
앗 ㅎㅎ 좋은 리뷰감사합니다!

2022-08-20 10:49 UTC, ChoJinmok commented on src/Input.test.jsx
> +  });
`change 이벤트가 일어난 후 state가 변하고 변한 state가 value에 적용되는 테스트`를 하고 싶었습니다!!

2022-08-20 10:51 UTC, ChoJinmok commented on src/List.test.jsx
> +    it('List render', () => {
아~ 리뷰 덕분에 조금씩 어떻게 테스트를 작성해야하는지 감이 잡히는 것 같습니다!!ㅎㅎ 좋은 리뷰 감사합니다!!

2022-08-21 03:14 UTC, daadaadaah requested changes
오오! 어느정도 테스트 코드 작성에 감을 잡으신것 같아서 기분이 좋네용😊
App.test.jsx 의 삭제 버튼 클릭 테스트는 아직 진행중이신거죵?ㅎㅎ
아샬님 피드백 강의 보면서 나의 코드와 어떤게 다른지도 한번 비교해보세요!ㅎㅎ

2022-08-21 03:14 UTC, daadaadaah commented on src/List.test.jsx
> +    it('renders list', () => {
`list` 보다 `tasks`가 좀더 의도를 드러내는 것 같아요!

2022-08-21 03:14 UTC, daadaadaah commented on src/Item.test.jsx
> +  it('renders list & button', () => {
`list` 보다 `tasks`가 좀더 의도를 드러내는 것 같아요!

2022-08-21 03:14 UTC, daadaadaah commented on src/Page.test.jsx
> +  it('renders h1', () => {
h1 이라는 HTML 요소보다 그냥 "To-do"로 표현해주시는게 좋을 것 같아요!

2022-08-21 03:14 UTC, daadaadaah commented on src/Page.test.jsx
> +describe('Page component', () => {
각각의 요소와 컴포넌트가 렌더된다고 테스트하기 보다 묶어주시는 건 어떠신가요? Page 컴포넌트가 통합 컴포넌트라는 것을 표현해주기 위해서요!

2022-08-21 03:14 UTC, daadaadaah commented on src/Item.test.jsx
> +  it('renders list & button', () => {
list 보다 tasks가 좀더 의도를 드러내는 것 같아요!

2022-08-21 03:14 UTC, daadaadaah commented on src/List.test.jsx
> +    it('render paragraph', () => {
paragraph 보다 "할 일이 없어요" 로 표현해주시는게 좋을 것 같아요!

2022-08-21 07:16 UTC, ChoJinmok commented on src/List.test.jsx
> +    it('renders list', () => {
아~! 좋은 리뷰 감사합니다!🙂

2022-08-21 07:16 UTC, ChoJinmok commented on src/Item.test.jsx
> +  it('renders list & button', () => {
좋은 리뷰 감사합니다!🙂

2022-08-21 07:18 UTC, ChoJinmok commented on src/Page.test.jsx
> +  it('renders h1', () => {
그렇네요! To-do가 더 좋은 표현 같네요! 좋은 리뷰 감사합니다!🙂

2022-08-21 07:20 UTC, ChoJinmok commented on src/Item.test.jsx
> +  it('renders list & button', () => {
좋은 리뷰 감사합니다!🙂

2022-08-21 07:26 UTC, ChoJinmok commented on src/List.test.jsx
> +    it('render paragraph', () => {
좋은 리뷰 감사합니다!🙂

2022-08-21 07:52 UTC, ChoJinmok commented on src/Page.test.jsx
> +describe('Page component', () => {
그렇군용!! 확실히 이렇게 해주니까 통합 컴포넌트라는 느낌이 더 드는 것 같습니다!! 좋은 리뷰 감사합니다!🙂

2022-08-22 03:43 UTC, merged