To-do 테스트 작성하기
CodeSoom/week3-assignment-1 pull request #155
Opened 2022-10-25 16:44 UTC by yxxnhx

# 목표
## To-do 테스트 작성하기

## 진행사항

### 2-3일차
강의를 듣고 List 파일을 할일이 있을 경우, 없을경우를 나누어 테스트 파일을 생성하였습니다
현재 jest, tdd에 대해서 많은 지식이 없어서 다른 분들은 어떻게 하셨는지 참고하여서 describe와 context에 대해 공부하면서 작성하고 있습니다.

2022-10-26 09:09 UTC, daadaadaah requested changes
빠른 PR에 더불어 테스트코드도 잘 작성하셔서 너무 기분이 좋네요!👏👏👏
다음 PR 기다리고 있을게요~ㅎㅎ

2022-10-26 09:09 UTC, daadaadaah commented on src/List.test.jsx
> +  const renderElement = (task) => (
`Element` 보다 좀더 의도가 드러나는 단어를 사용하게 좋을 것 같아요!

2022-10-26 09:09 UTC, daadaadaah commented on src/List.test.jsx
> +  const onClickDelete = jest.fn();
props 명이 아니므로, handleXXX으로 하는게 더 좋을 거 같아요!

2022-10-26 09:09 UTC, daadaadaah commented on src/List.test.jsx
> +  const renderElement = (task) => (
맥락 구분을 위해 서로 띄어줍시다!ㅎㅎ

2022-10-26 09:09 UTC, daadaadaah commented on src/List.test.jsx
> +    it('입력한 할 일이 출력된다', () => {
이것도 "렌더링된다"라고 표현하는게 더 좋을 것 같아요!ㅎㅎ

2022-10-27 03:49 UTC, yxxnhx commented on src/List.test.jsx
> +  const renderElement = (task) => (
넵 반영하여 수정하겠습니다!

2022-10-27 03:50 UTC, yxxnhx commented on src/List.test.jsx
> +    it('입력한 할 일이 출력된다', () => {
넵 랜더링으로 수정하겠습니다

2022-10-27 03:50 UTC, yxxnhx commented on src/List.test.jsx
> +  const onClickDelete = jest.fn();
아하 제가 자꾸 헷갈리네요ㅠㅠ 변경하겠습니다!

2022-10-27 03:51 UTC, yxxnhx commented on src/List.test.jsx
> +  const renderElement = (task) => (
네 변수명을 조금 더 고민해보겠습니다

2022-10-28 02:15 UTC, daadaadaah requested changes

2022-10-28 02:15 UTC, daadaadaah commented on src/Input.test.jsx
> +  );
render 함수도 중복되는데, render 함수 까지 같이 빼지 않은 이유가 있으신가용?ㅎㅎ

2022-10-28 02:15 UTC, daadaadaah commented on src/Input.test.jsx
> +    expect(input).toHaveAttribute('value', '잠자기');
맥락 구분을 위해 30줄이랑 31줄, 31줄이랑 36줄 각각 다 한줄씩 띄어주시는게 좋아요!(다른 부분도 마찬가지구요!)

2022-10-28 02:15 UTC, daadaadaah commented on src/Input.test.jsx
> +  it('Input에 입력한 값이 제대로 랜더링되는가', () => {
List.test.jsx 파일에서 기재한 것(`~렌더링된다.`)처럼 표현해주시면 좋을 것 같아요!(16번 테스트도요!)

2022-10-28 02:17 UTC, daadaadaah requested changes

2022-10-28 02:17 UTC, daadaadaah commented on src/List.test.jsx
> +  );
https://github.com/CodeSoom/react-week3-assignment-1/pull/155#discussion_r1007538376 이 리뷰 참고해주세요!ㅎㅎ

2022-10-28 02:17 UTC, daadaadaah commented on src/List.test.jsx
> +      getByText('할 일이 없어요!');
expect 문이 빠진 것 같아요!ㅎㅎ

2022-10-28 12:06 UTC, yxxnhx commented on src/Input.test.jsx
> +  );
아하 그냥 안에 내용만 따로 빼야 된다고 생각했는데 render까지 빼도 괜찮군요! 그렇다면 render까지 함께 빼겠습니다~!

2022-10-28 12:45 UTC, yxxnhx commented on src/Input.test.jsx
> +    expect(input).toHaveAttribute('value', '잠자기');
아 넵넵 맥락 구분까지 염두해서 다음부터는 코드를 짜고 정리할 수 있도록 하겠습니다

2022-10-28 12:45 UTC, yxxnhx commented on src/Input.test.jsx
> +  it('Input에 입력한 값이 제대로 랜더링되는가', () => {
넵! 수정하겠습니다!

2022-10-28 12:46 UTC, yxxnhx commented on src/List.test.jsx
> +  );
넵 반영하겠습니다!

2022-10-28 12:49 UTC, yxxnhx commented on src/List.test.jsx
> +      getByText('할 일이 없어요!');
앗 그렇네요 추가하겠습니다!

2022-10-29 06:27 UTC, daadaadaah requested changes
> 그런데 위와 같이 계속해서 동일한 코드가 겹쳐서 그 부분을 바깥으로 빼서 정리를 하고 싶은데 it 외부에 뺄 시에는 계속 동일한 오류가 납니다.
따로 정리를 할 수 있는 방법이 없을까요?
- 저라면 중복되는 거 함수로 뺄 것 같은데, 어떻게 빼셔서 어떤 오류가 났는지 보여주시면, 답변하는데 더 도움이 될 것 같아요!ㅎㅎ


> 그리고 궁금한 것이 있는데 프로젝트 규모가 더 커져서 페이지가 여러 개가 되고, 나눈 컴포넌트가 여러가지일 경우에도 현재와 같이 동일하게 src 폴더 안에 기존 jsx파일과 test.jsx 파일을 함께 두는 것이 맞나요?
아니면 test 폴더를 따로 생성해서 test 파일만 관리하는 것이 맞나요?
- 이건 팀마다 다를 것 같아요! 아샬님이 함께 두는 편이라, 보통 함께 둡니다!ㅎㅎ

2022-10-29 06:27 UTC, daadaadaah commented on src/App.test.jsx
> +    });
이 테스트의 의도가 궁금합니다! `값을 입력하면, 입력된 값이 보인다` 이거나 `추가 버튼이 렌더링 된다`로 테스트가 이루어질 것 같은데, 둘이 섞인 것 같아서요!

2022-10-29 06:27 UTC, daadaadaah commented on src/Page.test.jsx
> +  it('Page에 할일, 추가, 삭제 버튼이 있는가', () => {
테스트 이름 수정해주세요!ㅎㅎ

2022-10-29 06:27 UTC, daadaadaah commented on src/App.test.jsx
> +  const appElement = () => render((<App />));
함수명에 의도가 좀더 드러나면 좋을 것 같아요! appElement 만 보면, 처음 코드를 본 동료가 어떤 함수인지 의문이 들 것 같아요!

2022-10-29 06:27 UTC, daadaadaah commented on src/App.test.jsx
> +      const addTaskButton = getByText('추가');
버튼들 변수화해서 쓰시는데, 이유가 궁금합니다!ㅎㅎ

2022-10-29 06:27 UTC, daadaadaah commented on src/App.test.jsx
> +    it('"삭제" 버튼이 랜더링된다', () => {
테스트에 삭제 버튼이 렌더링 되는지만 확인하면 될 것 같아요! 테스트 목적에 맞게 불필요한 코드들은 지워봅시다!

2022-10-29 08:39 UTC, yxxnhx commented on src/Page.test.jsx
> +  it('Page에 할일, 추가, 삭제 버튼이 있는가', () => {
앗 수정하겠습니다!

2022-10-29 08:39 UTC, yxxnhx commented on src/App.test.jsx
> +  const appElement = () => render((<App />));
넵 조금 더 의도에 맞게 수정하겠습니다

2022-10-29 08:40 UTC, yxxnhx commented on src/App.test.jsx
> +      const addTaskButton = getByText('추가');
조금 더 명확하게 버튼을 사용하고 싶어서 했었는데 불필요한가요?
불필요하다면 변수화하지 않고 바로 사용하겠습니다!

2022-10-29 08:40 UTC, yxxnhx commented on src/App.test.jsx
> +    it('"삭제" 버튼이 랜더링된다', () => {
넵 불필요한 코드는 지우겠습니다~!

2022-10-29 08:41 UTC, yxxnhx commented on src/App.test.jsx
> +    });
앗 그렇네요 값이 보이는 것과 추가 버튼이 랜더링 되는 것 두 개로 나누어 작성하겠습니다!

2022-10-30 03:06 UTC, daadaadaah commented on src/App.test.jsx
> +      const addTaskButton = getByText('추가');
때에 따라서 다르겠지만, 지금 상황에서 "추가"라는 텍스트가 있어서 변수화 하지 않아도 될 것 같아요!ㅎㅎ
혹시, 버튼이라는 걸 드러내고 싶으면, 아래처럼 `getbyRole`를 활용할 수 있을 것 같아요!ㅎㅎ
```js
getbyRole('button', { name: /추가 })
```

2022-10-30 03:31 UTC, daadaadaah requested changes

2022-10-30 03:31 UTC, daadaadaah commented on src/App.test.jsx
> +      },
App.test.jsx 모든 테스트에 ChangeInput 이라는 함수가 필요한 건가요?

2022-10-30 03:31 UTC, daadaadaah commented on src/App.test.jsx
> +    context('값을 입력하면', () => {
`값`보다 `할일`이라고 표현해주시는게 좀더 의도가 드러나는 것 같아요!ㅎㅎ

2022-10-30 03:31 UTC, daadaadaah commented on src/Input.test.jsx
> +  const InputElement = () => render((<Input
함수 이름은 함수의 역할이 드러나는 표현을 적어주시는게 좋아요! 지금 단순히 Input 요소가 아니라 Input 요소가 렌더링되는게 함수 역할이 아닐까 생각해요!(다른 테스트에도 마찬가지로 적용시켜주세요!)

2022-10-30 03:31 UTC, daadaadaah commented on src/Input.test.jsx
> +  const InputElement = () => render((<Input
맥락 구분을 위해 한줄 띄어줍시당!ㅎㅎ

2022-10-30 03:31 UTC, daadaadaah commented on src/Input.test.jsx
> +    expect(handleClick).toBeCalled();
맥락 구분을 위해 한줄 띄어줍시당!ㅎㅎ(다른 곳도 마찬가지로 적용시켜주세요!)

2022-10-30 03:31 UTC, daadaadaah commented on src/Input.test.jsx
> +  });
1. 28줄이 없어도 34줄이 통과될 거예요! '잠자기2'로 value 변경했을 때, '잠자기2'가 보이는지 한번 테스트해보세요! 만약, 테스트가 안된다면, 왜 안되는지에 대해 한번 고민해봅시다!ㅎㅎ
2. 이런 문제가 발생하지 않기 위해서 함수를 묶어줄 때 어떻게 해야될지도 함께 고민해보시는게 좋을 것 같아요!ㅎㅎ

2022-10-30 03:31 UTC, daadaadaah commented on src/List.test.jsx
> +      ];
tasks 가 다른 테스트에서도 사용되고 있어요! 이렇게 여러 곳에서 사용되는 데스트용 데이터를 보통 fixture라고 이야기합니다. 저는 이러한 데이터를 `fixtures` 폴더 하나를 만들어서 따로 관리하는 편이에요!

2022-10-30 03:31 UTC, daadaadaah commented on src/Page.test.jsx
> +  });
테스트 이름에 맞게 테스트 코드가 작성되지 않은 것 같아요! 한번 체크해주세요!

2022-10-30 03:31 UTC, daadaadaah commented on src/List.test.jsx
> +    it('입력한 할 일이 랜더링된다', () => {
`입력한`은 빼고 작성해주시는게 좋을 것 같아요! 지금은 그냥 props로 받은 tasks가 렌더링 되는 것을 확인하는 테스트이지, 사용자가 입력해서 상태가 변경되는지 확인하는 테스트가 아니라고 생각하기 때문이예요!ㅎㅎ

2022-10-30 05:11 UTC, yxxnhx commented on src/App.test.jsx
> +      const addTaskButton = getByText('추가');
아하 그렇군요 그렇다면 getbyRole을 활용하여 다시 해보겠습니다!

2022-10-30 05:15 UTC, yxxnhx commented on src/App.test.jsx
> +      },
값을 넣어 테스트하는 경우에는 모두 필요해서 renderApp에 넣어서 구조분해할당으로 사용을 했는데 그렇게 하면 안되나요?

2022-10-30 05:16 UTC, yxxnhx commented on src/App.test.jsx
> +    context('값을 입력하면', () => {
넵 의도에 맞게 수정하겠습니다~!

2022-10-30 05:20 UTC, yxxnhx commented on src/Input.test.jsx
> +  const InputElement = () => render((<Input
넵 변경해보겠습니다

2022-10-30 05:48 UTC, yxxnhx commented on src/Input.test.jsx
> +  });
지워서 테스트를 돌려보니 이미 기본 값으로 들어가 있는 상태여서 해당 부분이 필요가 없었던 것이었네요
그래서 함수로 묶은 부분에서 그냥 값을 넣지 않고 변수로 빼서 테스트를 할 때 그 인자로 받은 변수의 값을 넣어주는 방식으로 바꾸어보았습니다
이 방법이 맞는 것을까요? 아니라면 혹시 다른 방법이 있을까요?

2022-10-30 06:00 UTC, yxxnhx commented on src/List.test.jsx
> +      ];
넵 분리하여 수정해보겠습니다~!

2022-10-30 06:01 UTC, yxxnhx commented on src/Page.test.jsx
> +  });
아하 그렇네요 테스트 명을 수정해보겠습니다

2022-10-30 06:01 UTC, yxxnhx commented on src/List.test.jsx
> +    it('입력한 할 일이 랜더링된다', () => {
그렇네요.. 테스트를 짤 때 조금 더 고민을 해봐야겠군요ㅠㅠ

2022-10-31 04:07 UTC, daadaadaah requested changes
이번주도 수고 많으셨습니다!ㅎㅎ 다음주에도 같이 힘내봐요👊

2022-10-31 04:07 UTC, daadaadaah commented on src/App.test.jsx
> +      },
구조분해할당 같은 기술을 사용해보시는거 잘하셨어요!👍
다만, 지금 App.test.jsx를 보면, 값을 넣어 테스트 하는 부분도 있고 아닌 부분도 있어서 말씀드린거였어요!ㅎㅎ 만약, 모든 App.test.jsx 테스트에 changeInput이 필요한 경우라면, 있어도 되겠지만, 그게 아니라서요!
만약, 값을 넣어서 테스트 하는 부분이 중복되어 함수로 묶어 주고 싶다면, 그 부분만 묶어주셔서 사용해주셔도 됩니다!ㅎㅎ

2022-10-31 04:07 UTC, daadaadaah commented on src/App.test.jsx
> +      it('onChange가 실행된다', () => {
App 컴포넌트의 관심사에 대해 한번 생각해보면, onChange 실행이 아니라 상태가 변경된다고 기재하시는게 더 좋을 것 같아요!

2022-10-31 04:07 UTC, daadaadaah commented on src/Input.test.jsx
> +  const InputElement = (taskTitle = '') => render((<Input
render랑 같이 빼주셨으면, 함수명도 그에 맞게 바꿔주시는게 좋을 거 같아요!ㅎㅎ
App.test.jsx에서는 하셔서 어떻게 하시는지 아시는 것 같은데, 깜박하신거 같아요!ㅎㅎ(다른 부분도 마찬가지로 반영해주세요!ㅎㅎ)

2022-12-20 00:18 UTC, merged