Input test작성
CodeSoom/week3-assignment-1 pull request #157
Opened 2022-10-27 11:48 UTC by hyeji07

**react-week3-assignment-1**

안녕하세요 jest, TDD를 처음 접해봐서 너무 어렵네요 ㅠㅠ
작성하는 데 어려움이 있어서 다른 사람들이 올린 코드를 보고 학습하고 있는데도 아직 잘 모르겠습니다.. 
더 공부하면서 나머지 과제도 올려보겠습니다..!

2022-10-28 02:09 UTC, daadaadaah requested changes
처음하셨다고 했는데, 그래도 잘 작성하신 것 같아요!ㅎㅎ
저는 테스트 코드 작성할 때, 크게 2단계로 나눠서 생각해요!
1) 무엇을 테스트 할지 (-> 관련해서 도움될만한 리뷰 링크 남겨두었습니다!)
- https://github.com/CodeSoom/react-week3-assignment-1/pull/134#pullrequestreview-1013694078
- https://github.com/CodeSoom/react-week3-assignment-1/pull/138#pullrequestreview-1015192093
2) 1번을 테스트 코드로 어떻게 작성할지 (-> 이부분은 jest, React-testing-libarary 공식 문서 참고하세요!)
- 어느 단계에서 모르는지 한번 생각해보시고, 관련 링크들 한번 공부해보세요!
추가로 도움될만한 링크 남겨놉니다.
  - https://johngrib.github.io/wiki/junit5-nested/#describe---context---it-%ED%8C%A8%ED%84%B4
  - https://marocchino.net/2016/12/04/about-rspec/
  - https://ko.javascript.info/testing-mocha#ref-888
  - https://github.com/ahastudio/til/blob/main/ruby/20161206-rspec-let.md
  - [Ginkgo - Go 언어 개발자를 위한 BDD 테스팅 프레임워크](https://www.youtube.com/watch?v=gfTsSBRvdqI)

2022-10-28 02:09 UTC, daadaadaah commented on src/Input.test.jsx
> +  const onChange = jest.fn();
onXXX 보다 handleXXX으로 표현해주시는게 더 좋을 것 같아요!ㅎㅎ

2022-10-29 07:19 UTC, hyeji07 commented on src/Input.test.jsx
> +  const onChange = jest.fn();
네넵!

2022-10-29 07:19 UTC, hyeji07 commented
해설 강의 참고하여 다시 커밋하였습니다!

2022-10-30 03:01 UTC, daadaadaah requested changes
코드를 통일감 있게 작성해주시는 것만 연습하면 좋을 것 같아요!ㅎㅎ잘하셨어요👏

2022-10-30 03:01 UTC, daadaadaah commented on src/App.test.jsx
> +  ]; */
다음에는 불필요한 주석은 정리하고 PR 보내주세요!ㅎㅎ

2022-10-30 03:01 UTC, daadaadaah commented on src/App.test.jsx
> +  const appContents = () => render((<App />));
함수명은 함수의 역할을 명확히 드러나게 표현해주시는게 좋아요!
지금 `appContents`라는 단어만 보면, 함수가 무슨 역할을 하는지 명확히 알기 어려운것 같아요😭

2022-10-30 03:01 UTC, daadaadaah commented on src/App.test.jsx
> +    });
`완료 버튼이 렌더링 된다`라는 테스트에 너무 많은 걸 확인하는 것 같아요!
완료 버튼이 렌더링 되는지 여부만 확인할 수 있는 코드만 작성해주시는게 좋을 것 같아요!ㅎㅎ

2022-10-30 03:01 UTC, daadaadaah commented on src/App.test.jsx
> +    });
value가 입력 안되어도 "추가" 버튼이 보이지 않아용?ㅎㅎ어떤 상황을 테스트 해보고 싶으셨나요?ㅎㅎ

2022-10-30 03:01 UTC, daadaadaah commented on src/Input.test.jsx
> +    ));
테스트 코드 리팩터링을 해주시는게 좋아요!
테스트 코드를 다 작성 후 중복되는 것이 없나 한번 체크하는 습관을 들이시는 걸 추천드려요!ㅎㅎ

2022-10-30 03:01 UTC, daadaadaah commented on src/List.test.jsx
> +  }
저라면 renderXX 함수를 동일한 형태로 통일해줄 것 같아요!
어디서는 화살표 함수(예 : App.test.jsx), 어디서는 요소만(예: Page.test.jsx)있는 형태여서 `왜 다르고 어떤 기준으로 다른게 표현한거지?` 라는 생각이 들거든요!

2022-10-30 03:01 UTC, daadaadaah commented on src/List.test.jsx
> +    ];
tasks 가 다른 테스트에서도 사용되고 있어요! 이렇게 여러 곳에서 사용되는 데스트용 데이터를 보통 fixture라고 이야기합니다. 저는 이러한 데이터를 `fixtures` 폴더 하나를 만들어서 따로 관리하는 편이에요!

2022-10-30 03:01 UTC, daadaadaah commented on src/List.test.jsx
> +    it('renders tasks', () => {
테스트 이름 또는 설명도 어디서는 영문, 어디서는 한글인데, 하나로 통일해주시는게 좋을 것 같아요!ㅎㅎ

2022-10-30 08:16 UTC, hyeji07 commented on src/App.test.jsx
> +  const appContents = () => render((<App />));
넵 renderApp으로 변경하였습니다

2022-10-30 08:29 UTC, hyeji07 commented on src/App.test.jsx
> +    });
"value가 입력되면 handleChange함수가 실행된다"로 변경하였습니다..ㅎㅎ

2022-10-30 08:46 UTC, hyeji07 commented on src/List.test.jsx
> +  }
넵 function함수로 통일 시켰습니다!

2022-10-30 09:09 UTC, hyeji07 commented on src/App.test.jsx
> +    });
`expect(container).toHaveTextContent('독서');` 를 삭제하였습니다

2022-10-30 09:28 UTC, hyeji07 commented
리뷰반영하여 다시 커밋하였습니다!

2022-10-30 09:31 UTC, hyeji07 commented on src/Input.test.jsx
> +    ));
넵 중복되는 코드를 함수로 선언하였습니다!

2022-10-31 03:58 UTC, daadaadaah requested changes

2022-10-31 03:58 UTC, daadaadaah commented on src/Page.test.jsx
> +        onClickDeleteTask={handleClickDeleteTask}
다음 과제에서는 데이터는 데이터 끼리, 함수는 함수끼리 정렬해주시면 좋을 것 같아요!ㅎㅎ

2022-10-31 03:58 UTC, daadaadaah commented on src/App.test.jsx
> +    });
테스트로 알고 싶은게 혹시, `할일을 입력하면, 입력창에 입력한 할일이 보인다`는 걸 테스트 하고 싶으셨나요? 아니면, `추가버튼을 누르면 할일이 추가된다`는 걸 테스트하고 싶으셨나요? 테스트 이름에 맞게 테스트 코드를 바꾸거나 테스트 코드에 맞게 테스트 이름을 바꾸는게 좋을 것 같아요! 필요하다면, 2개의 테스트로 쪼개도 될 것 같아요!

2022-10-31 03:58 UTC, daadaadaah commented on src/App.test.jsx
> +    it('"완료"버튼이 랜더링된다', () => {
이 테스트도, 완료버튼이 렌더링이 되는 게 궁금했는지, 완료버튼을 눌렀을 때, 할일이 삭제되는게 궁금했는지, 2개가 섞여서 테스트 코드가 작성된 것 같아요!

2022-12-20 00:18 UTC, merged