3주차 과제 - To-do 테스트 작성하기
CodeSoom/week3-assignment-1 pull request #159
Opened 2022-12-20 11:25 UTC by naji0001

안녕하세요 트레이너님!
테스트 코드를 작성하는 것은 이번이 처음입니다.
그래서 matcher중에 어떤 것을 사용해야 되는지 
테스트 코드를 어느 범위까지 작성해야되는지 
가늠이 잘 안가서 좀 헤맸습니다.
피드백주시면 감사하겠습니다!

2022-12-21 03:17 UTC, daadaadaah requested changes
오! 혹시, 테스트 코드 개인적으로 공부해보셨나요? 완성도 높게 과제를 제출해주셨어요👍

2022-12-21 03:17 UTC, daadaadaah commented on src/Input.test.jsx
> +  const renderInput = (value = '') => render((
오! 함수를 활용해서 중복을 제거 하셨군요! 잘하셨어요!👏

2022-12-21 03:17 UTC, daadaadaah commented on src/Page.test.jsx
> +    ];
- 현재, tasks  데스트용 데이터가  여러 곳에서 사용되고 있어요. 이렇게  여러 곳에서 사용되는 테스용 데이터를 보통 fixture라고 이야기합니다.`fixtures` 폴더 하나를 만들어서 이러한 데이터를 따로 관리해봅시다!

2022-12-21 03:17 UTC, daadaadaah commented on src/App.test.jsx
> +  context('when first render', () => {
context는 보통 대비되는 상황에서 활용하는 것이 좋아요! 작성해주신 List.test.jsx 처럼요!
지금은 it문으로만 표현해주셔도 괜찮습니다! 30줄도 마찬가지구요!

2022-12-21 12:09 UTC, naji0001 commented on src/App.test.jsx
> +  context('when first render', () => {
피드백 주신 내용으로 리팩토링 했습니다!

2022-12-21 13:34 UTC, daadaadaah requested changes

2022-12-21 13:34 UTC, daadaadaah commented on src/Page.test.jsx
> +  it('renders empty input when click add', () => {
테스트로 알고 싶은 건 실제로 input 에 텍스트를 작성하는 이벤트를 발생시키면 handleChange 가 호출되느냐일 거에요. 이럴 때, 저라면, `listens change event` 라고 작성하는 편입니다. click 이벤트 호출이라면, `listen click event`로 작성할 것 같구요!

2022-12-21 13:34 UTC, daadaadaah commented on src/Page.test.jsx
> +      onClickDeleteTask={handleClickDelte}
변수명은 변수명끼리 함수명은 함수명끼리 모아서 정렬해주시면 좋을 것 같아요!

2022-12-22 10:58 UTC, naji0001 commented
수정했습니다! 리뷰 요청드립니다!

2022-12-22 12:43 UTC, daadaadaah approved these changes
잘하셨어요!👏 아샬님 피드백 강의 들으면서 아샬님은 어떻게 하셨는지 잘 관찰해보세요~
주간회고 하시는 것도 잊지 마시구요!ㅎㅎ

2022-12-26 11:58 UTC, merged