3주차 과제 - To-do 테스트 작성하기
CodeSoom/week3-assignment-1 pull request #160
Opened 2022-12-20 12:40 UTC by KwangMin-Moon

안녕하세요 트레이너님:)

테스트 코드 아직 감을 못잡아서 강의 그대로 따라하면서 진행 중입니다.

jest와 리액트 테스팅 라이브러리 사용법에 아직 익숙하지 않아 원하는 테스트를 어떻게 해야할지 헤매고 있어요

조금씩 보완해 나가겠습니다.

피드백 부탁드립니다:)

2022-12-21 03:07 UTC, daadaadaah requested changes
처음 테스트 코드 작성하는거 많이 어려우시죠ㅠㅠ그래도, 조금이라도 작업해서 PR 날려주신 점 너무 잘하셨어요!👏

1. 테스트 코드 작성
-  제가 테스트를 어떻게 발견하는지와 도움될만한 링크 남겨놓았습니다! 한번 참고하세요!
- [https://github.com/CodeSoom/react-week3-assignment-1/pull/134#pullrequestreview-1013694078](https://github.com/CodeSoom/react-week3-assignment-1/pull/134#pullrequestreview-1013694078)
- [https://github.com/CodeSoom/react-week3-assignment-1/pull/138#pullrequestreview-1015192093](https://github.com/CodeSoom/react-week3-assignment-1/pull/138#pullrequestreview-1015192093)

2. 어떤 matcher를 사용해야하는지에 대해서 저는 아래 링크 보고 참고합니다!
- https://github.com/testing-library/jest-dom#custom-matchers

2022-12-21 03:07 UTC, daadaadaah commented on src/input.test.jsx
> +test('Input', () => {
- 저는 test를 정말 간단한 테스트에만 사용하고, 되도록 BDD 스타일(describe -context-it) 같이 테스트를 작성하는 템플릿를 사용하는 걸 선호 편입니다! BDD스타일(describe-context-it)로 한번  관련해서 아래 링크들이 도움될 거예요!

[참고]
- https://johngrib.github.io/wiki/junit5-nested/#describe---context---it-%ED%8C%A8%ED%84%B4
- https://marocchino.net/2016/12/04/about-rspec/
- https://ko.javascript.info/testing-mocha#ref-888
- https://github.com/ahastudio/til/blob/main/ruby/20161206-rspec-let.md
- [Ginkgo - Go 언어 개발자를 위한 BDD 테스팅 프레임워크](https://www.youtube.com/watch?v=gfTsSBRvdqI)

- 한가지 테스트에 너무 많은 걸 테스트 하고 있어요! describe-context-it를 이용해서 1개의 테스트에 1개의 기대만 할 수 있도록 수정해봅시다!

2022-12-21 17:08 UTC, KwangMin-Moon commented on src/input.test.jsx
> +test('Input', () => {
오늘은 시간이 많지 않아 자료 참고해서 Input 컴포넌트만 테스트 코드 작성했습니다.
트레이너님 덕분에 조금씩 감을 잡는거 같아요 감사드립니다:)

<질문>
원하는 태그를 선택할 때 getByTestId로 선택을 하려면 테스트할 컴포넌트의 id를 수정해야만 하는 건가요?

2022-12-22 12:45 UTC, daadaadaah commented on src/input.test.jsx
> +test('Input', () => {
직접 공식문서를 보시는 게 더 좋을 것 같아 관련 링크 남깁니다!
- 참고 : https://testing-library.com/docs/queries/bytestid/

2022-12-22 12:46 UTC, daadaadaah requested changes

2022-12-22 12:46 UTC, daadaadaah commented on src/input.test.jsx
> +      expect(getByRole('button')).toBeInTheDocument();
구체적으로 어떤 버튼인지 의도를 드러나게 표현하려면 어떻게 하는게 좋을까요?

2022-12-22 12:46 UTC, daadaadaah commented on src/input.test.jsx
> +      expect(addTodo).toBeCalled();
맥락 구분을 위해 한줄씩 띄어줍시다!

2022-12-22 12:46 UTC, daadaadaah commented on src/input.test.jsx
> +  const inputComponentRender = () => render(<Input value={newTodo} onChange={setNewTodos} onClick={addTodo} />);
props가 3개이상부터는 새로 정렬해주는게 가독성에 더 좋은 것 같아요! ㅎㅎ

2022-12-23 15:25 UTC, daadaadaah requested changes

2022-12-23 15:25 UTC, daadaadaah commented on src/input.test.jsx
> +    render(<Input value={newTodo} onChange={setNewTodos} onClick={addTodo} />);
props가 3개 이상일 경우, 새로정렬로 해주시면 가독성에 더 좋을 것 같아요!

2022-12-23 15:25 UTC, daadaadaah commented on src/input.test.jsx
> +  context('first rending', () => {
context는 대비되는 상황에서 사용하는 편입니다. 예를 들어, 할일이 없을 경우/있을 경우 처럼요!
지금 상황에서는 그냥 context 없이 it문으로만 표현해주셔도 될 것 같아요!

2022-12-23 15:25 UTC, daadaadaah commented on src/list.test.jsx
> +    render(<List tasks={tasks} onClickDelete={onClickDelete} />);
중괄호과 생략 가능하지만, 가독성을 위해 매번 붙여주시는게 좋아요!

2022-12-23 15:25 UTC, daadaadaah commented on src/list.test.jsx
> +      const tasks = ['todo1', 'todo2'];
`tasks`가 다른 테스트에서도 사용되고 있어요!
이렇게 테스트용 데이터를 `fixture`라고 부르는데, 저는 `fixtures` 폴더 하나 만들어서 따로 관리하는 편입니다.

2022-12-23 15:25 UTC, daadaadaah commented on src/list.test.jsx
> +    });
음...구현이 그대로 노출되는 것은 좋지 않아보여요!
다른 방법으로 할일이 보이는 걸 테스트 할 수 없을까요?

2022-12-23 15:25 UTC, daadaadaah commented on src/input.test.jsx
> +  const inputComponentRender = () =>
함수명은 보통 `동사+명사`으로 씁니다. 어떻게 수정하면 좋을까요?

2022-12-23 15:25 UTC, daadaadaah commented on src/list.test.jsx
> +    });
List는 onClickDelete가 호출되는 정도만 알아요!
List 테스트를 아샬님은 어떻게 하셨는지 한번 피드백 강의를 통해 알아봅시다!

2022-12-26 11:58 UTC, merged