[Week3][Davidyang2149]Make Test Code(구현작업 진행 중)
CodeSoom/week3-assignment-1 pull request #24
Opened 2020-10-04 22:05 UTC by DavidYang2149

# 3강 테스트 - 3주 차 과제 1
## 기능 구현
- [ ] 모든 컴포넌트에 테스트를 작성해주세요. 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.

## 제한 조건
- [ ] if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- [ ] switch는 사용하실 수 없습니다.
- [ ] let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- [ ] 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- [ ] indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

## 요구사항
- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

## 작업내용 및 질의
- [ ] 구현 작업 진행 중.

2020-10-06 13:07 UTC, hannut91 commented
어려운거 있으면 질문 남겨주세요 ㅎㅎ

2020-10-07 02:59 UTC, DavidYang2149 commented
# 기능 구현
목표 : 각 항목의 컴포넌트의 역할을 확인하고 역할이 정상적으로 작동하는지 테스트를 진행.

## 항목의 역할 및 테스트
### App
- 변수 state를 통해 상태를 관리한다.
- To-do App의 기능 함수를 구현한다.
- Page로 각 함수와 상태값을 전달한다.
### Input
- input placeholder는 "할 일을 입력해 주세요"를 가진다.
- onchange시에 value 값이 변한다.
- 추가 버튼을 클릭하면 value 값이 초기화된다.
### Item
- 할 일은 title과 완료버튼을 가진다.
- 완료 버튼을 클릭하면 Item이 사라진다.
### List
- 할 일(task)의 길이에 따라(0 or !0) 다른 화면을 출력한다.
- (불분명)할일이 존재하는 경우 확인을 클릭하면 내용이 사라진다.
### Page
- 페이지(제목: To-do)를 구현한다.
- 전달받은 변수와 함수를 각 컴포넌트로 전달한다.

## 작업내용 및 질의
### 궁금한 것.
1. 왜 모든 컴포넌트를 테스트해야 하는가? Page의 경우 사실 UI를 구분하기 위한 역할로만 사용되고 있다. 굳이 여기까지 테스트를 해야 할까?
2. 각 컴포넌트의 테스트의 범위를 어디까지 설정해야 하는가? 테스트는 각 컴포넌트에 맞게 독립적으로 진행되어야 한다고 이해했다. 그렇다면 테스트의 깊이를 어디까지 진행해야할까? Input의 경우 placeholder나 onChange도 모두 테스트 해야 하는가?
3. 하위 컴포넌트의 기능을 같이 테스트해야하는가? List는 Item 컴포넌트를 랜더링 한다. 여기서 `완료`버튼을 누르면 해당할 일이 사라지는 역할을 확인해야 하는데, 이 기능은 List에서 확인해야 하는가? Item에서 확인해야 하는가? 혹은 둘 다 확인해야 하는가?

2020-10-07 12:23 UTC, DavidYang2149 commented
# Input
Input 테스트를 진행하기 위해 다음과 같은 계획을 세웠습니다.

## 기본 테스트
- [ ] value의 값이 비어있는 것을 확인합니다.
- [ ] <label>할 일</label>이 존재하는 것을 확인합니다.
- [ ] placeholder가 "할 일을 입력해 주세요"인 것을 확인합니다.

## onChange 테스트
- [ ] onChange의 입력값이 정상적으로 value에 변화했는지 확인합니다.
- [ ] onChange가 일어나지 않으면 값은 그대로 있습니다.

## onClick 테스트
- [ ] 추가 버튼을 클릭 시에 value 값이 초기화됩니다.

## 진행 상황
해당 내용을 구현하기 위해 테스트를 시도 중입니다.
처음 테스트를 해보아서 의도하는데로 테스트가 구현이 되지 않고 있습니다.

2020-10-07 15:16 UTC, hannut91 commented
* 왜 모든 컴포넌트를 테스트해야 하는가? Page의 경우 사실 UI를 구분하기 위한 역할로만 사용되고 있다. 굳이 여기까지 테스트를 해야 할까?
`Page`가 UI를 구분하기 위한 역할만 하고 있나요? 이 사실을 어떻게 알게 되셨나요? 그리고 사실이 참이라는 것을 어떻게 증명할 수 있나요?

* 각 컴포넌트의 테스트의 범위를 어디까지 설정해야 하는가? 테스트는 각 컴포넌트에 맞게 독립적으로 진행되어야 한다고 이해했다. 그렇다면 테스트의 깊이를 어디까지 진행해야할까? Input의 경우 placeholder나 onChange도 모두 테스트 해야 하는가?
내가 어디까지 테스트할 것인지는 중요한 고민거리인 것 같아요. 내가 테스트하고 싶은 만큼만 테스트를 작성하는 것인데, 내가 잘 동작하는지 확인하고 싶은 부분까지 테스트를 작성하면 좋을 것 같아요. 그리고 테스트를 일종의 사용설명서라고 보시면 될 것 같아요. 이 컴포넌트를 사용하는 사람에게 무엇을 알려주고 싶으신가요/

* 하위 컴포넌트의 기능을 같이 테스트해야하는가? List는 Item 컴포넌트를 랜더링 한다. 여기서 완료버튼을 누르면 해당할 일이 사라지는 역할을 확인해야 하는데, 이 기능은 List에서 확인해야 하는가? Item에서 확인해야 하는가? 혹은 둘 다 확인해야 하는가?
Item이 올바르게 동작한다고해서 List가 올바르게 동작한다는 것을 보장할 수 있을까요? 각 부품은 올바르게 동작한다는 것을 테스트로 작성했습니다. 그럼 그 부품을 조합했을 때 그 결과도 올바르게 동작한다는 것을 보장할 수 있을까요?

2020-10-09 15:15 UTC, hannut91 requested changes

2020-10-09 15:15 UTC, hannut91 commented on src/Input.test.jsx
> +    const handleChange = jest.fn();
테스트에 필요한 상수를 선언하는 곳이 중복되고 있는 것 같아요. 위에서 선언한 후 재사용하면 중복을 제거할 수 있습니다.

```js
describe('Input', () => {
  const value = '';
  const handleClick = jest.fn();
  const handleChange = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
  });
});
```

mock한 함수를 올바르게 초기화하지 않으면 의도치 않게 동작할 수 있기 때문에 주의해야 합니다.

See also
  - https://jestjs.io/docs/en/setup-teardown
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks

2020-10-09 15:15 UTC, hannut91 commented on src/Input.test.jsx
> +      getByText(buttonText);
`getBy*`했을 때 찾지 못하면 에러가 발생해서 테스트가 가능하지만, 단정문을 사용해서 의도적으로 더 드러내면 좋을 것 같아요

```js
expect(getByText(buttonText)).toBeInTheDocument();
```

2020-10-09 15:15 UTC, hannut91 commented on src/Input.test.jsx
> +    it('Basic', () => {
`it`안에는 실제로 어떤 일을 하는지 명시하는게 좋을 것 같아요.

Input 컴포넌트(describe) 는 value가 주어지면(context) value를 출력한다(it)

이런식으로 작성할 수 있습니다.

2020-10-09 15:15 UTC, hannut91 commented on src/Input.test.jsx
> +  };
테스트하는 로직이 함수에 담겨있는 것 같네요. 각각 테스트로 분리시켜주는게 좋을 것 같아요.

2020-10-10 14:35 UTC, hannut91 requested changes
테스트코드도 코드이기 때문에 관리를 해야합니다. 중복이 발생한 부분을 발견하면 어떻게 제거할 수 있을지 고민해보시면 좋을 것 같아요. 다른 컴포넌트도 동일하게 테스트를 작성하면서 연습해보시면 좋을 것 같습니다.

2020-10-10 14:35 UTC, hannut91 commented on src/Input.test.jsx
> +  context('Initialize', () => {
`context`에는 `with, without, when`이라는 키워드로만 작성할 것은 권장합니다.

See also
  - https://www.betterspecs.org/#contexts

2020-10-10 14:35 UTC, hannut91 commented on src/Input.test.jsx
> +      const handleChange = jest.fn();
`handle*`이 계속 중복되는 것 같아요. 다음과 같이 중복을 제거하면 좋을 것 같습니다

```js
describe('Input', () => {
  const handleClick = jest.fn();
  const handleChange = jest.fn();
  
  const renderInput = (value) => render((
    <Input value={value}
      onChange={handleChange}
      onClick={handleClick}
    />
  ))
  
  beforeEach(() => {
    jest.clearAllMocks();
  });
  
  it('shows value', () => {
    const { getByLabelText } = renderInput('책 읽기');
  
    expect(getByLabelText('할 일')).toHaveValue('책 읽기');
  });

  describe('click button', () => {
    it('calls onClick handler', () => {
      const { getByText } = renderInput('책 읽기');
      
      fireEvent.click(getByText('추가'));
      
      expect(handleClick).toBeCalled();
    });
  });
});

```

2020-10-10 14:35 UTC, hannut91 commented on src/Input.test.jsx
> +      expect(input).toHaveAttribute('value', '추가된 할 일');
`taskTitle`을 이용해서 표현해주는건 어떨까요?

```js
expect(input).toHaveValue(taskTitle);
```

2020-10-11 11:54 UTC, DavidYang2149 commented on src/Input.test.jsx
> +      const handleChange = jest.fn();
덕분에 어떻게 리팩토링을 해야할 지 감을 잡았습니다. 감사합니다!

2020-10-11 11:54 UTC, DavidYang2149 commented on src/Input.test.jsx
> +      expect(input).toHaveAttribute('value', '추가된 할 일');
사실 여기서 시간을 너무 많이 허비했습니다. ㅠㅠ
팁 감사합니다!

2020-10-11 11:55 UTC, DavidYang2149 commented on src/Input.test.jsx
> +  context('Initialize', () => {
describe, context, it(test)은 익숙해질 때까지 반복해야겠습니다.

2020-10-11 11:55 UTC, DavidYang2149 commented on src/Input.test.jsx
> +  };
네 전체 내용을 다시 수정하였습니다~

2020-10-11 11:55 UTC, DavidYang2149 commented on src/Input.test.jsx
> +    it('Basic', () => {
넵!

2020-10-11 11:56 UTC, DavidYang2149 commented on src/Input.test.jsx
> +      getByText(buttonText);
좋은 팁 감사합니다!

2020-10-11 13:44 UTC, hannut91 approved these changes
테스트를 잘 작성해주신 것 같아요 ㅎㅎ 다음번에 테스트를 작성할 때는 테스트이름을 좀 더 명시적으로 작성하는 연습을 하면 좋을 것 같습니다. 앞으로도 테스트를 작성할 일은 아직 많이 남아있으니 충분히 연습할 수 있을거에요. 

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

2020-10-11 13:44 UTC, hannut91 commented on src/App.test.jsx
> +  ];
아마 여러개를 입력할려고 배열도 만드신 것 같은데 사용하는 것을 보면 첫 번째 아이템만 사용하고 있네요 ㅎㅎ
더 단순하게 `const task = '첫 번째 할 일`이라고 해도 되겠네요

2020-10-11 13:44 UTC, hannut91 commented on src/Input.test.jsx
> +  });
render할 때 동작을 테스트하신 것 같아요. 테스트 이름을 좀 더 명시적으로 하면 더 좋은 테스트가 될 것 같습니다.

```js
describe('Input', () => {
  describe('Click addTask button', () => {
    it('calls onClick handler', () => {
    });
  });
});
```

이렇게 쓰면 테스트 대상이 무엇인지 명시할 수 있고, 그래서 어떤 일을 하는지 명시할 수 있어서 저는 주로 이런식으로 씁니다

2020-10-11 13:44 UTC, hannut91 commented on src/List.test.jsx
> +  ));
onClickDelete함수를 다루는 함수이니 `handleClickDelete`라는 이름의 함수가 더 좋을 것 같아요

2020-10-11 13:44 UTC, hannut91 commented on src/List.test.jsx
> +      expect(getByText(tasks[1].title)).toBeInTheDocument();
스터디에서 배운 Side effect를 위해서 사용하는 모든 목록을 순회한다는 의도를 드러내는 `forEach`를 사용해서 표현해주는건 어떨까요?

2020-10-12 12:32 UTC, DavidYang2149 commented on src/List.test.jsx
> +  ));
아! 코드를 짜다가 놓친 부분이었네요. 감사합니다.

2020-10-12 12:33 UTC, DavidYang2149 commented on src/List.test.jsx
> +      expect(getByText(tasks[1].title)).toBeInTheDocument();
넵! 의도가 더 명확하지는 것 같습니다.

2020-10-12 12:33 UTC, DavidYang2149 commented on src/Input.test.jsx
> +  });
describe를 중복해서 사용해도 되는군요!

2020-10-12 12:34 UTC, DavidYang2149 commented on src/App.test.jsx
> +  ];
배열 전체를 활용하지 못한다면 말씀하신 내용처럼 적용해보는 것도 좋겠네요.

2020-10-12 12:35 UTC, DavidYang2149 commented
3주 차 주간회고로 느낀 점을 대체하였습니다.
https://davidyang2149.dev/codesoom/%EC%BD%94%EB%93%9C%EC%88%A8-3%EC%A3%BC-%EC%B0%A8-%EC%A3%BC%EA%B0%84%ED%9A%8C%EA%B3%A0/

2021-01-17 12:59 UTC, merged