🎨 Write test code
CodeSoom/week3-assignment-1 pull request #27
Opened 2020-10-05 06:49 UTC by Knoa0405

Input.jsx 테스트 코드 하나 작성완료했습니다.
테스 코드 작성을 처음하다보니 어떻게 해야 하는 건지 잘 모르겠지만,
영상을 보고 배운대로 제 선에서 최대한 이해하고 적용해서 작성해봤습니다.
다른 것도 조금씩 작성해서 PR 보낼 예정입니다!

2020-10-05 16:55 UTC, Kihyun92 requested changes
Item.test.jsx에 refactoring이 필요하다고 생각되면 추가하셔도 됩니다~👍 이번 과제의 목표는 `Red-Green-Refactoring` 과정을 모두 적용해보는거에요. 그리고 `Refactoring` 단계까지 테스트 코드를 작성하는데에 제공되는 이외에 라이브러리는 굳이 필요 없을 것 같아요 :)

input.test.jsx에서 value를 고정하지 않고 테스트 케이스를 나누신건 매우 잘하신 것 같습니다~
그리고 말씀하신 render를 여러번 실행해주는 방법이 필요하다면 해봐도 좋을 것 같습니다~ 코드 중복은 앞선 과제들을 적용하면 충분히 해결 가능하니까요 😁

2020-10-05 16:55 UTC, Kihyun92 commented on src/Input.test.jsx
> +  expect(input.value).toBe('');
input에서 발생하는 다양한 케이스들을 잘 테스트해주신것 같습니다~ 다만 이렇게 되면 현재 이 테스트가 뭘 하는지 파악하기 힘든 것 같아요.

이런 경우엔 `describe, context, it` 을 사용해서 작성해보면 어떨까요?

2020-10-05 16:55 UTC, Kihyun92 commented on src/List.test.jsx
> +  });
task가 있는 경우와 없는 경우에 대해서 `test`로 구분해서 처리하셨네요! 좋습니다 👍 

다만 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이러한 경우 `describe - context - it`의 구조로 표현하는게 좋습니다. 

```jest
describe('List', () => {
  context('test의 length가 0인 경우', () => {
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      const { container } = render((
        <List tasks={tasks} onClickDelete={handleClick} />
      ));

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('test의 length가 1 이상인 경우', () => {
    ~~ 생략 ~~
```

이런 형태가 되겠네요. 차례대로 보면 `List는 test의 length가 0인 경우 "할 일이 없어요!"를 표시한다.`와 같이 읽혀서 조금 더 명확해 진 것 같지 않나요? :)

2020-10-05 16:55 UTC, Kihyun92 commented on src/List.test.jsx
> +    ));
중복되는 로직은 상위로 빼면 좋을 것 같습니다~ 

`Red - Green - Refactoring` ☺️

2020-10-06 09:46 UTC, Knoa0405 commented
App.jsx 에서 하위 컴포넌트에서 이미 전부 체크된 항목도 중복되게 하나요? 중복이 안되게 해주려고
저는 단순히 화면에 표시되어 있는지 없는지만 체크하고 버튼 클릭해서 작동하는지 최종 테스트를 작성해주려고 했습니다.
( 사실 App.jsx test 를 어떤 걸 해야할 지 모르겠습니다ㅠ)

그런데, 하다보니 안되는 부분이 생겨서 질문드립니다.

render() 에 App 컴포넌트를 인자로 넣어주면 객체를 반환해주는데 그 객체 안에 App 컴포넌트에서 렌더링하는 Page 컴포넌트 안에 List 나 Input 컴포넌트 전부 포함되어 있는거라고 생각했습니다. 그래서 아래처럼 해줬습니다.
(잘못된 생각이었다면 조언 부탁드립니다!)
이렇게 생각한 이유는 input 은 getByLabelText query 로 가져와져서 테스트가 가능했기 때문입니다.

![image](https://user-images.githubusercontent.com/60169820/95184082-d49d4c00-0801-11eb-8183-f892c789f3a6.png)

Q1. App.test.jsx 에서 하위 컴포넌트인 List 가 화면에 표시되있는지 체크를 해주는 테스트를 작성하려 했습니다.
queries 사용이 미숙해서 그런지 해당 요소를 가져와서 expect((list 요소)).toBeVisible() 해주려고 했는데, 아래 같이 에러가 뜹니다.
![image](https://user-images.githubusercontent.com/60169820/95184343-2fcf3e80-0802-11eb-9a3f-bb143187f4d3.png)

화면이 표시되있는지 없는지만 테스트하고 싶은데 render() 에서 반환된 객체에서 getByText를 하위 컴포넌트에 있는 "할 일이 없어요!" 를 가진 요소를 선택해서 테스트 해주려고 했는데 선택이 안됩니다.
어떤 부분을 몰라서 그런지 방향을 알려주시면 감사하겠습니다!
( DOM 요소를 가져오는 것과 비슷하다고 생각했습니다. 잘못된 생각이라면 조언 부탁드립니다! )

Q2. 앞에서 똑같이 작성해준 것을 리팩토링해줬는데 List.test.jsx 에서 12~15 부분이 uncoverage 라고 뜹니다.
ol 태그 부분인 것 같은데 해당 요소를 어떻게 테스트 해줄지 방향을 잡지 못하겠습니다.

2020-10-06 15:41 UTC, Kihyun92 requested changes
질문 해주신 두 문제는 동일한 원인 같네요~ 코멘트 확인부탁드립니다 :)

그리고 `describe-context-it`의 포멧으로 모든 테스트를 작성할 필요는 없습니다~ 

App 컴포넌트 테스트에 대해서 고민하신게 올바른 방향 같습니다~ 그래서 E2E 테스트가 있는 거구요 :)
지금은 본인이 안심될때까지 가능한 부분에서 테스트 코드를 작성해보시는게 좋을 것 같습니다.

2020-10-06 15:41 UTC, Kihyun92 commented on src/List.test.jsx
> +  });
테스트를 작성하실 때 `Given, When, Then` 형식에 맞춰 테스트를 작성하면 더 작성하기 쉬울 뿐더러 이해하기도 쉽습니다.

``` jest
describe('List', () => {
  context('test length is 0', () => {
    // Given
    const tasks = [];
    
    it('할 일이 없어요! 표시', () => {
      // When
      const { container } = render(<ListComponent />);
      
      // Then
      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });
```

또한 context안에는 `when, with, without`만 사용하길 권장합니다~
- https://www.betterspecs.org/#contexts

2020-10-07 14:53 UTC, Knoa0405 commented
## 두번째 리팩토링

위에서 말씀해주신 부분들 위주로 정리했습니다.
오늘 시간이 부족해서 많이 하진 못했네요!
App.test.jsx 에서 E2E 테스트 식으로 해보려고 하는데, 막히는 부분이 있어 
어떤 걸 공부해야 할지 방향을 알려주시면 감사하겠습니다~
예를 들면, 
1. "추가"버튼을 눌렀을 때, List 가 생성된다.
2. 생성된 List의 "완료" 버튼을 눌렀을 때 삭제된다.

이 두가지를 App.test.jsx 에서 테스트 해주려고 할 떄, 어떤 요소를 생성하고 삭제해주는
createElement 나 removeChild 같은 DOM API를 사용해주듯이 jest 에서 제공해주는 메서드 같은게 있나요?
찾아보는데 안보이네요ㅠ 없는게 아닌지 / 없다면 저런 경우는 어떤 걸 공부해야 할 수 있을지 방향을 알고 싶습니다.

2020-10-07 16:07 UTC, Kihyun92 requested changes
많이 작업하지 못해도 좋습니다~ 매일 조금씩 서로 피드백을 주는게 중요하죠 👍 

https://testing-library.com/docs/dom-testing-library/api-queries
여기를 참고해보시면 예를 들어주신 DOM 테스팅이 가능합니다~ 한번 봐보시고 궁금하시면 피드백 주세요~ :)

2020-10-07 16:07 UTC, Kihyun92 commented on src/Input.test.jsx
> +  ));
각 it 함수 내부에 우리가 테스트를 할 코드를 넣어주는게 좋을 것 같네요~

관련해서 의논된 슬랙 스래드 참고 해주세요~ 
- https://codesoom-group.slack.com/archives/G01AYKYRU1X/p1602062648028200?thread_ts=1602042153.016100&cid=G01AYKYRU1X

2020-10-07 16:07 UTC, Kihyun92 commented on src/List.test.jsx
> +    const handleClick = jest.fn();
handleClick 함수는 context 바깥쪽에 위치하는게 좋을 것 같습니다~

2020-10-08 16:15 UTC, Kihyun92 requested changes
잘 진행하고 계신것 같아요:) 다만, 전반적으로 중복되는 코드들이 있는데, 어떻게 개선할 수 있을지 고민해보시면 좋을 것 같아요~!

2020-10-08 16:15 UTC, Kihyun92 commented on src/Input.test.jsx
> +    ));
it 함수 안에 실제 테스트 할 코드가 있어야합니다.

2020-10-08 16:15 UTC, Kihyun92 commented on src/Input.test.jsx
> +    });
change 이벤트를 발생시킨 후 뭘 확인하려는지가 없는 것 같아요. 뭔가를 실행해서 어떤 변화가 생기는지를 확인하는게 좋습니다. :)

2020-10-08 16:15 UTC, Kihyun92 commented on src/Input.test.jsx
> +    });
각 테스트는 독립적으로 테스트 되어야합니다. 서로 의존성을 가지면 안됩니다.

2020-10-09 01:13 UTC, Knoa0405 commented on src/Input.test.jsx
> +    });
제가 독립적이라는 뜻을 잘못 이해했던 것 같습니다.
[모던 자바스크립트](https://ko.javascript.info/testing-mocha)
위에서 설명을 잘못 읽고 연관이 있더라도 테스트 하나엔 하나만 확인 하는 걸로 이해하고 따로 분리를 해줬었습니다.

2020-10-09 14:35 UTC, Knoa0405 commented
## 세번째 리팩토링

공식문서를 꼼꼼히 읽고 하다보니 어떻게 하면 되겠다 감이 조금씩 잡힙니다.
위에서 말씀 주신 부분 토대로 리팩토링 하였습니다.

App.test.jsx 테스트 부분에서 막힙니다. 최종 E2E 테스트로 모든 부분이 전체적으로 잘 동작하는지 테스트 해주려고 하는데 저번에도 한번 말씀드렸던 부분인 사용자가 리스트 추가 제거하는 테스트를 구현하는 부분에서 막혔습니다.

![image](https://user-images.githubusercontent.com/60169820/95594939-88af0900-0a86-11eb-9081-2cba14bb8a27.png)

진행 도중에 막혀서 일단 PR 보냈습니다.
주말에 더 공부해서 완벽하게 해보려고 노력해야겠습니다ㅎㅎ
관련해서 조금 더 방향을 알려주시면 더 공부해보도록 하겠습니다.

2020-10-09 15:46 UTC, Kihyun92 requested changes
테스트 코드를 잘 작성하고 계신 것 같아요!👍

다만 테스트들이 작업자 본인만 알 수 있도록 작성되어있는 것 같아요.
테스트 코드를 동료들이 읽게 될 일종의 사용 설명서로 생각하고 작성해보시면 좋습니다. 우리가 만들어둔 컴포넌트를 사용할 동료들에게 제공되는 일종의 예제가 되는거죠. 

예를 들어 작성하신 `describe-context-it`의 경우에도 `render는 tasks가 있을 때 tasks목록을 출력한다.`와 같이 해당 기능/컴포넌트에 대한 설명서를 읽듯이 읽히면 좋을 것 같습니다.

무엇을, 어떻게 보여주는게 좋을지 한번 고민해보시고 적용해보세요 :)

참고
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2020-10-09 15:46 UTC, Kihyun92 commented on src/App.test.jsx
> +  const renderUtil = () => render((
`renderUtil` 보다 `renderApp`과 같이 조금 더 명확하게 하는건 어떨까요?

2020-10-09 15:46 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('when rendering text', () => {
이 테스트의 역할을 드러내는데 `text`라는 단어가 필요한가요? `when after rendering`과 같이 하고, it에는 `renders "할일" button`으로 처리하는건 어떨까요?? 🤔 (저도 영어를 잘하진 못해서 고민되네요😅)

2020-10-10 05:19 UTC, Knoa0405 commented
## 네번째 리팩토링

1. App.test.jsx coverage 100% 달성
2. App.test.jsx 에서 하는 테스트는 개별 컴포넌트에서 해준 테스트들을 컴팩트하여 구성함. 동작 위주 구성
3. 한글 사용으로 테스트 코드를 명확하게 하기

전체 테스트 구성을 할 때 처음에는 어떻게 중복하지 않고 짤까를 고민하다가, 어쨌든 최종 App 컴포넌트에서는
전체 App이 보여지고 동작하는 모든 테스트가 개별 컴포넌트 들이 합쳐졌을 때도 동작되는 것을 확인해줘야겠다고
생각이 들었기 때문에 각각의 개별 컴포넌트에서 해준 테스트들의 중요 부분들만 전부 가져와서 context 별로 구성해서
나타내주었습니다. 
그래서 Page 컴포넌트 테스트는 구성 하나하나 동작 여부를 판단하지 않고,visual 한 부분만 확인하도록 해줬습니다.

2020-10-10 14:24 UTC, Kihyun92 commented on src/App.test.jsx
> +      });
이 부분은 아직 작업 중 이신가요? 원하는대로 동작하지 않을 것 같아요

2020-10-10 14:24 UTC, Kihyun92 commented on src/App.test.jsx
> +      tasks.filter(({ id }) => id !== task.id);
concat, filter 는 새로운 배열을 반환 합니다. 이렇게 처리할 경우 어떤 변화도 없을 것 같아요. 

- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

2020-10-10 14:24 UTC, Kihyun92 commented on src/App.test.jsx
> +  const renderUtil = () => render((
App.test뿐 아니라 다른 테스트들도 처리해주세요!

2020-10-10 14:27 UTC, Kihyun92 requested changes
App.test.jsx에 의미없는 코드가 있는 것 같아요.
원하는대로 올바르게 동작하고 있는지 한번 확인해보면 좋을 것 같네요.

2020-10-10 15:31 UTC, Knoa0405 commented on src/App.test.jsx
> +      });
이런 놓친 부분입니다. 바로 수정할게요!

2020-10-10 15:33 UTC, Knoa0405 commented on src/App.test.jsx
> +      tasks.filter(({ id }) => id !== task.id);
맞죠.. 제가 왜그랬을까요 잘못 생각했었네요ㅠ

2020-10-10 15:36 UTC, Knoa0405 commented on src/App.test.jsx
> +      tasks.filter(({ id }) => id !== task.id);
App.jsx 에 신경 쓰다보니 다른 test 에 신경 못쓴 것 같습니다.
근데 막상 손대려고 보니 뭘해야 할지 모르겠네요ㅎㅎ
내일 이번주 과제 최종 PR 보내겠습니다!

2020-10-10 16:21 UTC, Kihyun92 commented on src/App.test.jsx
> +      tasks.filter(({ id }) => id !== task.id);
괜찮습니다~ 차근차근 진행해보시면 금방 하실 수 있을 거에요!  질문 있으면 언제든 말씀해주세요 😁

2020-10-11 11:54 UTC, Kihyun92 approved these changes
이번 테스트 작성 과제를 해보시면서 느낀점이나 더 배우고 싶은 점이 있나요? 한번 고민해보시면 좋을 것 같네요~ 👍 

과제 풀이 꼭 보시고, 회고도 남겨주세요~

2020-10-11 11:54 UTC, Kihyun92 commented on src/App.test.jsx
> +      tasks.push(handleList(task));
push를 사용하게 되면 원본 배열의 불변성이 깨지게 됩니다. 다른 방법은 없을까요? 고민해보시면 좋을 것 같아요~

2020-10-11 11:54 UTC, Kihyun92 commented on src/App.test.jsx
> +      getByText('할일2');
`getBy*`는 해당 요소를 찾지 못하면 에러가 발생해서 충분히 테스트 가능하지만, assert 문으로 작성한다면 의도를 더 분명히 할 수 있을 것 같아요~

`expect(getByText('할일2')).not.toBeNull();`

2020-10-11 12:46 UTC, Knoa0405 commented on src/App.test.jsx
> +      getByText('할일2');
넵 앞으로 테스트 코드를 자주 작성하게 될텐데 
나머지 공부를 더 해야겠네요 회고 올리겠습니다.

2020-10-19 13:24 UTC, merged