Add tests to TodoList - 작업중
CodeSoom/week3-assignment-1 pull request #28
Opened 2020-10-05 11:58 UTC by gringrape

## 과제 목표
모든 컴포넌트에 테스트를 작성해주세요. 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.

## 제한 조건
- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

## 요구사항
- ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- 모든 인수 테스트를 통과시켜야 합니다.
- 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- 테스트 커버리지 100%를 달성해야 합니다.

2020-10-05 14:15 UTC, hannut91 requested changes
테스트가 작성된 파일만 Coverage를 확인합니다. 그래서 100%가 되는거에요. 그래도 모든 파일에 테스트를 작성해주세요

2020-10-05 14:15 UTC, hannut91 commented on src/Input.test.jsx
> +describe('Input Component test', () => {
이미 테스트가 파일 이름에도 들어가 있고, `describe-it`을 사용하니까 테스트라고 또 안적어줘도 될 것 같아요

2020-10-06 08:38 UTC, gringrape commented on src/Input.test.jsx
> +describe('Input Component test', () => {
> 테스트가 작성된 파일만 Coverage를 확인합니다. 그래서 100%가 되는거에요. 그래도 모든 파일에 테스트를 작성해주세요

그렇군요. 코드 단위로 커버리지가 나오는 것으로 착각했습니다.

2020-10-06 08:39 UTC, gringrape commented on src/Input.test.jsx
> +  ));
매번 호출해 주어야 하는 거군요.

2020-10-06 08:44 UTC, gringrape commented
## 작업목표
- Input Component 에 테스트 추가하기
## 작업계획
다음의 테스트 케이스를 코드로 작성
- [ ] input, label, button 을 표시하는지 확인
- [ ] value 파라메터가 주어진 경우, 그 값을 input 에 표시
- [ ] input 에 값이 입력된 경우, onChange 함수 실행
- [ ] button 을 클릭한 경우, onClick 함수 실행

2020-10-06 11:39 UTC, gringrape commented
## 작업 반성
### 테스트 케이스
- 예외적인 값이 파라메터로 들어오는 경우를 생각해주지 않은것 같습니다.
- 제대로 값이 들어갔는지, 이벤트 핸들러가 실행되는지를 검사하는 부분이 빈약하게 느껴집니다. 
확실히 그값이 들어간건지 단순히 포함된건 아닌지 좀 더 검사하거나 함수를 조사해봤어야 했다는 생각이 듭니다.
### BDD
- describe - context - it 을 given - when - then 처럼 생각하고 진행했습니다.
어떤 케이스 인지 말로 읽기는 쉬워진것 같습니다. 
하지만 then 부분(it)에 코드가 다 들어가 있어서 어색하게 느껴지는 것 같습니다. 
### 동일 변수 선언 반복
- element 들을 반복해서 선언해주는 것 같습니다. 재사용을 어떻게 할지 고민 중 입니다.

2020-10-06 13:16 UTC, hannut91 requested changes
다른 컴포넌트에도 더 테스트를 작성하며 연습하시면 좋을 것 같습니다. 잘해주고 계세요 ㅎㅎ

2020-10-06 13:16 UTC, hannut91 commented on src/Input.test.jsx
> +      getByText('추가');
`getBy*`는 해당 요소를 찾지 못하면 에러가 발생해서 충분히 테스트 가능하지만, assert문을 작성해서 의도를 분명히 해주면 더 좋을 것 같아요.

```js
expect(getByText('할 일')).toBeIntheDocument();
```

See also
  - https://github.com/testing-library/jest-dom#tobeinthedocument

2020-10-06 13:16 UTC, hannut91 commented on src/Input.test.jsx
> +  );
기본값을 주어서 올바르게 동작하도록 해주셨네요. 상황에 따라서 값을 다르게 주어서 다르게 테스트할 수 있어서 굉장히 유연한 것 같아요. 그렇지만 함수가 조금 복잡해진 것 같아요. 테스트 코드도 유지보수해야 할 코드 이기 때문에 이 또한 좋은 코드를 작성하도록 노력해야 합니다.

```js
  const mockValue = 'value';

  const handleChange = jest.fn();
  const handleClick = jest.fn();

  const renderInput = (value = mockValue) => render((
    <Input
      value={value}
      onChange={handleChange}
      onClick={handleClick}
    />
  ));

  beforeEach(() => {
    jest.clearAllMocks();
  });

  context('when user click button', () => {
    it('call click handler', () => {
      const { getByText } = renderInput();

      fireEvent.click(getByText('추가'));

      expect(handleClick).toBeCalled();
    });
  });
```

2020-10-07 11:00 UTC, gringrape commented on src/Input.test.jsx
> +  );
오.. mock 함수를 상위에다 놓고 매 테스트가 끝날때 mock 함수에 준 정보를 지우도록하면, 계속해서 사용할 수 있군요!
감사합니다 :)

2020-10-07 11:07 UTC, gringrape commented
## 작업 계획
### Input Component 테스트 코드 수정
- [ ] 이벤트 핸들러 테스트 수정 -> 이벤트 발생 전, 후 모두 테스트
- [ ] renderInput 수정 -> 가독성 고려
- [ ] 컴포넌트가 element 들을 가지는지에 대한 테스트 수정 -> assert 를 명확하게 실행
###  List Component 테스트 추가
- [ ] tasks 가 배열 타입이 아닐때, 예외가 발생한다.
- [ ] tasks 가 비어있는 배열일때, 기본 메세지가 보여진다.
- [ ] tasks 가 빈 배열이 아닐때, 배열의 각원소가 Item 으로 보여진다.
- [ ] handleClick 이 함수가 아닐때, 예외가 발생한다.

2020-10-07 12:02 UTC, gringrape commented on src/Input.test.jsx
> +      expect(handleChange).toBeCalled();
toBeCalledWith 를 이용하여 정확히 '밥 먹기' 라는 것이 들어왔는지 테스트 해주려고 했는데, 잘안되어 질문 드립니다.
이밖에도 현업에서 change, click 핸들러를 테스트하실때, 어떻게 하시는지 궁금합니다.

2020-10-07 13:23 UTC, gringrape commented
## 고민한 것
### 구현이 아닌 작동을 테스트
> 어떻게 구현하는지가 아닌  작동을 테스트 하라. 
> => 올바르게 작동하는데도 실패하는 테스트를 만들면, 구현에 따라 자주 수정해주어야 한다.

위와 같은 조언을 얻고서 적용해보았습니다. 
List 에서 하위 컴포넌트를 제대로 렌더링하는지 테스트하려 했다가, 
내용을 제대로 표시하는지 검사하는것으로 바꿨습니다.
조언 내용에 공감은 했지만, 맞게 고쳤는지는 확신이 없습니다.

### 예외처리
파라메터의 타입이 안맞는 경우에 대한 오류 처리를 추가했습니다.
오류 메세지를 표시할때, 컴포넌트 단위에서 하면 화면에 표시되는 메세지가 중구난방이 되어서
한 곳에서 모아서 해야할것 같습니다. 경험이 없어서 어떤식으로 해주어야 하는지 자료를 찾아보아야 할 것 같습니다.

2020-10-07 14:44 UTC, hannut91 requested changes

2020-10-07 14:44 UTC, hannut91 commented on src/Input.test.jsx
> +  });
테스트가 끝난 후 초기화를 하기 위해 `afterEach`를 이용해서 초기화를 시켜주셨네요. 이럴 경우 하나의 테스트가 만약 실패할 경우 제대로 초기화가 되지 않아서 의도치 않게 동작할 수 있으므로 `beforeEach`항상 실행하기전에 깨끗한 상태에서 테스트가 동작하도록 하는게 좋을 것 같아요. 

어떤 책에서는 `afterEach`와 `beforeEach`둘다 하라고 조언하는 책도 있긴 합니다

2020-10-07 14:44 UTC, hannut91 commented on src/Input.test.jsx
> +    it('call change handler', () => {
주어가 3인칭 단수 이기 때문에 `calls`로 써주는게 더 정확합니다 ㅎㅎ

2020-10-07 14:44 UTC, hannut91 commented on src/List.test.jsx
> +    it('show information of tasks', () => {
여기 위에 빈 줄 하나를 추가해서 구분해주면 좋을 것 같아요

2020-10-07 14:44 UTC, hannut91 commented on src/List.test.jsx
> +  });
정의되어 있지 않은 스펙을 테스트로 정의해주셨군요! 좋네요!

2020-10-07 14:52 UTC, hannut91 commented on src/Input.test.jsx
> +      expect(handleChange).toBeCalled();
지금 구현된 코드에서는 onChange 이벤트를 부모 컴포넌트로 전달하고 있기 때문에 테스트할 게 없는 것 같아요. 실무에서는 onChange이벤트를 바로 처리하지 않고 다르게 처리한다면 그 부분을 테스트합니다.

2020-10-08 10:21 UTC, gringrape commented on src/Input.test.jsx
> +  });
그렇군요. 테스트가 중간에 실패하면 초기화가 안돼서 다음것도 영향을 주는군요!
감사합니다 :)

2020-10-08 11:12 UTC, gringrape commented
## 작업계획
### App Component 테스트 추가
상태관리가 주요관심사인 컴포넌트이므로, 상태변화 이벤트가 일어날때 어플리케이션 동작변화를 테스트.
- **when** **then**
- [ ] 사용자가 새로운 할 일을 입력하면, 새로운 할 일이 입력창에 나타난다.
- [ ] 사용자가 추가버튼을 누르면, 새로운 할 일이 화면에 나타난다.
- [ ] 사용자가 완료버튼을 누르면, 그 할일이 화면에서 사라진다.
### 기존 테스트 수정
- [ ] afterEach -> BeforeEach, 테스트 이름 수정.
- [ ] 상수를 모두 위쪽으로 옮기기
### Page 테스트 추가
- [ ] heading 을 보여준다.

2020-10-08 15:06 UTC, hannut91 requested changes

2020-10-08 15:06 UTC, hannut91 commented on src/Input.test.jsx
> +  context('without user action', () => {
사용자 액션 없이 라는게 테스트를 이해하는데 도움이 되진 않는 것 같아요. 꼭 context를 쓸 필요 없이 it만 써도 괜찮을 것 같아요

2020-10-08 15:06 UTC, hannut91 commented on src/List.test.jsx
> +  });
여기는 beforeEach로 안바꼇군요

2020-10-08 15:06 UTC, hannut91 commented on src/List.test.jsx
> +  });
비어있는 tasks라고 의도적으로 써주셨으니, 코드로도 보여주는게 좋을 것 같아요

```js
context('with empty tasks', () => {
  const tasks = [];

  it('show default text', () => {
    const { getByText } = renderList(tasks);

    expect(getByText(defaultText)).toBeInTheDocument();
  });
});
```

그러면 위의 테스트와 뭔가 대칭되는 것 같죠

2020-10-09 00:18 UTC, gringrape commented on src/List.test.jsx
> +  });
엇.. 그렇군요. 정신놓고 했는지 살펴보니 다른 부분도 일관성이 없네요.

2020-10-09 15:31 UTC, hannut91 requested changes

2020-10-09 15:31 UTC, hannut91 commented on src/List.test.jsx
> +      expect(getAllByText(itemButtonText).length).toBe(3);
왜 3인지 여기만 봐서는 알기 어려운 것 같아요. `3`을 `tasks`를 이용해서 표현할 수 있을까요?

2020-10-09 15:31 UTC, hannut91 commented on src/List.test.jsx
> +      expect(getByText(errorText)).toBeInTheDocument();
```js
const { container } = renderList(tasks);

expect(container).toHaveTextContent(errorText);
```

텍스트가 있는지 확인할때는 이렇게 할 수도 있습니다.

2020-10-10 10:15 UTC, gringrape commented on src/List.test.jsx
> +      expect(getByText(errorText)).toBeInTheDocument();
넵 ㅎ 강의에서 봤었는데 container 라는게 뭘 컨테이너라고 하는건지 잘 와닿지가 않아서 
피했던것 같습니다. 참고할게요 ㅎ

2020-10-10 10:18 UTC, gringrape commented on src/List.test.jsx
> +      expect(getAllByText(itemButtonText).length).toBe(3);
그러네요 정말. 여기서보면 갑자기 3 이군요. 하드코딩할때는 주의해야하는군요. 감사합니다.

2020-10-10 14:42 UTC, hannut91 approved these changes
꼼꼼하게 테스트를 잘 작성해주신 것 같습니다 ㅎㅎ 앞으로 과제를 진행하면서 테스트는 필수로 작성해야하기 때문에 앞으로도 연습할 기회가 많을 것 같습니다.

처음 작성했던 테스트 코드와 현재와 비교해서 무엇이 더 좋아졌는지 생각해보시면 좋을 것 같습니다.

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

2020-10-11 13:33 UTC, hannut91 commented
회고를 작성해주시면 머지하겠습니다!

2020-10-11 23:51 UTC, gringrape commented
> 회고를 작성해주시면 머지하겠습니다!

넵 늦게 작성했습니다 ㅜ

2020-10-12 00:20 UTC, merged

2021-01-07 12:56 UTC, hannut91 commented on src/Input.test.jsx
> +      expect(handleChange).toBeCalled();
그렇군요. 각 컴포넌트에서 무슨 일을 하는지 정확하게 파악하고 각 역할에 따라 테스트를 작성해야되는 군요! 

감사합니다!