테스트 시나리오 작성
CodeSoom/week3-assignment-1 pull request #29
Opened 2020-10-05 12:40 UTC by juunini

테스트 작성 전 시나리오부터 작성하였습니다.

2020-10-05 12:43 UTC, juunini commented
# 작업 내용
테스트 작성 전 시나리오부터 작성하였습니다.

# 느낀 점
아직 테스트 코드를 작성하진 않았고, 시나리오만 작성한 상태이지만
작은 컴포넌트 일 수록 간단하게 테스트 시나리오가 나오고,
작은 컴포넌트를 포함하는 큰 컴포넌트가 될 수록
앞에서 했던 케이스들을 포함하는 복잡한 테스트 시나리오가 되어간다고 느꼈습니다.

`App.test.jsx` 의 경우에는 거의 e2e 테스트와 비슷하게 시나리오를 작성하는 기분이 들었습니다.

2020-10-05 17:02 UTC, Kihyun92 reviewed
테스트 코드를 작성하기 전에 시나리오부터 작성해보는건 매우 좋은 것 같습니다👍

다만 `describe-it`으로만 작성하려다보니 애매모호한 케이스들이 생기는 것 같아요~ 이 경우에는 `describe-context-it`의 구조로 표현해 볼 수 있을 것 같아요.

List.test.jsx를 예로 들면,
```jest
describe('List', () => {
  context('empty tasks', () => {
    it('"할 일이 없어요!" 노출', () => {
      ~~ 생략 ~~
    });
  });

  context('exist tasks', () => {
    ~~ 생략 ~~
```
이런 형태로 표현한다면, `List가 empty tasks이면, "할 일이 없어요!"노출`과 같이 조금 더 명확하게 읽힐 것 같네요 😁

2020-10-06 11:45 UTC, juunini commented
# 오늘 작업 내용
- Input 컴포넌트 테스트 작성
- List 컴포넌트 테스트 작성
- Page 컴포넌트 테스트 작성
- App 컴포넌트 테스트 작성

# 새로 알게된 것
- describe - context - it
    - describe() : 설명할 테스트 대상을 명시한다.
    - context() : 테스트 대상이 놓인 상황을 설명한다.
    - it() : 테스트 대상의 행동을 설명한다.

        test() 와 같은 의미로 사용된다는 말이 있다.
        맞는지 모르겠다.

- mock은 import하는 모듈에 사용한다.

# 느낀 점
일단 테스트 코드를 전부 작성했습니다.
App 컴포넌트의 테스트 작성은 역시나 CodeceptJS를 통해 하는 e2e 테스트와 비슷한 느낌이 들었습니다.

App 컴포넌트에서 정의한 함수들은 외부에서 가져온게 아니라
App 컴포넌트 내에서 정의된 함수들이라 mocking이 되지 않는다는 사실을 알게되었습니다.

2020-10-06 16:36 UTC, Kihyun92 requested changes
확실히 여러 시나리오를 먼저 고민해보고 구현하셔서인지 매우 다양한 테스트 케이스를 구현하셨네요! 좋습니다. :)

context의 경우, `with, without, when`만 사용하도록 권장되고 있어요. 적용해보시면 조금 더 명확하게 테스트들이 표현될 것 같아요~
- https://www.betterspecs.org/#contexts

그리고 App 테스트의 경우, 확실히 최상단 테스트라서 고민하신대로 E2E 테스트와 유사해졌네요~ 이번 과제에서는 본인이 안심될때까지 테스트를 추가해보시는것도 좋은 것 같아요 👍 

테스트 또한 유지보수를 해야하는 코드이고, 중복되는 로직이 있다면 어떻게 제거할 수 있을지 고민해보시면 좋을 것 같습니다~

2020-10-06 16:36 UTC, Kihyun92 commented on src/Input.test.jsx
> +  };
setup을 통해 각기 다른 테스트 케이스마다 props들을 세팅해주어 다양한 테스트를 작성하신것 같네요! 좋습니다👍
다만 조금 복잡한 것 같아요~ handleChange와 handleClick의 경우, 최초 한번만 선언해도 될 것 같은데 어떤가요?

```suggestion
  const handleChange = jest.fn();
  const handleClick = jest.fn();

  const renderInput = render((
    <Input
      value={value}
      onClick={handleClick}
      onChange={handleChange}
    />
  ));
```

그리고 setup대신에 각 it함수 내에서 renderInput을 호출하는 방식으로 처리하면 어떨까요?

2020-10-07 00:28 UTC, juunini commented on src/Input.test.jsx
> +  };
음... 조언해주신 부분이 어떤 식으로 적용해야 되는건지 잘 모르겠습니다 ㅠㅠ

```javascript
describe('Input', () => {
  const handleChange = jest.fn();
  const handleClick = jest.fn();
  const placeholderText = '할 일을 입력해 주세요';
  const buttonText = '추가';
  const value = '';
  const renderInput = render((
    <Input
      value={value}
      onClick={handleClick}
      onChange={handleChange}
    />
  ));

  context('with value', () => {
    it('check elements', () => {
      renderInput.getByPlaceholderText(placeholderText);
      renderInput.getByText(buttonText);
    });

    it('click button', () => {
      const button = renderInput.getByText(buttonText);

      expect(handleClick).not.toBeCalled();

      fireEvent.click(button);

      expect(handleClick).toBeCalledTimes(1);
    });
  });
});
```

이런 방식을 말씀하신건지

```javascript
describe('Input', () => {
  const handleChange = jest.fn();
  const handleClick = jest.fn();
  const placeholderText = '할 일을 입력해 주세요';
  const buttonText = '추가';

  context('with value', () => {
    const value = '';
    const renderInput = render((
      <Input
        value={value}
        onClick={handleClick}
        onChange={handleChange}
      />
    ));

    it('check elements', () => {
      renderInput.getByPlaceholderText(placeholderText);
      renderInput.getByText(buttonText);
    });

    it('click button', () => {
      const button = renderInput.getByText(buttonText);

      expect(handleClick).not.toBeCalled();

      fireEvent.click(button);

      expect(handleClick).toBeCalledTimes(1);
    });
  });
});
```

아니면 이런 방식을 말씀하신건지
아니면 아래 방법인지

```javascript
import React from 'react';

import { render, fireEvent } from '@testing-library/react';

import Input from './Input';

describe('Input', () => {
  const handleChange = jest.fn();
  const handleClick = jest.fn();
  const placeholderText = '할 일을 입력해 주세요';
  const buttonText = '추가';

  context('with value', () => {
    const value = '';

    it('check elements', () => {
      const renderInput = render((
        <Input
          value={value}
          onClick={handleClick}
          onChange={handleChange}
        />
      ));

      renderInput.getByPlaceholderText(placeholderText);
      renderInput.getByText(buttonText);
    });

    it('click button', () => {
      const renderInput = render((
        <Input
          value={value}
          onClick={handleClick}
          onChange={handleChange}
        />
      ));
      const button = renderInput.getByText(buttonText);

      expect(handleClick).not.toBeCalled();

      fireEvent.click(button);

      expect(handleClick).toBeCalledTimes(1);
    });
  });
});

```

이래저래 고민해보면서 작성해보았는데, 첫번째, 두번째 방법은 에러가 나서 실패하고
세번째 방법은 단순화 시키려면 setup() 같은 방식을 사용할 수 밖에 없게 되서...
결론적으로는 조언해주신 방향을 전혀 이해하지 못했습니다 ㅠㅠ

2020-10-07 15:05 UTC, Kihyun92 commented on src/Input.test.jsx
> +  };
제가 설명이 부족했던 것 같네요~ setup()을 사용하는 방식과 크게 다르지 않습니다.

```
describe('Input', () => {
  const handleChange = jest.fn();
  const handleClick = jest.fn();
  const placeholderText = '할 일을 입력해 주세요';
  const buttonText = '추가';

  context('with value', () => {
    const value = '';

    it('check elements', () => {
      const renderInput = render((
        <Input
          value={value}
          onClick={handleClick}
          onChange={handleChange}
        />
      ));

      renderInput.getByPlaceholderText(placeholderText);
      renderInput.getByText(buttonText);
    });

    it('click button', () => {
      const renderInput = 
      const button = renderInput.getByText(buttonText);

      expect(handleClick).not.toBeCalled();

      fireEvent.click(button);

      expect(handleClick).toBeCalledTimes(1);
    });
  });
});
```

2020-10-08 13:36 UTC, juunini commented on src/Input.test.jsx
> +  };
context가 한개일 땐 괜찮은데
2가지 이상으로 다른 상태에서 동일한 테스트를 진행하려니 문제가 생깁니다 ㅠㅠ
onClickTest와 onChangeTest를 풀어서 써도 동일하게 문제가 발생합니다

일단 문제가 생기는 상태의 코드를 푸시해뒀습니다 ㅠㅠ

2020-10-08 16:26 UTC, Kihyun92 commented
>context가 한개일 땐 괜찮은데, 2가지 이상으로 다른 상태에서 동일한 테스트를 진행하려니 문제가 생깁니다

각 테스트가 독립적이지 않기 때문일 것 같습니다. `beforeEach`를 이용하여 각 테스트 전에 mock해주는 함수들을 초기화해주도록 처리하면 의도치 않게 동작하는걸 막을 수 있습니다~ 

```
beforeEach(() => {
  jest.clearAllMocks();
});
```

2020-10-09 02:27 UTC, juunini commented
```javascript
beforeEach(() => {
  jest.clearAllMocks();
});
```

이 함수가 이런 경우에 사용하는 것이었군요. 감사합니다.
말씀해 주신 대로 한번만 선언하고도 재사용이 가능해졌습니다.

2020-10-09 15:21 UTC, Kihyun92 requested changes
전반적으로 테스트를 잘 작성해주셨네요~
다만 테스트들이 작업자 본인만 알 수 있는 테스트로 이루어져있는 것 같아요. 테스트 코드를 동료들이 읽게 될 일종의 `사용 설명서`로 생각하고 작성해보시면 좋습니다. 우리가 만들어둔 컴포넌트를 사용할 동료들에게 제공되는 일종의 예제가 되는거죠.
무엇을, 어떻게 보여주는게 좋을지 한번 고민해보시고 적용해보세요 :)

2020-10-09 15:21 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('function test', () => {
이런 경우에는 context가 필요 없을 것 같아요~ `context`내에 `with, without, when`을 권장하는 이유는 서로 대비되는 테스트를 나타내줄 때 유용하기 때문인데, 지금의 상황에서는 it으로도 충분히 나타낼 수 있을 것 같아요 :)

- https://www.betterspecs.org/
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2020-10-09 15:21 UTC, Kihyun92 commented on src/Input.test.jsx
> +  };
```suggestion
  const renderInput = (value) => render((
    <Input
      value={value}
      onClick={handleClick}
      onChange={handleChange}
    />
  ));
```
이렇게 하면 더 심플할 것 같네요 :)

2020-10-09 15:21 UTC, Kihyun92 commented on src/List.test.jsx
> +    it('check element', () => {
`descibe-context-it`에 있는 문장들이 개인적으로 잘 연결되지 않는 것 같아요.

`it('renders "할 일이 없어요!"', () => {`
이렇게 하면, `List without tasks renders "할 일이 없어요!"` 와 같이 다른사람에게 설명해주는 느낌이 될 것 같습니다~

2020-10-10 11:24 UTC, juunini commented
# 작업 내용
- 기능 테스트는 하위 컴포넌트에서 빡시게 확인
- 상위 컴포넌트에서는 하위 컴포넌트가 잘 불러와졌는지 확인
- 최상위 컴포넌트에서는 E2E 테스트와 동일한 테스트

# 생각중인 부분
사용 설명서 같이 생각해본다는 부분에서 세부적인 기능은 해당 부분의 하위 컴포넌트에서 확실히 테스트 하고
상위 컴포넌트들에서 기능 테스트는 하위 테스트에서 되었으니, 잘 불러와졌는지 확인하고, 연계된 동작들을 테스트하는게 맞지 않나 하는 생각을 해보았습니다.

사실 아직도 뭐가 맞는지 잘 모르겠군요 ㅠㅠ

2020-10-10 15:30 UTC, Kihyun92 requested changes
많은 고민을 하고 계신것 같아요 👍  각 테스트들이 무슨 역할을 하는지 굉장히 이해하기 쉬워진 것 같아요😊

제 생각에는 각 컴포넌트 마다 가지고있는 관심사가 다르기 때문에, 각 컴포넌트 테스트들은 본인의 스코프 내에서 어떤 기능을 가지고 있는지, 그리고 각 기능은 어떤 동작을 하는지에 대해 알 수 있으면 된다고 생각합니다~

지금 작성해주신 테스트도 충분히 기능과 역할이 전달이 되는 것 같아요 ㅎㅎ 테스트 코드도 유지보수해야하는 코드라는 점 잊지 말고 계속 개선해나가면 좋을 것 같습니다~ 👍

2020-10-11 05:45 UTC, juunini commented on src/App.test.jsx
> +    getByText('할 일이 없어요!');
그냥 저렇게 해두니 맞게 작동하긴 하지만
"getByText 다음은?"
하는 느낌으로 의도가 모호하기도 하고 휑하기도 하네요 ㅎㅎ;

2020-10-11 12:01 UTC, Kihyun92 approved these changes
제가 드린 피드백보다 더 잘 해주신 것 같아요! 이번 과제를 해보시면서 고민을 많이 해보셨을 것 같아요 ㅎㅎ 테스트를 작성하면서 어떻게 코드들이 바뀌었는지 봐보시면 좋을 것 같아요 👍 

과제풀이 꼭 보시고, 회고도 남겨주세요 😁

2020-10-11 14:11 UTC, merged