첫 테스트 코드 추가
CodeSoom/week3-assignment-1 pull request #31
Opened 2020-10-05 12:57 UTC by dongakim

### 간략설명

- **Input**
구성요소가 있는지,
onChange, onClick 호출시 handler 메서드가 호출되는지를 테스트 했습니다.

- **List**
tasks가 있을 때와 없을 때를 나누어서 테스트를 작성했습니다.

- **Page**
하위 컴포넌트들이 나오는지를 테스트 했습니다.

- **App**
task를 추가하고 삭제하는 기능을 테스트 했습니다.

### 느낀점

테스트가 처음이라 많이 막막했습니다.

### 궁금한 점

- 자식 컴포넌트에서 테스트한 부분을 부모 컴포넌트에서도 테스트 해야할 지 궁금합니다.
- 테스트 작성은 자식 컴포넌트에서 부모 컴포넌트로(bottom -> up 방식)으로 해야할지 그 반대로 해야할 지 궁금합니다.

2020-10-05 14:28 UTC, hannut91 requested changes
* 자식 컴포넌트에서 테스트한 부분을 부모 컴포넌트에서도 테스트 해야할 지 궁금합니다.
자식 컴포넌트에서 테스트한 부분도 부모 컴포넌트에서도 테스트 해야합니다. 왜냐하면 자식 컴포넌트에서 잘 동작한다고 해서 그 컴포넌트를 조합했을 때 올바르게 동작하는지도 테스트해야 하기 때문입니다.
* 테스트 작성은 자식 컴포넌트에서 부모 컴포넌트로(bottom -> up 방식)으로 해야할지 그 반대로 해야할 지 궁금합니다.
둘 다 하실줄 알아야 합니다. 상황에 따라서 왔다갔다 할 수 있으셔야 합니다. botttom부터하면 더 간단한 것 부터 시작하기 때문에 테스트를 작성하기 쉽다는 장점이 있는데, 막상 테스트 코드를 작성하고 코드를 작성완료했을 때 실제 사용하는 top에서는 사용하기 불편하거나 잘못 설계 했을 수도 있습니다. 그럴 경우에는 Top -> Bottom이 더 좋은 경우가 있습니다.

2020-10-05 14:28 UTC, hannut91 commented on src/Page.test.jsx
> +      taskTitle
이 줄은 없어도 될 것 같아요

2020-10-05 14:28 UTC, hannut91 commented on src/List.test.jsx
> +  test('tasks가 없을 때', () => {
tasks가 있을 때 와 없을 때를 잘 나눠서 테스트해주신 것 같아요. 현재 이 테스트가 실제로 무엇을 하는지 더 자세히 설명해주면 더 좋을 것 같아요. 
테스트를 작성하실 때 `Given, When, Then`에 맞춰서 코드를 작성해보세요. 이러한 형식에 맞춰서 테스트를 작성하는 연습을 하면 좋은 테스트를 작성하는데 많은 도움이 됩니다. 

```js
describe('render', () => {
  context('tasks가 없을 떄', () => {
    // Given
    const tasks = [];

    it('빈 메세지를 표시합니다.', () => {
      // When
      const { container } = render(<SomeComponent />);

      // Then
      expect(container).toHaveTextContent('투두가 없습니다.');
    });
  });
  
  context('tasks가 있을 때', () => {
    // Given
    const tasks = [{ id: 1, task: '밥먹기' }];

    it('tasks 목록을 출력한다', () => {
      ...
    });
  });
});
```

그래서 차례대로 읽어보면 `render는 tasks가 없을 때 빈 메시지를 출력한다.`, `render는 tasks가 있을 때 tasks목록을 출력한다.`로 읽을 수 있습니다. 그래서 자연스러운 문장이 됩니다. 영어로 작성해도 마찬가지에요. 그래서 `context`안에는 `with, without, when`만 사용하도록 권장합니다.

See also
  - https://ko.javascript.info/testing-mocha
  - https://www.betterspecs.org/#contexts

2020-10-06 11:13 UTC, dongakim commented
말씀해주신 내용을 바탕으로
각 컴포넌트에서 일어나는 일들을 쪼개고(render, click event, chagne event 등)
맥락에 따라 구분되는 테스트를 작성해보았습니다.

2020-10-06 14:06 UTC, hannut91 requested changes

2020-10-06 14:06 UTC, hannut91 commented on src/App.test.jsx
> +    it('추가할 수 있다.', () => {
`<App />`에서 무엇을 할 수 있는지 테스트를 잘 작성해주신 것 같아요. 
무엇을 할 수 있는지도 중요하지만 무엇을 했을 때 어떤 변화가 일어나는지 더 집중해보면 좋을 것 같아요. 추가하면 어떤 변화가 일어나나요?

2020-10-06 14:06 UTC, hannut91 commented on src/Input.test.jsx
> +        );
`render`가 계속 반복되고 있는 것 같아요. 이런 경우 `render`를 더 추상화해서 중복을 제거해주는 것이 좋습니다.

```js
const handleChange = jest.fn();

const renderInput = () => render((
  <Input onChange={handleChange} />
));

beforeEach(() => {
  jest.clearAllMocks();
});

context('input에 typing 했을 때', () => {
  it('onChange props가 호출된다.', () => {
    renderInput();
      
    userEvent.type(screen.getByRole('textbox'), 'fix the bug');

    expect(handleChange).toHaveBeenCalled();
  });
});
```

2020-10-06 14:06 UTC, hannut91 commented on src/Input.test.jsx
> +        expect(handleChange).toHaveBeenCalledTimes(11);
이렇게 테스트하면 다른 테스트에 의존하게 됩니다.
`beforeEach`같은걸 사용해서 항상 테스트가 독립적으로 실행되도록 해야합니다.

2020-10-06 14:06 UTC, hannut91 commented on src/Page.test.jsx
> +        }];
테스트를 준비하는 과정을 `it`함수 안에 적는 대신 `context`안에 적으면, 테스트를 준비하는 것과 실제로 테스트가 실행되는 것을 분리하여 보여줄 수 있습니다.

```js
context('tasks가 있을 때', () => {
  const title = '복습하기';
  const tasks = [{ id: 1, title, }];

  it('tasks 목록을 출력한다', () => {
    ...
  });
});
```

2020-10-07 12:59 UTC, dongakim commented
<App /> 테스트를 말씀해주신대로
무엇을 했을 때 어떤 변화가 생기는지 즉, 기능의 아웃풋은 무엇인지라는 관점으로
테스트 코드를 재작성해보았습니다.

2020-10-07 15:03 UTC, hannut91 requested changes

2020-10-07 15:03 UTC, hannut91 commented on src/Page.test.jsx
> +    const emptyTasks = [];
emptyTasks로 변수의 이름을 드러낼 수 있지만 테스트를 이해할 때는 좀 한 번 더 생각하게 되는 것 같아요

```js
describe('Page', () => {
  let tasks = [];

  context('with empty tasks', () => {
    tasks = [];

    it('do something', () => {
      render(tasks);
    })
  });

  context('wtih tasks', () => {
    tasks = [{ id: 1, task: '책 읽기' }];

    it('do something different', () => {
      render(tasks);
    });
  });
});
```

이런식으로 하면 `context`간에 어떤 조건(Given)이 다른지 좀더 의도를 드러낼 수 있을거에요. let을 사용하지만 나중에 다른 라이브러리를 쓰면 안쓰고도 표현이 가능한데 나중에 배우게 될거에요

2020-10-08 00:48 UTC, dongakim commented on src/Page.test.jsx
> +    const emptyTasks = [];
이런식으로 시도했으나
tasks가 있을 때 context에서 할당한 배열값이
tasks가 없을때 context에도 할당 됩니다..

2020-10-08 14:42 UTC, hannut91 approved these changes
Given When Then 템플릿에 맞춰서 테스트를 잘 작성해주신 것 같아요 ㅎㅎ 각 테스트도 하나의 테스트만 하고 있고 좋습니다. 익숙해지시면 주석작성없이 자연스럽게 좋은 테스트를 작성하실 수 있을거에요. ㅎㅎ 처음 코드와 지금 코드와 어떻게 달라졌는지 다시 한 번 생각해보시면 좋을 것 같아요.

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

2020-10-08 14:42 UTC, hannut91 commented on src/Page.test.jsx
> +    const emptyTasks = [];
음.. 이런식이 정확히 어떻게 된지 몰라서 답변이 어려우나, 추후에 다른 라이브러리를 사용해서 더 의도를 드러낼 수 있는 방법을 학습할테니 넘어가도 좋을 것 같아요 ㅎㅎ

2020-10-11 13:32 UTC, merged