Week3_1 Todo create test code [진행중..]
CodeSoom/week3-assignment-1 pull request #32
Opened 2020-10-05 14:58 UTC by saseungmin

## ✌ To-do 테스트 작성하기

### 🚀 과제 목표
- 모든 컴포넌트에 테스트 작성하기
- 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.

### 📚 현재 진행 사항
- [x] Input.test.jsx 작성
    - 할일 입력, 추가 버튼 클릭
- [ ] List.test.jsx 작성
- [ ] Page.test.jsx 작성
- [ ] App.test.jsx 작성

2020-10-06 16:52 UTC, Kihyun92 requested changes
테스트 케이스를 잘 작성하고 계신 것 같아요~ 테스트 또한 유지보수해야하는 코드라는 점 기억하면서 구현하시면 좋을 것 같습니다~

2020-10-06 16:52 UTC, Kihyun92 commented on src/Input.test.jsx
> +  };
setup을 통해 각기 다른 테스트 케이스마다 props들을 세팅해주어 다양한 테스트를 작성하신것 같네요! 좋습니다👍
다만 조금 복잡한 것 같아요~ handleChange와 handleClick의 경우, 최초 한번만 선언하도록하면 어떨까요?

```jest
describe('Input', () => {
  const handleChange = jest.fn();
  const handleClick = jest.fn();

  const renderInput = render((
    <Input
      value={value}
      onClick={handleClick}
      onChange={handleChange}
    />
  ));
```

이후 각 테스트에서, `setup`대신 `renderInput`을 호출하면 어떨까요?

2020-10-06 16:52 UTC, Kihyun92 commented on src/List.test.jsx
> +});
task가 있을때와 없을때를 잘 나눠서 테스트해주신 것 같아요! 좋습니다 :)

다만 이 테스트가 뭘 하려는지 조금 더 명확하게 표현해주면 좋을 것 같아요. 이런 경우엔 `Given, When, Then`에 맞춰서 `describe-context-it`의 구조로 표현하면 좋습니다.

```
describe('List', () => {
  context('tasks의 값이 없을 때', () => {
    // Given
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      // When
      const { container } = render(<ListComponent />);

      // Then
      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('tasks의 값이 존재할 때', () => {
    ~~ 생략 ~~
```
이런 형태가 되겠네요. 차례대로 보면 `List는 tasks의 값이 없을 때, "할 일이 없어요!"를 표시한다.`로 이해됩니다.

여기선 이해가 쉽도록 한글로 표현했지만, `context`의 안에는 `with, without, when`만 사용하길 권장합니다.

- https://ko.javascript.info/testing-mocha
- https://www.betterspecs.org/#contexts

2020-10-07 11:16 UTC, saseungmin commented on src/Input.test.jsx
> +    const input = getByLabelText('할 일');
- 알려주신 방법대로 수정을 해봤습니다.
- 무슨 이유인지 고민하다 질문남깁니다!
이 부분이 `TestingLibraryElementError: Unable to find a label with the text of: 할 일` 에러가 나와서 왜 해당 `label`의 `input` 태그를 찾지 못하는지 이유를 잘 모르겠습니다.

2020-10-07 11:21 UTC, saseungmin commented on src/Input.test.jsx
> +    const input = getByLabelText('할 일');
```javascript
test('할 일 입력', () => {
    const { getByLabelText } = render((
      <Input
        onClick={handleClick}
        onChange={handleChange}
      />
    ));
// 생략...
});
```
- 그래서 다음과 같이 각 테스트에서 `render`를 해주게 하였는데 이 방법이 리뷰해주셨던 방향과 일치하는지 모르겠습니다..

2020-10-07 14:10 UTC, saseungmin commented
- 테스트 코드를 모두 작성하였지만 여전히 만족스럽지가 못한거 같습니다.
- 추가적으로 값이 여러개로 주어질 때에 대해서도 테스트 코드를 작성해보겠습니다.
- 또한, 각각의 테스트마다 `render`를 해주었는데 `setup`함수로 하는 방법말고, 어떻게 해야할지 잘 모르겠습니다.
알려주신 방법으로 진행하보았지만, 오류로 인해 각 테스트마다 `render` 함수를 생성하여 호출했습니다.
- 코드리뷰 부탁드립니다! 🚀

2020-10-07 14:50 UTC, Kihyun92 requested changes
많은 시도를 해보고 계신것 같아 좋네요 :) 의논이 필요한 부분이 있으면 편하게 피드백 부탁드립니다~

테스트들 마다 중복되는 테스트들이 있는 것 같아요. 이번 과제는 커버리지 100%를 달성해보는거라 크게 문제가 되진 않지만, 그 원인은 무엇이고, 어떤 방식으로 개선할 수 있을지 고민해보시는 것도 도움이 될 것 같네요~👍

2020-10-07 14:50 UTC, Kihyun92 commented on src/Input.test.jsx
> +    const input = getByLabelText('할 일');
문제를 잘 해결해주셨네요!

제가 말한 의도는 작업하신것과 다르지 않습니다~ 이렇게 각 테스트마다 `render`를 해주게 되면 같은 코드가 중복되는 부분이 발생하게 되어서 상위에서 `input` 컴포넌트를 `render`하는 부분을 함수로 선언해두고 사용하면 어떨까 해서 드린 말씀이었어요~

한번 코드 중복을 없애는 작업을 해보시고, 혹시 이해가 안된다면 피드백 부탁드립니다~ 😁

2020-10-07 14:50 UTC, Kihyun92 commented on src/Input.test.jsx
> +    const input = getByLabelText('할 일');
그리고 이 테스트에도 `describe-context-it`을 적용하면 더 이해하기 좋은 테스트가 될 것 같아요~

2020-10-07 14:50 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('function test', () => {
`function test` 라고 하니 어떤 함수를 테스트하려는건지 의도를 이해하기 힘든 것 같아요

`context` 안에는 `with, without, when`만 사용하도록 권장됩니다~

2020-10-07 14:50 UTC, Kihyun92 commented on src/List.test.jsx
> +} from '@testing-library/react';
줄 바꿈 처리가 되는것 같은데 어떤 설정이 다른 걸까요? 한번 확인 부탁드립니다~

2020-10-07 14:50 UTC, Kihyun92 commented on src/List.test.jsx
> +  };
이 부분도 조금 더 간단하게 표현가능 할 것 같아요~
```suggestion
  const handleClickDelete = jest.fn();

  const renderList = (tasks) => render((
    <List
      tasks={tasks}
      onClickDelete={handleClickDelete}
    />
  ));
```

2020-10-08 14:23 UTC, saseungmin commented
코드리뷰 해주신 부분들을 수정을 해보았습니다.
하던 중 궁금한 사항이 생겼는데 
> `context` 안에는 `with`, `without`, `when`만 사용하도록 권장됩니다~

라고 말씀해주신 부분이 아래의 `Given`, `When`, `Then`이랑 같은 맥락인가요??
```javascript
  context('tasks의 값이 없을 때', () => {
    // Given
    const tasks = [];

    it('"할 일이 없어요!"를 표시한다.', () => {
      // When
      const { container } = render(<ListComponent />);

      // Then
      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });
```

또한, `fireEvent`에 해당하는 것들은 `context`안에서 사용하면 안되는 것인가요??

2020-10-08 16:31 UTC, Kihyun92 commented
context 안에는 with, without, when만 사용하도록 권장된다라고 말씀 드린 부분은, 

```
context('with tasks', () => {
it('renders tasks', () => {
~~ 생략 ~~

context('without tasks', () => {
it('"할 일이 없어요!" 를 표시', () => {
~~ 생략 ~~ 
```

위와 같이 영어로 했을때 `with, without, when`이 포함되도록 문장을 케이스를 분류해 달라는 말이었습니다~ㅎㅎ

2020-10-08 16:44 UTC, Kihyun92 requested changes

2020-10-08 16:44 UTC, Kihyun92 commented on src/Page.test.jsx
> +      expect(handleClickAddTask).toBeCalled();
다른 테스트에 영향을 받을 것 같습니다. 각 테스트는 독립적으로 실행되어야해요.

`beforeEach`를 이용해서 mocking 함수들을 초기화 시켜주면 각 테스트가 의도치 않게 동작하는 것을 막을 수 있습니다.

```
beforeEach(() => {
  jest.clearAllMocks();
});
```

2020-10-10 07:18 UTC, saseungmin commented on src/Page.test.jsx
> +      expect(handleClickAddTask).toBeCalled();
안 그래도 이 부분에서 `expect(handleClickAddTask).not.toBeCalled();`를 해주니까 아래와 같은 오류가 있어서 제거해주었습니다.

```
expect(jest.fn()).not.toBeCalled()

Expected number of calls: 0
Received number of calls: 1
```
- 그래서 `beforeEach` 를 사용해서 해결이 되었지만, 어떤 테스트에서 영향을 받고 있다는 것인지 정확하게 제가 이해?하고있는게 맞는지 모르겠습니다.
- 독립적으로 실행된다는 것과 현제 다른 테스트에서 영향을 받고 있는다는게 **다른** `test` 페이지에서 영향을 받는다는 것일까요??
아니면, 현재 Page test 페이지에서 `without tasks context`의 `handleClickAddTask`가 이미 호출되어서 그런 것일까요??
그렇게 되어서 아래의 `with tasks context`의 테스트에서 `handleClickAddTask`가 다시 호출되었기 때문에 `expect(handleClickAddTask).not.toBeCalled();`을 하면 테스트에 실패를 한 것일까요??
- 다시 한 번 답변 부탁드립니다!! 😢

2020-10-10 16:24 UTC, Kihyun92 requested changes
좋습니다. 전반적으로 테스트들이 처음보다 이해하기 편해졌어요!

남은 시간을 리펙터링에 조금 더 집중해보면 좋을 것 같네요! 👍

2020-10-10 16:24 UTC, Kihyun92 commented on src/Page.test.jsx
> +      expect(handleClickAddTask).toBeCalled();
제가 설명이 부족했던 것 같아요 ☺️ 

저희는 테스트를 위해서 상단에 `handleClickAddTask`와 같은 함수들을 mocking 했습니다. 그리고 이 mock 함수들을 각 테스트에서 사용을 했구요. 이 과정에서 각 테스트들마다 하나의 함수를 같이 사용하게 되고, 이로 인해 모든 테스트 코드들이 영향을 받을 수 있게 됐습니다.
이러한 상황을 방지하기 위해 jest와 같은 테스트 라이브러리에서는 `clean up`해주는 함수들을 제공해요~ 그 중 하나가 [mockClear](https://jestjs.io/docs/en/mock-function-api#mockfnmockclear)입니다. 이걸 각 테스트의 마지막에 호출해주어서 해당 테스트에서 생성된 mock 함수와 mock 인스턴스들을 `clean up`해주는 식으로 주로 사용합니다.

이걸 각 테스트별로 하면 중복 코드가 발생하기 때문에 경우에 따라서 `beforeEach`와 함께 [jest.clearAllMocks()](https://jestjs.io/docs/en/jest-object#jestclearallmocks)를 사용하여 각 테스트 시작 전에 `clean up`해주어 각 테스트들의 의존성을 없애서 각 테스트가 독립적으로 실행되게 만들어 주는거죠 🙌

각 문서를 링크해뒀으니 한번 읽어보시고, 의논할 내용 있으면 언제든 피드백주세요~

2020-10-10 16:24 UTC, Kihyun92 commented on src/App.test.jsx
> +  context('all flow test', () => {
context내에 `all flow test`라는 문장은 적합하지 않은 것 같습니다. 이 경우에는 context없이 it으로만 처리해주는게 더 좋을 것 같아요~

2020-10-10 16:24 UTC, Kihyun92 commented on src/App.test.jsx
> +      fireEvent.click(finishButton);
```suggestion
      fireEvent.click(getByText('완료'));
```
따로 선언하고, 할당해줄 필요 없이 한번에 작성하는건 어떨까요?

2020-10-10 16:24 UTC, Kihyun92 commented on src/Page.test.jsx
> +    const task = '아무것도 하지 않기';
각 context마다 공통적으로 사용된다면 상위에서 관리하는게 좋을 것 같습니다.

2020-10-10 16:24 UTC, Kihyun92 commented on src/Input.test.jsx
> +      getByText('추가');
`getBy*`는 해당 요소를 찾지 못하면 에러가 발생해서 충분히 테스트 가능하지만, assert 문으로 작성한다면 의도를 더 분명히 할 수 있을 것 같아요~

`expect(getByText('추가')).not.toBeNull();`

2020-10-11 05:04 UTC, saseungmin commented on src/Page.test.jsx
> +      expect(handleClickAddTask).toBeCalled();
자세한 답변 감사합니다~! 🙏
Page test 상단에 테스트를 위해서 `const handleChangeTitle = jest.fn();` 해주게 되었고, 이걸 현재 page test에서 두 개의 테스트에서 하나의 함수로 같이 사용하게 되어서 영향을 받는 다는 거군요!!
그렇기 때문에 독립적으로 실행시키기 위해서 `clean up` 해주는 함수인 `jest.clearAllMocks()`를 `beforeEach`와 함께 사용하여 테스트 시작 전에 mocking한 모든 함수를 clean up해주는 것이군요.

2020-10-11 05:08 UTC, saseungmin commented on src/App.test.jsx
> +  context('all flow test', () => {
`context`는 `with`, `without`, `when`만이 권장되고? 테스트가 하나이기 때문에 굳이 사용할 필요가 없었군요..
생각을 못하고 있었습니다! 😅

2020-10-11 12:08 UTC, Kihyun92 approved these changes
쉽지 않은 과제였는데 잘해주신 것 같아요!👍
이번 과제를 하면서 무엇을 배웠는지 한번 되돌아 보시면 좋겠습니다~

과제 풀이 꼭 보시고, 회고도 부탁드려요😁

2020-10-11 14:41 UTC, saseungmin commented
이번주 코드리뷰 감사합니다!! 🙏🙏

2020-10-19 13:25 UTC, merged