[3주차] To-do 리스트 테스트 작성하기
CodeSoom/week3-assignment-1 pull request #33
Opened 2020-10-05 17:28 UTC by oceanide2

**진행사항**
- Input 컴포넌트에 대한 테스트 작성

**느낀점**
- react testing library API 사용법을 이해하지 못하고 있으며 여기 저기 자료를 참고해서 가져다 쓰기도 힘들었습니다.

**궁금한 점**
- 테스트 케이스마다 반복되는 render함수를 제거하려면 어떻게 해야하는지 궁금합니다. 
- react testing library 공식문서를 조금 읽어보았지만 내용이 거의 이해가 되지 않았습니다. 조금 쉬운 참고 자료가 있을까요?

2020-10-06 13:56 UTC, hannut91 requested changes
* 테스트 케이스마다 반복되는 render함수를 제거하려면 어떻게 해야할까요
render하는 것을 추상화해서 함수로 분리하면 좋을 것 같아요. render함수를 한 번만 호출해서는 안됩니다. 우리가 테스트하는게 render하는 것 자체를 테스트하니까요. 함수로 분리해서 최상단 describe 아래에 함수를 정의하면 좋을 것 같아요.

* describe-context-test 구조로 작성할 때, 코드가 어느 위치에 있는지에 따른 접근 범위
어떤 경우에 에러나는지 정확히 이해를 못했습니다. DM으로 문의주시면 자세히 답변드리겠습니다.

* react testing library 공식문서를 조금 읽어보았지만 내용이 거의 이해가 되지 않았습니다. 조금 쉬운 참고 자료가 있을까요?
react testing library에 대한 다른 문서는 찾아보질 않아서 잘 모르겠습니다. 혹시 다른 문서를 보시더라도 공식문서는 꼭 참고하셔야 합니다.

* render 함수에서 반환되는 여러 가지 쿼리함수가 어떤 파라미터를 가지고 사용되는지 등이 정리된 사이트나 문서가 있을까요?
라이브러리의 공식 API를 참고하는게 좋을 것 같습니다.
https://testing-library.com/docs/react-testing-library/api#render

2020-10-06 13:56 UTC, hannut91 commented on src/Input.test.jsx
> +    );
`<Input />`컴포넌트를 렌더하는 부분이 계속 반복되는 것 같아요. 함수로 추출해서 중복을 제거해줄 수 있을까요?

2020-10-06 13:56 UTC, hannut91 commented on src/Input.test.jsx
> +  test('Label을 확인한다', () => {
Label을 확인하는 테스트라서 `Label을 확인한다`라고 이름을 지으신 것 같아요 

테스트를 작성하실 때 `Given, When, Then`에 맞춰서 코드를 작성해보세요. 이러한 형식에 맞춰서 테스트를 작성하는 연습을 하면 좋은 테스트를 작성하는데 많은 도움이 됩니다. 

```js
describe('render', () => {
  context('tasks가 없을 떄', () => {
    // Given
    const tasks = [];

    it('빈 메세지를 표시합니다.', () => {
      // When
      const { container } = render(<SomeComponent />);

      // Then
      expect(container).toHaveTextContent('투두가 없습니다.');
    });
  });
  
  context('tasks가 있을 때', () => {
    // Given
    const tasks = [{ id: 1, task: '밥먹기' }];

    it('tasks 목록을 출력한다', () => {
      ...
    });
  });
});
```

그래서 차례대로 읽어보면 `render는 tasks가 없을 때 빈 메시지를 출력한다.`, `render는 tasks가 있을 때 tasks목록을 출력한다.`로 읽을 수 있습니다. 그래서 자연스러운 문장이 됩니다. 영어로 작성해도 마찬가지에요. 그래서 `context`안에는 `with, without, when`만 사용하도록 권장합니다.

See also
  - https://ko.javascript.info/testing-mocha
  - https://www.betterspecs.org/#contexts

2020-10-07 11:05 UTC, oceanide2 commented
- Input 컴포넌트의 렌더링되는 부분을 함수로 고쳐서 describe와 context 사이로 옮겼습니다.

- 한가지 궁금한 사항은 아래 코드에서 ```debug(input)```로 엘리먼트를 출력해보면 2곳에서 모두 ```value="운동하기"```로 표시가 되는 것 같습니다. 마지막의 debug에서는 공백이 나올 거라고 생각했었는데, 그렇지 않은 이유가 궁금합니다.
``` 
context('추가 버튼을 클릭하면', () => {
    test('handleClick()를 호출한다', () => {
      const value = '운동하기';

      const { getByLabelText, getByText } = renderInput(value);
      const input = getByLabelText('할 일');

      expect(input).toHaveDisplayValue('운동하기');
      debug(input);

      fireEvent.click(getByText('추가'));

      expect(handleClick).toHaveBeenCalled();
      expect(input).toHaveDisplayValue('');
      debug(input);
    });
  });
```

2020-10-07 14:51 UTC, oceanide2 commented
- Input 컴포넌트의 테스트와 비슷한 작성방식으로 List와 Page 컴포넌트의 테스트를 작성하였습니다.
- react testing library 공식 문서에는 getByRole을 우선적으로 쓰라고 나와있는 것 같은데, 해당 API를 사용하면 코드가 눈에 잘 들어오지 않아서 getByText, getByLabelText등을 주로 사용하여 작성하였습니다.
- 각 컴포넌트별로 테스트 항목을 어떤 기준으로 분류하고 모아야할지를 아직은 잘 모르겠습니다.

2020-10-07 15:25 UTC, hannut91 commented
`value`의 값이 변하지 않는 이유는 `Input`컴포넌트에서  `value`는 props의 `value`에 의해서만 값이 변하기 때문입니다. 실제로 상태가 변하여 `Page`컴포넌트로 변한 `value`를 전달하는 곳은 `App`컴포넌트입니다. `value`가 변하는 테스트는 이 `Page`컴포넌트에서 테스트해야하는 관심사가 아닙니다. `Page`컴포넌트는 주어진 값으로 올바르게 출력하고 이벤트가 발생했을 때 전달해주는 일만 하고 있기 때문입니다.

2020-10-07 15:27 UTC, hannut91 commented
* 각 컴포넌트별로 테스트 항목을 어떤 기준으로 분류하고 모아야할지를 아직은 잘 모르겠습니다.
테스트를 일종의 사용설명서라고 생각해보시면 좋을 것 같아요. 해당 컴포넌트를 사용하는 사람에게 예제로 테스트를 제공하는거죠. 무엇을 보여주고 싶으신가요?

2020-10-07 23:37 UTC, oceanide2 commented
> `value`의 값이 변하지 않는 이유는 `Input`컴포넌트에서 `value`는 props의 `value`에 의해서만 값이 변하기 때문입니다. 실제로 상태가 변하여 `Page`컴포넌트로 변한 `value`를 전달하는 곳은 `App`컴포넌트입니다. `value`가 변하는 테스트는 이 `Page`컴포넌트에서 테스트해야하는 관심사가 아닙니다. `Page`컴포넌트는 주어진 값으로 올바르게 출력하고 이벤트가 발생했을 때 전달해주는 일만 하고 있기 때문입니다.

Input 테스트에서 `expect(input).toHaveDisplayValue('');`가 Pass되는 것이 이해가 되지 않습니다. 공식 문서를 보고 toHaveDisplayValue는 주어진 엘리먼트의 value가 존재 여부를 체크하는 것으로 생각했는데, debug로 찍어보면 해당 엘리먼트에 value는 있어보이고 공백을 체크하는 테스트가 통과하는 것처럼 보여서 이게 헷갈립니다.

2020-10-08 14:37 UTC, oceanide2 commented
- 하위 컴포넌트에서 상위컴포넌트로 테스트를 작성해 나갔는데, 상위 컴포넌트로 갈수록 하위 컴포넌트에서 수행했던 테스트를 모으는 것 같다는 생각이 들었습니다. 이런 생각이 드니 각 컴포넌트마다 테스트 항목을 제대로 나눈게 맞나라는 생각이 들고 있습니다. 일단 현재까지 작성한 것은 올리고 각 컴포넌트 별로 다시 한번 생각해보려고 합니다.

2020-10-08 14:45 UTC, hannut91 commented
Input 테스트에서 expect(input).toHaveDisplayValue('');가 Pass되는 것이 이해가 되지 않습니다. 공식 문서를 보면 toHaveDisplayValue는 주어진 엘리먼트의 value가 존재하는지 체크하는 것으로 생각했는데, debug로 찍어보면 해당 엘리먼트에 value는 있어보이고 공백을 체크하는 테스트가 통과하는 것처럼 보여서 이게 헷갈립니다.
* 작성중...

하위 컴포넌트에서 상위컴포넌트로 테스트를 작성해 나갔는데, 상위 컴포넌트로 갈수록 하위 컴포넌트에서 수행했던 테스트를 모으는 것 같다는 생각이 들었습니다. 이런 생각이 드니 각 컴포넌트마다 테스트 항목을 제대로 나눈게 맞나라는 생각이 들고 있습니다. 일단 현재까지 작성한 것은 올리고 각 컴포넌트 별로 다시 한번 생각해보려고 합니다.
* 작성중...

test대신 it를 사용하는 것도 가능한 것 같은데, 2개 중에 어떤 것을 쓰던지 팀 또는 개인의 취향일까요? :)
* 간단한 테스트의 경우 `test`를 사용하고 `describe-context-it`을 쓸 때는 저는 `it`을 씁니다. betterspecs를 따라서 그런 것 같아요
See also
  - https://www.betterspecs.org/

2020-10-08 14:52 UTC, hannut91 requested changes

2020-10-08 14:52 UTC, hannut91 commented on src/Input.test.jsx
> +
`beforeEach`를 이용해서 mocking함수들을 초기화 시켜줘야 테스트가 의도치 않게 동작하는 것을 막을 수 있습니다.

```js
beforeEach(() => {
  jest.clearAllMocks();
});
```

2020-10-09 15:41 UTC, oceanide2 commented
Input 컴포넌트의 테스트 코드를 다시 작성해봤습니다. 위에서 언급해주신 대로 주어진 value값 출력, onChange와 onClick이벤트에 대한 함수 실행이 주요 동작이라도 생각했습니다.
- `텍스트가 입력 되면, 화면에 표시한다`는 케이스를 추가했습니다. value값이 제대로 표시되는지를 확인해야된다고 생각했습니다.
- renderInput 함수의 value 초기값을 삭제하고 각 테스트 케이스에서 value값을 따로 정의했습니다. 이렇게 하는 것이 Given, When, Then에 더 맞다고 생각했습니다.

2020-10-09 16:36 UTC, oceanide2 commented
List 컴포넌트의 테스트 코드를 다시 작성하였습니다. List 컴포넌트는 tasks, onClickDelete이벤트를 Item컴포넌트로 전달하고 tasks항목이 비어있을 때 메시지를 출력하는 것을 주요 동작이라고 생각했습니다. 

- List 컴포넌트는 Item 컴포넌트를 하위 컴포넌트로 가지고 있어서 여기서부터 테스트 코드를 작성하는 것이 고민이 되기 시작했습니다. List컴포넌트는 Item컴포넌트로 tasks와 onClickDelete를 전달만 하기 때문에 tasks항목이 비어있는 경우에 대해서만 테스트를 작성하면 되지 않을까? 라는 생각이 들었습니다.

- 테스트 코드를 사용자 설명서로 생각하라고 말씀해주셔서, List 컴포넌트에서도 tasks 출력과 onClickDelete 동작에 대한 테스트는 추가하였습니다. 하지만, 이 2가지 테스트는 Item 컴포넌트에서 수행하는 테스트 코드와 중복이 된다고 생각했습니다. 그래서 List 컴포넌트에서는 tasks가 1개 이상인 경우에 대해서 테스트를 작성하였습니다.

- 테스트 코드를 사용자 설명서라고 생각하면 tasks 출력과 onClickDelete 동작을 테스트 코드로 포함해야 한다고 생각합니다. 하지만, tasks 출력과 onClickDelete 동작이 Item 컴포넌트의 동작으로 생각한다면 List 컴포넌트에서는 빈 메시지를 출력하는 테스트 케이스만 포함되어야 하는게 아닐까요? 트레이너님의 의견이 궁금합니다.

2020-10-10 14:16 UTC, hannut91 approved these changes
테스트 코드를 사용자 설명서라고 생각하면 tasks 출력과 onClickDelete 동작을 테스트 코드로 포함해야 한다고 생각합니다. 하지만, tasks 출력과 onClickDelete 동작이 Item 컴포넌트의 동작으로 생각한다면 List 컴포넌트에서는 빈 메시지를 출력하는 테스트 케이스만 포함되어야 하는게 아닐까요? 트레이너님의 의견이 궁금합니다.

* 어디까지 테스트할지 잘 정하는게 좋을 것 같아요. List 컴포넌트관점에서 보면 지금 비어있는 경우와 여러개가 있는 경우가 있잖아요. 이걸 테스트롤 명확하게 표현해주는게 좋을 것 같아요

2020-10-10 14:16 UTC, hannut91 commented on src/App.test.jsx
> +    });
여기도 단순히 텍스트가 존재하는지만 확인한다면 다음과 같이 하는것도 좋을 것 같아요.

```js
expect(container).toHaveTextContent('To-do');
```

See also
  - https://github.com/testing-library/jest-dom#tohavetextcontent

2020-10-10 14:16 UTC, hannut91 commented on src/Page.test.jsx
> +      expect(input).toHaveDisplayValue('');
정확한 테스트가 아니라서 이부분도 다시 수정해야겠네요.
추가 버튼을 클릭했을 때 핸들러만 호출되는 것을 테스트하면 되니 단순해지겠네요

2020-10-10 14:17 UTC, hannut91 commented
지금처럼 계속 명확하게 이해하지 못했다면 계속 질문을 던지고 답변을 찾으며 과제를 하시면 정말 실력이 많이 느실 것 같아요.
이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

2020-10-11 13:32 UTC, hannut91 commented
좋습니다! ㅎㅎ 회고를 작성해주시면 머지하겠습니다!

2021-01-17 13:02 UTC, merged