[Week3] Assignment 1 - Todo List 테스트 코드 작성
CodeSoom/week3-assignment-1 pull request #35
Opened 2020-10-06 12:24 UTC by wjy5446

# 3주차 과제 1 
## 요구사항
- 모든 컴포넌트에 테스트를 작성한다.

## 구현할 기능
- App.text.jsx
- List.test.jsx
- Item.test.jsx
- Input.test.jsx
- Page.test.jsx

## 작업 내용

- [x] Item.test.jsx
  - task 입력시 task의 title과 버튼이 추가되었는 지 확인
  - 버튼 클릭시 handleClick이 호출되는 지 확인

- [x] List.test.jsx
  - tasks 입력시 입력된 task가 모두 출력되는 지 확인
  - tasks 입력시 task 순서대로 item이 생성되는 지 확인
  - tasks 없을시 '할 일 없어요'이 출력되는 지 확인

- [ ] Input.test.jsx
  - '할 일' 라벨이 출력되는 지 확인
  - '추가' 버튼이 있는 지 확인
  - value가 없을 때, '할 일을 입력해주세요' placeholder가 출력되는 지 확인
  - value가 있을 때, value가 출력되는 지 확인
  - input에 입력되었을 때 handleChange가 호출되는 지 확인
  - input에 입력되었을 때 inpu의 value가 입력한 값으로 호출되는 지 확인
  - '추가' 버튼 클릭시 handleClick이 호출되는 지 확인
  - '추가' 버튼 클릭시 List에 변화가 있는 지 확인

- [ ] App.test.jsx

- [ ] Page.test.jsx

2020-10-06 13:22 UTC, hannut91 requested changes
재영님 안녕하세요 ㅎㅎ 테스트를 잘 작성해주신 것 같아요. 테스트 대상에 따라서 잘 나누는 연습만 좀 더 해보시면 좋을 것 같습니다

2020-10-06 13:22 UTC, hannut91 commented on README.md
> +
여기 빈 줄이 들어갔군요! 이유가 있다면 코드 리뷰를 하는 사람에게 왜 이 줄이 변경되었는지 알려주면 좋을 것 같아요.

2020-10-06 13:22 UTC, hannut91 commented on src/List.test.jsx
> +  expect(getAllByText(/뭐라도 하기/)[2]).toHaveTextContent('뭐라도 하기3');
`tasks`목록이 잘 출력되는지 테스트하고 계신 것 같아요. 그런데 `뭐라도 하기`같은 Magic literal 존재하고, 비슷한 일을 반복하는 것 같아요. 이 테스트들을 `tasks`를 이용해서 표현해줄 수 있을까요?

2020-10-06 13:22 UTC, hannut91 commented on src/List.test.jsx
> +  expect(container).toHaveTextContent('할 일이 없어요!');
하나의 테스트 단위는 하나의 테스트만 해야 합니다. 이런 경우 테스트를 나눠서 테스트해주시면 좋을 것 같아요.
간단한 테스트일 경우 `test`를 이용해서 테스트를 만들지만, 여러개의 테스트를 할 경우에는 `describe-context-it`을 사용하는게 좋아요.

테스트를 작성하실 때 `Given, When, Then`에 맞춰서 코드를 작성해보세요. 이러한 형식에 맞춰서 테스트를 작성하는 연습을 하면 좋은 테스트를 작성하는데 많은 도움이 됩니다. 

```js
describe('List', () => {
  context('tasks가 없을 떄', () => {
    // Given
    const tasks = [];

    it('빈 메세지를 표시합니다.', () => {
      // When
      const { container } = render(<SomeComponent />);

      // Then
      expect(container).toHaveTextContent('투두가 없습니다.');
    });
  });
  
  context('tasks가 있을 때', () => {
    // Given
    const tasks = [{ id: 1, task: '밥먹기' }];

    it('tasks 목록을 출력한다', () => {
      ...
    });
  });
});
```

그래서 차례대로 읽어보면 `render는 tasks가 없을 때 빈 메시지를 출력한다.`, `render는 tasks가 있을 때 tasks목록을 출력한다.`로 읽을 수 있습니다. 그래서 자연스러운 문장이 됩니다. 영어로 작성해도 마찬가지에요. 그래서 `context`안에는 `with, without, when`만 사용하도록 권장합니다.

See also
  - https://ko.javascript.info/testing-mocha
  - https://www.betterspecs.org/#contexts

2020-10-06 13:31 UTC, wjy5446 commented on README.md
> +
readme 파일에 작업할 내용을 잠시 써 두었다가 지우면서 빈칸이 들어 갔나 보군요. 
수정하겠습니다. !!

2020-10-06 13:48 UTC, wjy5446 commented on src/List.test.jsx
> +  expect(getAllByText(/뭐라도 하기/)[2]).toHaveTextContent('뭐라도 하기3');
보니깐 반복되는 패턴이 많네요.
그래서 map 을 이용해서 테스트하는 코드로 변경 했습니다.

2020-10-06 13:51 UTC, wjy5446 commented on src/List.test.jsx
> +  expect(container).toHaveTextContent('할 일이 없어요!');
jest에서 describe - context - it이 되는 군요. 제가 찾아본 블로그에서 jest는 context가 없다고 해서 추가 않 했습니다. ㅠㅠ

그리고 알려주신 given - when - then 맞춰서 코드를 작성하니 더 보니 편한 것 같습니다. 

감사합니다.

2020-10-07 15:18 UTC, hannut91 requested changes
테스트를 잘 작성해주셨네요! 다른 컴포넌트에도 테스트를 작성해주세요 ㅎㅎ

2020-10-07 15:18 UTC, hannut91 commented on src/List.test.jsx
> +      tasks.map((task) => expect(getByText(task.title)).toHaveTextContent(task.title));
`map`메소드는 callback함수의 반환값으로 이루어진 배열을 반환합니다. 그래서 여기서 `map`을 사용하는건 적절한 것 같지 않습니다. 왜냐하면 지금 콜백 함수가 side effect를 만들어내고 있기 때문입니다. 따라서 여기서는 `forEach`메서드를 사용하는게 더 맞는 것 같아요

2020-10-07 15:38 UTC, wjy5446 commented
# Input 테스트 코드 작성

- Input에 해당되는 코드를 작성했습니다.
- 하지만 작성하면서 몇몇 궁금한 부분이 존재하네요. 

## 질문 사항

- 디자인과 관련된 테스트 (ex Input에 라벨 명이 잘 있는지 확인)는 딱히 given이 없는 상태에서 확인이 가능합니다. 그래서 이럴 경우에는 '기본 값일 때'란 context를 생성하는 게 나을 까요? 아님 context가 없이 it으로 바로 만들어 주는 게 좋을 까요?

- Input Component의 경우 추가 버튼을 클릭할 때, List Component의 변화를 줍니다. 이럴 경우, `Input의 추가 버튼이 클릭 시, 리스트에 항목이 잘 나타나는 지에 대한 테스트`는 Input과 List의 상위 Component은 Page에서 작성하는 게 좋은 가요?

- `Input에 value가 변화되었을 때, 변화된 값이 유저에게 보이는 지에 대한 테스트`를 수행하고 싶은데, fireEvent를 통해서 handleChange를 호출하면, 값이 변경되지 않네요. 어떻게 코드를 작성하면 제시한 테스트를 수행할 수 있을 까요?

2020-10-07 15:41 UTC, hannut91 commented
* 디자인과 관련된 테스트 (ex Input에 라벨 명이 잘 있는지 확인)는 딱히 given이 없는 상태에서 확인이 가능합니다. 그래서 이럴 경우에는 '기본 값일 때'란 context를 생성하는 게 나을 까요? 아님 context가 없이 it으로 바로 만들어 주는 게 좋을 까요?
context없이 it으로 바로 만들어주는게 좋을 것 같습니다

* Input Component의 경우 추가 버튼을 클릭할 때, List Component의 변화를 줍니다. 이럴 경우, Input의 추가 버튼이 클릭 시, 리스트에 항목이 잘 나타나는 지에 대한 테스트는 Input과 List의 상위 Component은 Page에서 작성하는 게 좋은 가요?
Page 컴포펀트에서도 props에서 받은 값을 그대로 `Input`값으로 전달하고 있기 때문에 이 테스트는 `App`테스트에서 작성하는게 맞습니다.

* Input에 value가 변화되었을 때, 변화된 값이 유저에게 보이는 지에 대한 테스트를 수행하고 싶은데, fireEvent를 통해서 handleChange를 호출하면, 값이 변경되지 않네요. 어떻게 코드를 작성하면 제시한 테스트를 수행할 수 있을 까요?
값이 변경되지 않습니다. `Input`이 정확히 어떤 일을 하는지 잘 생각해보시면 좋을 것 같아요. `value`값이 주어지면 그 값을 `input`의 value로 넣습니다. 그리고 변화했을 때 주어진 `onClick`을 실행하는 일을 합니다. 변경에 대한 정보는 이 컴포넌트에는 없습니다. 상태를 관리하는 `App`에서 상태를 변경하고, 그 상태를 다시 `Page`에 `value`props로 전달하여 실제로 `Input`의 `value`가 변합니다.

2020-10-07 15:47 UTC, wjy5446 commented on src/List.test.jsx
> +      tasks.map((task) => expect(getByText(task.title)).toHaveTextContent(task.title));
피드백 감사드립니다. forEach 메서드로 변경하겠습니다.
그런데 말씀해 주신 부분에서 `콜백 함수가 side effect를 만들고 있다.`라는 부분이 잘 이해가 되지 않는데, expect함수나 toHaveTextContent 함수가 외부 상태에 영향을 주나요?

2020-10-07 15:50 UTC, hannut91 commented on src/List.test.jsx
> +      tasks.map((task) => expect(getByText(task.title)).toHaveTextContent(task.title));
외부 상태를 변경하는 것만이 `side effect`는 아닙니다. 함수로 반환하는 것 외에는 모두 side effect입니다. 예를들어 화면에 출력하는 것도 `side effect`에요. forEach의 반환값은 아무것도 없습니다. 그래서 반환값으로 아무것도 할 수 있는게 없죠. 사실상 `side effect`를 위해서 사용하는 함수입니다

2020-10-07 16:01 UTC, wjy5446 commented on src/List.test.jsx
> +      tasks.map((task) => expect(getByText(task.title)).toHaveTextContent(task.title));
답변 감사드립니다. ㅎㅎ
`side effect`가 담고 의미가 많군요. 다시 한번 side effect의 정의에 대해서 공부 해야겠네요.

2020-10-07 17:33 UTC, wjy5446 commented
# Page, App 테스트 코드 작성 

- Page, App에 대한 테스트 코드를 작성했습니다.
- 작성된 테스트는 최상단의 comment에 작성에 두었습니다.

## 질문사항

- 테스트 코드를 작성하다 보니, 하위 컴포넌트는 디자인적인 테스트와 함수 호출 테스트로 간단한 부분만 작성되었고, 최상단 컴포넌트에서 동작에 대한 테스트가 작성되었네요. 보통 이런 식으로 테스트 코드가 작성되는 것이 맞나요?

- 최상단 App 컴포넌트의 경우, props으로 입력을 받아서 생성되는 것이 아니라 자체 내부의 state를 통해서 생성되기 때문에, given 부분을 작성하기 어려워 Context를 제거하고, 바로 it으로 작성했습니다. 하지만 이렇게 작성하다 보니 test 코드 내부가 꽤 보기 힘들어 졌네요. 혹시 state를 직접 조작해서 describe - context - it 구조로 작성할 수 있는 방법이 있나요?

- App 컴포넌트의 테스트 코드의 경우에는 이벤트를 통해서 변경된 내용을 테스트 하기 때문에, 이벤트 발생 전 상태와 이벤트 발생 후 상태를 모두 테스트 했습니다. 하지만 이렇게 작성하다 보니 다른 테스트와 중복되는 부분도 존재하고, 코드가 복잡해져 버리네요. 보통 이런 경우, 이벤트 발생 전 상태, 이벤트 발생 후 상태 모두 테스트를 진행하나요?

- App 컴포넌트의 `추가 버튼이 클릭 되었을 때, list에 task가 추가 되는 지 확인` 테스트에서 task가 없을 경우에는 List가 p 태그이고, task가 있을 경우에는 List가 ol 태그가 됩니다. 그래서 이벤트 발생하기 전에 쿼리함수를 통해서 List를 찾고, 이벤트를 발생시키면 변화를 감지하지 못하네요. 그래서 변화된 후에 다시 쿼리함수로 List를 찾아 주는 방법으로 해결했습니다. 하지만 더 좋은 방법이 있을 것 같은 데 어떻게 하면 좋을 까요?

2020-10-08 14:06 UTC, hannut91 commented
테스트 코드를 작성하다 보니, 하위 컴포넌트는 디자인적인 테스트와 함수 호출 테스트로 간단한 부분만 작성되었고, 최상단 컴포넌트에서 동작에 대한 테스트가 작성되었네요. 보통 이런 식으로 테스트 코드가 작성되는 것이 맞나요?
* 관심사에 따라 올바르게 테스트를 작성해주신 것 같아요 ㅎㅎ

최상단 App 컴포넌트의 경우, props으로 입력을 받아서 생성되는 것이 아니라 자체 내부의 state를 통해서 생성되기 때문에, given 부분을 작성하기 어려워 Context를 제거하고, 바로 it으로 작성했습니다. 하지만 이렇게 작성하다 보니 test 코드 내부가 꽤 보기 힘들어 졌네요. 혹시 state를 직접 조작해서 describe - context - it 구조로 작성할 수 있는 방법이 있나요?
* 작성중...

App 컴포넌트의 테스트 코드의 경우에는 이벤트를 통해서 변경된 내용을 테스트 하기 때문에, 이벤트 발생 전 상태와 이벤트 발생 후 상태를 모두 테스트 했습니다. 하지만 이렇게 작성하다 보니 다른 테스트와 중복되는 부분도 존재하고, 코드가 복잡해져 버리네요. 보통 이런 경우, 이벤트 발생 전 상태, 이벤트 발생 후 상태 모두 테스트를 진행하나요?
* 테스트가 어떤 일을 하고 있는지 더 명확하게 드러내는 것으로 선택하시면 좋을 것 같아요. 이벤트가 발생하기 전의 상태가 이런 상태다라고 표현하고 싶다면 표현해도 괜찮다고 생각해요. 

App 컴포넌트의 추가 버튼이 클릭 되었을 때, list에 task가 추가 되는 지 확인 테스트에서 task가 없을 경우에는 List가 p 태그이고, task가 있을 경우에는 List가 ol 태그가 됩니다. 그래서 이벤트 발생하기 전에 쿼리함수를 통해서 List를 찾고, 이벤트를 발생시키면 변화를 감지하지 못하네요. 그래서 변화된 후에 다시 쿼리함수로 List를 찾아 주는 방법으로 해결했습니다. 하지만 더 좋은 방법이 있을 것 같은 데 어떻게 하면 좋을 까요?
* 태그로 테스트를 작성하는 것은 너무 구현에 의존한 방법인 것 같아요. 단순히 주어진 tasks의 특정 텍스트가 content에 포함되어있는지 확인해도 충분히 의도는 드러낼 수 있을 것 같아요.

2020-10-08 14:21 UTC, hannut91 requested changes

2020-10-08 14:21 UTC, hannut91 commented on src/App.test.jsx
> +    const { getByDisplayValue } = render((<App />));
jsx에서 소괄호를 사용하는 이유는 여러 줄일 경우에 사용하는 거에요 예를들면

```js
render(<Button type="button" />추가</Button>);
```

이런 버튼은 한 줄에 작성해서 상관이 없지만 만약에 다음과 같이 여러줄이라면

```js
render((
<Button 
    type="button" 
    onClick={handleClick}
/>
  추가
</Button>
))
```

그래서 이런 경우에 소괄호가 2개가 들어간거에요. 사실 한개만 써도 상관없지만 그러면 끝에  `,`가 들어가서 두개를 썼던 것 같아요

2020-10-08 14:21 UTC, hannut91 commented on src/App.test.jsx
> +    cleanup();
자동으로 `cleanup`이 되기 때문에 사용안하셔도 괜찮습니다.

See also
  - https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-cleanup

2020-10-08 14:21 UTC, hannut91 commented on src/App.test.jsx
> +  });
너무 많은 것을 테스트하다보니 본질에 집중하기 어려운 것 같아요.

```js
const { getByLabelText, getByText } = render((<App />));

const input = getByLabelText('input-task-title');
const addButton = getByText('추가');

fireEvent.change(input, { target: { value: '뭐라도 하기' } });
fireEvent.click(addButton);

expect(listTasks).toHaveTextContent('뭐라도 하기');
```

2020-10-08 14:56 UTC, wjy5446 commented on src/App.test.jsx
> +    const { getByDisplayValue } = render((<App />));
아 그런 규칙이 있었군요. 감사합니다.
바로 수정 하겠습니다. ㅎㅎ

2020-10-08 15:26 UTC, wjy5446 commented on src/App.test.jsx
> +  });
피드백 감사합니다.
App 컴포넌트 부분을 좀 더 수정해봐야 겠습니다.

2020-10-08 15:29 UTC, wjy5446 commented on src/App.test.jsx
> +    cleanup();
제가 it 밖에서 render를 선언하면 자동적으로 cleanup이 되지 않아서 cleanup을 넣었던 것 같습니다.
it 안에서 render를 선언하면 자동적으로 cleanup이 호출되나 보네요 ㅎㅎ 감사합니다.

2020-10-08 16:56 UTC, wjy5446 commented
# 피드백 

## 작업 내용

- cleanup 함수 제거
- jsx 한줄인 경우, render 함수 내 소괄호 제거
- App 컴포넌트 테스트 코드 이벤트 발생 후, 결과에만 테스트
  - 이벤트 발생 이전의 테스트는 이미 하위 컴포넌트에서 체크해 주기 때문에 발생 이후만 확인
- renderInput 함수 기본값 설정

2020-10-09 15:24 UTC, hannut91 requested changes

2020-10-09 15:24 UTC, hannut91 commented on src/Input.test.jsx
> +  const handleClick = jest.fn();
mock 함수들은 초기화해주지 않으면 테스트가 올바르게 동작하지 않을 수 있습니다. 위에서 이미 `handleChange`가 호출되었을 때 다른 테스트에서 `handleChange`가 호출되었는지 확인할 경우가 올바르게 테스트가 동작하지 않을 수 있습니다.

```js
beforeEach(() => {
  jest.clearAllMocks();
});
```
See also
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks
  - https://jestjs.io/docs/en/setup-teardown

2020-10-09 15:24 UTC, hannut91 commented on src/Input.test.jsx
> +    cleanup();
여기도 `cleanup`을 지우면 좋을 것 같아요

2020-10-09 15:24 UTC, hannut91 commented on src/List.test.jsx
> +      tasks.forEach((task) => expect(getByText(task.title)).toHaveTextContent(task.title));
화살표 함수는 한 줄일 경우 그 결과를 바로 반환합니다. `forEach`는 콜백 함수의 반환값을 사용하지 않으므로 

```js
tasks.forEach((task) => { 
  expect(getByText(task.title)).toHaveTextContent(task.title);
});
```

이렇게 써주는게 좋을 것 같습니다.

2020-10-10 06:09 UTC, wjy5446 commented on src/App.test.jsx
> +  it('input에 값이 변경 되었을 때, input의 값이 변경되는 지 확인', () => {
저도 이 부분에서 `~ 되었을 때, `는 주로 context에서 사용되는 데, it에서 사용하는 게 맞을 까 ? 라고 고민했었습니다.
추천해 주신 방향으로 테스트 명을 변경해야 겠네요. ㅎㅎ

2020-10-10 06:11 UTC, wjy5446 commented on src/App.test.jsx
> +    expect(listTasks).toHaveTextContent('뭐라도 하기');
코드를 다시 보니 쿼리로 해당 텍스트를 찾았는데, 다시 텍스트가 있는 지 확인하네요.
해당 방법으로 수정하겠습니다.

2020-10-10 06:12 UTC, wjy5446 commented on src/Input.test.jsx
> +  const handleClick = jest.fn();
mock 함수는 다시 초기화 시켜주어야 하는 군요!!
바로 추가하겠습니다.

2020-10-10 06:13 UTC, wjy5446 commented on src/Input.test.jsx
> +    cleanup();
cleanup을 다 지우지 못했네요. 
감사합니다.

2020-10-10 06:22 UTC, wjy5446 commented on src/App.test.jsx
> +    const inputTaskTitle = getByDisplayValue('');
해당 코드는 무엇을 지정하는 지 잘 모를 수 있겠네요. 감사합니다.

2020-10-10 06:52 UTC, wjy5446 commented on src/List.test.jsx
> +      tasks.forEach((task) => expect(getByText(task.title)).toHaveTextContent(task.title));
한 줄로 사용할 때에는 반환값이 있는 군요. 처음 알았네요..
감사합니다.

2020-10-10 07:01 UTC, wjy5446 commented
# 피드백

## 작업 내용
- 테스트 코드 명을 "하는 일, 변경 내용" 중점으로 변경
- App 컴포넌트 내 input을 가져오는 쿼리 Label로 가져오기
- clearMockUp 함수 추가
- 텍스트 확인 테스트 코드 container에 찾아 간단하게 변경
- foreEach 함수 반환값이 없도록 변경
- cleanup 코드 제거

2020-10-10 14:28 UTC, hannut91 approved these changes
테스트를 잘 작성해주신 것 같아요 ㅎㅎ 앞으로 과제를 진행하면서 테스트는 필수기 때문에 앞으로도 더 연습할 기회가 많이 있을거에요. 처음 작성했을 때보다 얼마나 더 나아졌는지 확인해보시면 좋을 것 같습니다.

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

2020-10-10 14:28 UTC, hannut91 commented on src/List.test.jsx
> +    });
단순히 텍스트가 있는지 확인할 때는 다음과 같이 할 수도 있습니다.

```js
const { container } = render(<List tasks={tasks} />);

tasks.forEach(({ title }) => {
  expect(container).toHaveTextContent(title);
});
```

2020-10-10 14:28 UTC, hannut91 commented on src/Page.test.jsx
> +});
이 함수는 `describe`안에 들어가는게 좋을 것 같아요

2020-10-11 07:08 UTC, wjy5446 commented on src/List.test.jsx
> +    });
object destruction을 이용하면 더 간단히 표현이 가능하군요!!
감사합니다.

2020-10-11 07:09 UTC, wjy5446 commented on src/Page.test.jsx
> +});
해당 코드는 describe 안에서 작성되는 군요!! 감사합니다.

2020-10-11 12:59 UTC, wjy5446 commented
# 피드백 

## 수정사항 
- object destruction 으로 코드 간단하게 표현
- clearAllMocks 함수 description 내에 선언

2020-10-11 13:31 UTC, hannut91 commented
좋습니다! 회고를 작성해주시면 머지하겠습니다!

2020-10-11 15:27 UTC, wjy5446 commented
# 3주차 회고

## 1. 한 일
- jest 코드 문서 튜토리얼 읽기
- jest-dom의 Readme 읽기
- testing-library/react 공식 문서 읽기
- To-do 테스트 작성 하기

## 2. 배운점 

- `given - when - then`과 `describe - context - it` 구조로 테스트 코드 작성
- `jest`, `jest-dom`, `testing-library`에 대한 전체적인 개념 이해


- 하나의 테스트 코드에서 되도록 하나의 테스팅만 진행
- 컴포넌트를 작성할 때, 하위 컴포넌트는 디자인 테스팅, 함수 호출 및 props의 값 확인에 대해서만 진행, 반면 상위 컴포넌트에서 전체적인 동작에 대한 테스팅을 진행
- 기본 값일 때의 테스트(디자인, 함수호출)은 context 없이 테스트 코드 작성
- cleanup의 경우에는 자동적으로 호출됨. (description에서 render 호출 시에는 cleanup이 호출되지 않음)
- 테스트 코드 설명을 적을 때, 대상의 중점으로 작성
- 간단한 구조일 때, 쿼리로 대상을 찾기 않고, container를 이용해서 작성.
- mock 함수 작성시 clearAllMocks 함수 선언


- map 함수는 콜백함수에 대한 반환값을 배열로 출력되기 때문에 side effect가 생길 수 있음. 그렇기 때문에 반환값이 없는 반복문은 forEach 함수 사용.
- jsx가 한줄일 때, 소괄호 사용하지 않기.
- object destruction으로 코드 간단하기 작성.

## 3. 느낀 점 & 자기 선언 

그 동안 주변에서 듣기만 했던 TDD를 직접해 보았다. 처음에는 jest, jest-dom, testing-library에 대해서 대락적인 구조 파악에 시간을 많이 썼던 것 같다.  하지만 해당 라이브러리에 대해서 대략적으로 이해해도 테스트 코드를 작성하는 건 어려웠다. 실제로 작성해보니 해당 라이브러리에 대한 이해도 중요하지만 각 Component의 필요한 테스트 코드가 무엇인지 고민해야 되고, 어떤 구조로 테스트 코드를 작성하는 게 좋은 지에 대해서 많은 고민이 필요했다. 

그래도 멘토님의 수많은 피드백으로 대략적인 테스트 코드의 작성해서 어느 정도 감은 잡은 것 같다. 내 나름의 테스트 작성 방법에 대해서 적어보자면 아래와 같다.
```
1. 기본적으로 초기에 나타나는 디자인에 대한 테스트 코드를 작성한다.
2. props을 상태값을 전달 받아 사용하는 컴포넌트의 경우에는 given으로 props 값을 주어서 props에 대한 테스트 코드를 작성한다.
3. props으로 함수를 전달 받은 컴포넌트의 경우에는 mock 함수를 이용해 함수가 호출되는 지에 대한 테스트 코드를 작성한다.
4. state와 handle 함수가 정의 되어 있는 상위 컴포넌트에는 실제 앱의 동작에 대한 테스트 코드를 작성한다.
```  
이게 틀릴 수도 있고, 맞을 수도 있지만 이 정도의 감을 잡은 것도 큰 발전이라고 생각한다.

하지만 아직도 test 라이브러리에 대한 코드를 작성하는 데, 미숙한 부분이 존재한다. 좀 더 자세히 공부해봐야겠다.

또한 이번에 테스트 코드를 작성하면서 `왜 테스트코드를 작성하는가?`에 대해서 생각해보았다. 원래는 단지 테스트 코드를 작성하면서 오류를 줄이기 위해서 작성하는 것이라 생각했는데, 그것 이외에도 테스트를 미리 작성하면서 자신이 작성하는 제품이 어떻게 작동하는 지에 대해서 먼저 고민하면서 내가 구현할 기능을 좀 더 명확히 이해하는 과정을 겪은 것 같다. 그러면서 좀 더 사용자 중점으로 코드를 작성하는 장점을 가지는 것 같다. 직접 테스트 코드를 작성하니 TDD의 필요성을 직접 깨달은 것 같다.

2021-01-17 12:59 UTC, merged