Add test code
CodeSoom/week3-assignment-1 pull request #36
Opened 2020-10-06 13:01 UTC by smilee

Add test code to test components

2020-10-06 17:06 UTC, Kihyun92 requested changes
모든 컴포넌트에 대해서 일단 테스트를 만들어 보신게 좋네요!

그리고 test 폴더에서 모든 테스트 파일들을 관리하는 것도 좋은 것 같습니다~ 실제로 저희 팀에서는 각 컴포넌트 폴더 내에 `__test__`와 같은 폴더를 따로 만들어 그곳에서 해당 컴포넌트의 테스트코드를 관리하는 방식을 사용하기도 해요 :) (이렇게 하라는 말은 아닙니다 ㅎㅎ)

다만, 이번 과제 프로젝트의 기존 test 폴더에서는 E2E테스트에 관한 테스트 코드들이 들어있기 때문에, 따로 섞이지 않도록 관리하는게 좋을 것 같네요~
중요한건 같이 일하는 동료들과 어떻게 관리할 것인지 협의하는거니까요 ☺️

2020-10-07 02:42 UTC, smilee commented
> 모든 컴포넌트에 대해서 일단 테스트를 만들어 보신게 좋네요!
> 
> 그리고 test 폴더에서 모든 테스트 파일들을 관리하는 것도 좋은 것 같습니다👍 실제로 저희 팀에서는 각 컴포넌트 폴더 내에 `__test__`와 같은 폴더를 따로 만들어 그곳에서 해당 컴포넌트의 테스트코드를 관리하는 방식을 사용하고 있어요~ (이렇게 하라는 말은 아닙니다 ㅎㅎ)
> 
> 다만, 이번 과제 프로젝트의 기존 test 폴더에서는 E2E테스트에 관한 테스트 코드들이 들어있기 때문에, 따로 섞이지 않도록 관리하는게 좋을 것 같네요~
> 중요한건 같이 일하는 동료들과 어떻게 관리할 것인지 협의하는거니까요 ☺️

과제를 급하게 하다보니 기존 테스트 파일의 존재조차 모르고 바로 보이는 `test` 폴더에 테스트 코드를 작성하는 실수를 했군요! 🤣 
테스트 코드를 모두 이사시켰습니다. ㅎㅎ

2020-10-07 14:33 UTC, Kihyun92 requested changes
좋습니다~ 많은 고민을 해보고 계신 것 같네요 :)
테스트를 작성할때 `App.test.jsx`와 같은 최상위 컴포넌트에서 `item.test.jsx`와 같은 최하위 컴포넌트로 작업하는 방법과 반대로 최하위에서 최상위로 작성해보는 방식이 있습니다~
각각 어떤 장단점이 있고, 어떤 상황에 각 방법을 사용하는게 좋을지 한번 고민해보시면 좋을 것 같습니다~!

2020-10-07 14:33 UTC, Kihyun92 commented on src/App.test.jsx
> +  describe('when new task is input', () => {
```suggestion
  context('when new task is input', () => {
```
다양한 테스트들을 보기 쉽게 표현하신 것 같네요~ 이 경우에는 `describe-context-it` 형식에 맞춰 작성하면 더 어울릴 것 같아요~ 참고로 `context` 안에는 `with, without, when`만 사용하도록 권장합니다.

```
describe('render', () => {
  context('tasks가 없을 떄', () => {
    // Given
    const tasks = [];

    it('빈 메세지를 표시합니다.', () => {
      // When
      const { container } = render(<SomeComponent />);

      // Then
      expect(container).toHaveTextContent('투두가 없습니다.');
    });
  });
```

위의 예시 코드를 보면, `render는 tasks가 없을 때 빈 메시지를 출력한다.`와 같이 이해하기 쉽게 읽힙니다.

반드시 항상 `describe-context-it`의 구조를 적용할 필요는 없습니다. 시나리오에 맞게 고민해보시고 사용하시면 좋을 것 같아요~

2020-10-08 08:49 UTC, smilee commented
최상위 컴포넌트에서 최하위 컴포넌트로 테스트를 작성하면 큰 그림을 그린 다음 작업할 수 있고, 반대로 작업하면 작업하면서 큰 그림을 그릴 수 있게 될 것 같습니다. 아마 프로젝트의 규모가 커지면 후자처럼 작업하지 않을까요?

2020-10-08 16:57 UTC, Kihyun92 requested changes
테스트의 중점을 어디에 두느냐에 따라서 어떤 영향이 있을지 고민을 잘 해주신것 같아요~ 👍 

테스트도 결국 유지보수해야하는 코드입니다. 불필요한 중복은 없애고, 필요한 테스트를 추가하는 등 꾸준히 리펙토링을 해야하는 부분이죠. ☺️

2020-10-08 16:57 UTC, Kihyun92 commented on src/List.test.jsx
> +      ));
테스트가 추가될때마다 중복 코드가 생길 것 같아요~ 함수로 추출하여 상위에 위치시킨다면 어떨까요?

그리고 List 컴포넌트에는 완료 버튼을 핸들링하는 함수가 있는데 이에 대한 테스트도 있으면 좋을 것 같네요~

2020-10-08 23:09 UTC, smilee commented on src/List.test.jsx
> +      ));
말씀하신대로 중복 코드를 함수로 추출했습니다. 😄 

완료 버튼을 핸들링하는 부분은 해당 버튼이 있는 컴폰넌트에서 테스트했는데, 그 함수를 내리는 과정에 매번 테스트를 작성하는 게 좋을까요?

2020-10-09 14:21 UTC, Kihyun92 commented on src/List.test.jsx
> +      ));
아 그렇네요 ㅎㅎ `Item.test.jsx`에서 이미 task가 있는 경우에 대해서 확인이 됐기 때문에 리스트에선 필요 없을 것 같습니다~ 🙏

2020-10-09 14:52 UTC, Kihyun92 requested changes
피드백을 잘 반영해주신것 같아요 👍  지금 같은 테스트에서는 당장 문제가 없을 수 있지만, 테스트들은 각각 독립적이어야합니다~

`beforeEach`와 같은걸 사용하여 각 테스트의 시작 전에 mocking 해준 함수들을 초기화를 해줄 수 있어요. 이를 통해 각 테스트가 의도한대로 동작한다고 신뢰할 수 있게 됩니다~ 
```
beforeEach(() => {
  jest.clearAllMocks();
});
```

- https://jestjs.io/docs/en/jest-object#jestclearallmocks

2020-10-09 14:52 UTC, Kihyun92 commented on src/App.test.jsx
> +      expect(container).toContainHTML('<div');
App에서 render가 잘 이루어졌는지 테스트를 해주셨네요!👍 div라는 태그가 존재하는지를 보는것도 좋지만, 특정 컨텐츠 내용이 노출됐는지를 확인하는것도 괜찮을 것 같아요~

2020-10-09 14:52 UTC, Kihyun92 commented on src/App.jsx
> +      taskTitle: value,
주어진 코드를 변경해서 테스트를 작성하신 것 같아요~ 왜 변경이 필요했나요?

2020-10-11 07:38 UTC, smilee commented on src/App.jsx
> +      taskTitle: value,
이렇게 변경한 것이 테스트 코드를 짜기가 더 편해서요! :)

2020-10-11 07:42 UTC, smilee commented on src/App.test.jsx
> +      expect(container).toContainHTML('<div');
Page의 "To-do"가 보이는지 확인했습니다~

2020-10-11 07:48 UTC, smilee commented
> 피드백을 잘 반영해주신것 같아요 👍 지금 같은 테스트에서는 당장 문제가 없을 수 있지만, 테스트들은 각각 독립적이어야합니다~
> 
> `beforeEach`와 같은걸 사용하여 각 테스트의 시작 전에 mocking 해준 함수들을 초기화를 해줄 수 있어요. 이를 통해 각 테스트가 의도한대로 동작한다고 신뢰할 수 있게 됩니다~
> 
> ```
> beforeEach(() => {
>   jest.clearAllMocks();
> });
> ```
> 
> * https://jestjs.io/docs/en/jest-object#jestclearallmocks

반영했습니다! 😄

2020-10-11 12:21 UTC, Kihyun92 approved these changes
꽤 어려운 과제였는데, 제가 드린 피드백보다 더 잘 해주신 것 같아요!👍 테스트를 작성하면서 어떻게 코드들이 바뀌었는지 봐보시면 좋을 것 같습니다 ㅎㅎ

과제풀이 영상도 꼭 보시면 좋겠습니다~😁

2020-10-11 12:21 UTC, Kihyun92 commented on src/App.test.jsx
> +
`describe` 안에 추가 하는게 좋을 것 같네요~

2020-10-11 12:21 UTC, Kihyun92 commented on src/App.test.jsx
> +}
`describe` 안에 선언해주는게 좋을 것 같습니다~

2020-10-11 12:31 UTC, Kihyun92 commented
코멘트 확인해보시고, 수정되는대로 머지하도록 하겠습니다 ㅎㅎ 그리고 남겨주신 회고 잘 봤습니다!(제가 맞게 해석 했겠죠..?😂)

2020-10-11 13:35 UTC, smilee commented on src/App.test.jsx
> +
지금 위치에서는 파일 안에 있는 모든 테스트에 적용되는 것 같은데 꼭 describe 안에 넣어야 할까요?
https://jestjs.io/docs/en/setup-teardown

2020-10-11 13:54 UTC, Kihyun92 commented on src/App.test.jsx
> +
맞아요 지금 상황에서는 반드시 그래야하는건 아닙니다. 하지만 `describe`안에 선언함으로써 우리가 의도한 테스트에만 적용되게 할 수 있죠. 만약 바깥에 사용한다면, 지금 당장은 문제가 없지만, 추후 다른 테스트가 추가될 경우, 해당 테스트에 의도치 않은 영향을 줄 수 가 있어요.

`그때 가서 옮기면 되지 않나?` 라고 생각되지만, 테스트를 추가하는게 작업자 본인이 아닌 다른 동료에게는 그 의도가 전달되지 않을 수 있어요 ㅎㅎ 그래서 가능하면 현재 테스트 scope 내부에 두는걸 추천했습니다~

2020-10-11 14:00 UTC, smilee commented on src/App.test.jsx
> +}
얘는 다른 테스트에서도 쓸 수 있으니 그대로 두는 것도 좋을 것 같습니다. 😄

2020-10-11 14:10 UTC, merged