[week3-assignment-1] To-do 테스트 작성하기
CodeSoom/week3-assignment-1 pull request #38
Opened 2020-10-06 15:30 UTC by goodzzong

### 과제 목표
 - 모든 컴포넌트에 테스트를 작성하고 커버리지 100% 달성하기

### 요구사항

- ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- 모든 인수 테스트를 통과시켜야 합니다.
- 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- 테스트 커버리지 100%를 달성해야 합니다.

### 기능구현

- [ ] App.test.jsx 통과하기
- [ ] Page.test.jsx 통과하기
- [ ] List.test.jsx 통과하기
- [ ] input.test.jsx 통과하기

### 고민

- 처음부터 어떤 식으로 접근 해야 하는지 감을 잡기 위해 글로 풀어서 써보기로 했습니다. 테스트 케이스를 작성하기 위한 시나리오가 아니라 너무 글을 풀어서 쓴 요구사항 같은 느낌이라 어색한 것 같습니다.
- 대부분의 컴포넌트 들이 부모컴포넌트의 자식 컴포넌트라 테스트 케이스가 중복 되는 느낌입니다. 이 부분을 어떻게 적절 나눠야 하는지 고민입니다.

2020-10-07 15:38 UTC, Kihyun92 requested changes
테스트 또한 코드의 일부입니다. 계속해서 유지보수를 해야하고, 중복되거나 빠진 테스트가 있다면 지속적으로 수정해줘야하죠. 시나리오를 처음부터 고민해보는건 매우 좋은 것 같아요. 시나리오를 구현하다보면, 언젠가는 해결되는 고민일 것 같습니다~ 👍 

그리고 두번째 고민의 경우, 컴포넌트가 최상위에 있는지, 최하위에 있는지에 따라 역할이 달라질 것 같습니다~ 개인적으론 App과 같은 최상위 컴포넌트의 경우 테스트 케이스가 매우 다양할 수 밖에 없기 때문에, 전체 흐름에 대해서 E2E 테스트를 사용하여 테스트하고, 세세한 기능 테스트는 최하위 컴포넌트에서 하는게 좋을 것 같다는 생각입니다.

이번 과제는 가능한 모든 테스트의 커버리지를 100%로 맞춰보자는 생각으로 본인이 안심되는 만큼, 테스트를 작성해보시면 좋을 것 같습니다 :)

2020-10-07 15:38 UTC, Kihyun92 commented on src/List.test.jsx
> +      ));
리스트 컴포넌트를 render하는 코드가 각 테스트마다 중복되는데, 이 부분 개선해보면 좋을 것 같아요~

그리고 리스트 컴포넌트에서 onClickDelete해주는 핸들러도 테스트해보면 좋을 것 같네요 :)

2020-10-08 17:08 UTC, Kihyun92 requested changes
좋습니다~ 시나리오를 작성하고 테스트를 구현하셔서 그런지 잘 작성하고 계신 것 같네요 👍 

테스트가 무엇을 할지도 중요하지만, 뭘 했을때 어떻게 되야하는지에 집중해보시면 좋을 것 같아요 :)

2020-10-08 17:08 UTC, Kihyun92 commented on src/List.test.jsx
> +      expect(handleClickDelete).toBeCalledWith(tasks[0].id);
다른 테스트에 영향을 받을 것 같습니다. 각 테스트는 독립적으로 실행되어야해요.

`beforeEach`를 이용해서 mocking 함수들을 초기화 시켜주면 각 테스트가 의도치 않게 동작하는 것을 막을 수 있습니다.

```
beforeEach(() => {
  jest.clearAllMocks();
});
```

2020-10-08 17:08 UTC, Kihyun92 commented on src/Page.test.jsx
> +      );
테스트가 추가될때마다 중복 코드가 생기지 않게 상위에서 함수로 관리해주세요~

2020-10-08 17:08 UTC, Kihyun92 commented on src/input.test.jsx
> +describe('Input Test', () => {
파일 이름에서 test라는걸 유추할 수 있기 때문에 `Test`는 빼도 될 것 같습니다~

2020-10-08 17:08 UTC, Kihyun92 commented on src/input.test.jsx
> +      ));
이쪽도 추상화를 통해 상위에서 관리하는게 좋을 것 같네요~

2020-10-11 11:56 UTC, Kihyun92 commented
혹시 진행하시다가 어려운점이 생기면 말씀해주세요~ ☺️

2020-10-11 16:34 UTC, goodzzong commented
App 에서 테스트 하는 부분이 어려웠습니다. Page 와 중복되는 코드들이 있다고 생각한 부분도 있었고 이해를 하지 못하여 App 과 Page가 같다 라는 생각이 강했습니다. 각 컴포넌트의 사용 설명서를 작성한다른 개념을 조금은 이해 할 것 같아서 처음 보다는 괜찮아진 것 같습니다.

기능들이 구현되어 화면에 보여지는 담당을 하는 자식 컴포넌트에서는 기능들의 테스트가 잘되는지 확인을 하고 
App 컴포넌트에서는 좀 더 사용자 입장에서 시나리오를 테스트 하듯이 진행 되는 느낌입니다.

2020-10-19 13:25 UTC, merged