Make Input.test.jsx
CodeSoom/week3-assignment-1 pull request #39
Opened 2020-10-06 15:44 UTC by TaeWoongKim2

# To-do 테스트 작성하기

## **목표**

> 모든 컴포넌트에 테스트를 작성해보자.
그리고, 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해보자!

![image](https://user-images.githubusercontent.com/37302935/95224235-65d9e600-0835-11eb-9008-90ef2fc61384.png)

## **기능구현**

- [ ]  input.test.jsx 통과하기
- [ ]  List.test.jsx 통과하기
- [ ]  Page.test.jsx 통과하기
- [ ]  App.test.jsx 통과하기

## **진행사항**
Make test case for Input component.

> nput 컴포넌트의 `onChange` 테스트를 위해 `fireEvent.change()`를 활용하려고 했으나, 다음과 같은 오류 발생.
> ```
> Expected: "뭐라도 하기"
> Received: ""
> ```

아래와 같이 실행 시, 테스트를 통과하는 것으로 보아 node의 문제 아닌 것으로 확인.

> ```
> inputNode.value = '뭐라도 하기'
> expect(inputNode.value).toBe('뭐라도 하기');
> ```

2020-10-09 11:55 UTC, TaeWoongKim2 commented
현재 어플리케이션에 상태를 파라미터로 받아 그려주는 관심사를 갖고 있는 Input, List 컴포넌트에 대해 테스트를 만들어봤습니다.

현재 Page 및 App 컴포넌트에 대해 고민중인 내용은 다음과 같습니다.

- Page에서 Input 및 List 컴포넌트를 자식으로 사용하고 있는지 확인할 수 있을까?
Page 컴포넌트에서는 무엇을 테스트하면 좋을지 고민됩니다.

- App 컴포넌트는 상태를 변화시키는 Function에 대해서만 테스트하면 될까?
'App은 자동차다. 자동차는 엑셀이 밟히면 나가고, 헨들을 돌리면 바퀴가 돌아가는 것을 테스트하면 된다.' 라고 생각했으며,
그려주는 것은 이미 자식 컴포넌트인 Input과 Item, List 등에서 테스트하면 된다는 방식으로 방향을 잡고 나아가고 있습니다.



현재까지 진행된 코드에 대해서 더 발전시킬 수 있는 방향과 고민 해봐야할 방향에 대해 리뷰를 해주시면 감사하겠습니다!!!

2020-10-10 13:48 UTC, hannut91 requested changes
테스트를 잘 잘성해주신 것 같습니다 ㅎㅎ 테스트 이름만 조금만 더 신경써주시면 좋을 것 같아요. 내가 무엇을 테스트하는지보다, 테스트하는 기능이 실제로 어떤 일을 하는지 혹은 어떤 변화가 일어나는지를 중심적으로 작성해주시면 좋을 것 같아요. ㅎㅎ 그러면 이코드를 읽는 사람은 테스트를 통해서 컴포넌트를 학습하게 되고 이 컴포넌트를 사용해서 내가 무엇을 얻을 수 있는지 파악하기 쉬울거에요

2020-10-10 13:48 UTC, hannut91 commented on src/App.test.jsx
> +});
`beforeEach`는 `describe`안에 들어가는게 좋을 것 같고, 여기서는 `clearAllMocks`를 안해도 될 것 같아요 ㅎㅎ 사용하는 mocking 함수들이 없어서요

2020-10-10 13:48 UTC, hannut91 commented on src/App.test.jsx
> +  });
무엇을 테스트하는지 모르겠어요 ㅎㅎ 더 자세히 작성해주시면 좋을 것 같아요

2020-10-10 13:48 UTC, hannut91 commented on src/Input.test.jsx
> +    return { ...utils };
다른 helper함수들을 추가하기 위해서 이렇게 작성해주신 것 같아요 ㅎㅎ 지금은 없으니까 더 단순히 표현해줘도 될 것 같습니다

2020-10-10 13:48 UTC, hannut91 commented on src/Input.test.jsx
> +    onChange = handleChange,
위에서 선언한 handleClick을 사용하고 따로 매개변수로 넘겨주지 않기 때문에, 파라미터에 이렇게 있을 필요가 없을 것 같아요

2020-10-10 13:48 UTC, hannut91 commented on src/Input.test.jsx
> +});
이 부분은 `describe`안으로 들어와야 합니다

2020-10-10 13:48 UTC, hannut91 commented on src/Input.test.jsx
> +  });
테스트가 실제로 어떤 일을 하는지 명시해주면 더 좋을 것 같아요. 
`shows label text`은 어떨까요?

2020-10-10 13:48 UTC, hannut91 commented on src/List.test.jsx
> +      getByText(deleteButtonText);
`getBy*`함수들은 찾지 못할 경우 에러가 발생해서 이렇게 작성해주신 것 같아요. 하지만 단정문을 사용해서 의도를 더 드러내는게 좋을 것 같습니다.

```js
expect(getByText(tasks[0].title)).toBeInTheDocumnet();
```

See also
  - https://github.com/testing-library/jest-dom#tobeinthedocument

2020-10-10 15:43 UTC, TaeWoongKim2 commented on src/App.test.jsx
> +});
`beforeEach`는 `describe`안에 들어가는게 좋군요!!
맞습니다. `**App.test.jsx**`에서는 `clearAllMocks`이 필요없는 것 같아서 최근 작업에서 뺐습니다!!

2020-10-10 15:44 UTC, TaeWoongKim2 commented on src/App.test.jsx
> +  });
최근 commit에 무엇을 테스트할지, 무엇이 실행되는지 올렸습니다 :)

2020-10-10 15:45 UTC, TaeWoongKim2 commented on src/Input.test.jsx
> +    onChange = handleChange,
Value 만 있으면 될 것 같습니다!! 수정 하겠습니다 👍

2020-10-10 15:47 UTC, TaeWoongKim2 commented on src/Input.test.jsx
> +  });
모든 테스트 파일 전체적으로 '어떤 일을 하는지' 에 대해 정확하게 명시해주도록 수정해야겠습니다!!

2020-10-10 15:52 UTC, TaeWoongKim2 commented on src/List.test.jsx
> +      getByText(deleteButtonText);
더욱 의도를 잘 드러내는 방향으로 수정하겠습니다 😁

2020-10-10 16:11 UTC, TaeWoongKim2 commented
## 새롭게 작업한 부분

### Page 및 App Component에 대한 테스트 구현.

#### Page component는 현재 페이지가 무엇을 위한 페이지 알려주는 것이 관심사.

- [ ] 1. 페이지 제목(Title)을 정확하게 갖추고 있는지?


#### App component는 사용자가 사용할 어플리케이션으로 생각하여 테스트를 진행했습니다.

> 자동차를 예로 들면, 엑셀을 밟으면 차가 앞으로 가고 브레이크를 밟으면 차가 멈춘다면 자동차는 정상적으로 작동한다고 생각했다.
> 테스트 방향을 '내부적으로 어떻게 돌아가는지 사용자는 알 필요가 없다'로 잡았다.
> 위와 같은 생각으로 App 컴포넌트의 관심사를 아래와 같이 정리해봤다.

- [ ] 1. 초기 화면에 '할 일을 입력해 주세요'와 '할 일이 없어요!'가 명시가 되는지?

- [ ] 2. 할 일을 입력할 수 있는지?

- [ ] 3. 입력된 할 일을 추가할 수 있는지?

- [ ] 4. 추가된 할 일 목록을 삭제할 수 있는지?



## 추가로 해야할 부분

- [ ] 1. 모든 테스트가 **'어떤 일을 하는지'**가 명시적으로 기입돼 있는지 확인 및 수정. 

- [ ] 2. **단정문**을 사용해서 의도를 더욱 명확히 드러나도록 수정.

- [ ] 3. `beforeEach(() => { jest.clearAllMocks() });` 의 위치 `describe` 안으로 수정.

- [ ] 4. render()에 대해 필요한 부분만 기입. 단순한 표현 지향.


**리뷰해주신 내용을 참고하여 더 좋은 테스트 코드를 만들도록 하겠습니다 😃**

2020-10-11 06:42 UTC, TaeWoongKim2 commented
## ✈️ 새롭게 작업한 부분

> 더 좋은 테스트를 만들기 위해 조언해주신 부분 적극 반영했습니다 😆
> 테스트하고자 하는 주제를 기입할 때, 더 간단하고 더욱 명료하고 더욱 더 명시적으로 작성하기 위해 수정 진행했습니다 😁

 1. 모든 테스트가 **'어떤 일을 하는지'**가 명시적으로 기입돼 있는지 확인 및 수정.

 2. 단정문을 사용해서 의도를 더욱 명확히 드러나도록 수정.

 3. beforeEach(() => { jest.clearAllMocks() }); 의 위치 describe 안으로 수정.

 4. render()에 대해 필요한 부분만 기입. 단순한 표현 지향.

2020-10-11 13:54 UTC, hannut91 approved these changes
테스트를 잘 작성해주셨네요 ㅎㅎ 우리가 회고를 할 때 Fact, Feeling, Finding 처럼 템플릿을 쓰면 좋은 회고를 작성하는 좋은 연습이 되는 것 처럼 테스트도 BDD 스타일 Given, When, Then에 템플릿에 맞춰서 테스트를 작성해보면 자연스럽게 좋은 테스트를 작성할 수 있습니다.

2020-10-11 13:54 UTC, hannut91 commented on src/App.test.jsx
> +  const addTaskButton = '추가';
`addButton`은 어떨까요?

2020-10-11 13:54 UTC, hannut91 commented on src/App.test.jsx
> +  const deleteTaskButton = '완료';
`completeButton`은 어떨까요?

2020-10-11 13:54 UTC, hannut91 commented on src/App.test.jsx
> +  const isEmptyTaskNotice = '할 일이 없어요!';
`emptyMessage`는 어떨까요?

2020-10-11 13:54 UTC, hannut91 commented on src/App.test.jsx
> +  };
`init`이라는 말은 초기화를 할 것 같은데 실제로는 그런 일을 하는 것이 아니라 우리가 테스트하고 싶은 대상이 들어가 있는 것 같아요.
`renderApp`이나 `renderComponent`처럼 대상을 명시해주면 좋을 것 같아요. 
그리고 헬퍼 함수같은 다른 함수들을 추가하기 위해서 구조 분해 할당을 하신 것 같은데 지금은 하고 있지 않으니 그냥 반환해도 될 것 같아요

2020-10-11 13:54 UTC, hannut91 commented on src/App.test.jsx
> +  context('Can this app enter to-do title?', () => {
`context`에는 `when, with, without`만 작성하도록 권장합니다. 즉 어떤 상황이 주어졌을 때(Given) 다르게 테스트를 표현하고 싶을 때 사용합니다. 예를들어서
`context(when login) it(shows products)`
`context(when not login) it(shows login message)`

이런식으로 작성할 수 있습니다.

See also
  - https://www.betterspecs.org/#contexts

2020-10-11 13:54 UTC, hannut91 commented on src/App.test.jsx
> +    it('when empty value', () => {
`it` 함수 안에는 실제로 무슨 일을 하는지 혹은 어떤 변화가 일어나는지를 중심적으로 작성해주시면, 다른 사람이 코드를 봤을 때 이 코드를 이용해서 내가 무엇을 얻을 수 있고 무엇을 할 수 있는지 알기 쉽습니다. 지금의 경우 `shows empty value`정도로 해도 괜찮을 것 같아요

2020-10-11 13:54 UTC, hannut91 commented
이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

2020-10-11 15:01 UTC, TaeWoongKim2 commented on src/App.test.jsx
> +  const addTaskButton = '추가';
간단하고 명료 할수록 좋죠!
여기서는 추가 버튼 하나니깐 addButton이 명확하겠네요 :)

2020-10-11 15:02 UTC, TaeWoongKim2 commented on src/App.test.jsx
> +  };
그러네요. 아무런 값도 받지 않으니 그냥 반환해주는게 더 명확하네요. 감사합니다!!

2020-10-11 15:06 UTC, TaeWoongKim2 commented
이번 과제를 통해 얻은게 많은 것 같습니다.
일단 코드의 신뢰도를 높이는 아주 중요한 TDD 방식을 배웠다는 점이 가장 좋네요.
마치 옆에서 제가 이상한 방향으로 가지 않도록 보고 있는 동료를 하나 얻은 것 같습니다.

앞으로도 TDD 기반의 코드 구현 방식과 가독성 좋은 자바스크립트 코딩의 기술 책을 다시 한 번 볼 생각입니다.
지금까지 배운 것과 앞으로 배울 것들을 항상 반복 학습해서 습관으로 만들고 싶네요.
항상 피가 되고 살이 되는 좋은 코드리뷰 감사합니다 💯

2021-01-17 13:00 UTC, merged