Todo Test 작성하기
CodeSoom/week3-assignment-1 pull request #40
Opened 2020-10-06 16:11 UTC by koremp

2020-10-06 16:12 UTC, koremp commented
Test의 예시를 어떻게 작성할지 감이 안잡히네요. ㅠㅠ

2020-10-07 15:06 UTC, hannut91 commented
먼저 사용법에 대해서 정의를 한다고 생각하시고 가장 단순한 테스트를 작성해보세요. `<Input />` 컴포넌트는 어떻게 사용하는건가요?

2020-10-09 15:08 UTC, hannut91 requested changes
테스트를 잘 작성해주셨네요 ㅎㅎ 테스트도 코드라서 관리를 해야합니다. render하는 부분과 handler를 선언하는 부분이 중복되고 있어요. 이 때 `describe-context-it`을 사용하면 중복된 로직을 많이 제거할 수 있을거에요.

```js
describe('Input', () => {
  const handleChange = jest.fn();
  const handleClick = jest.fn();

  it('claer on click', () => {
    render(<Input onChange={handleChange} onClick={handleClick} />);
  });
  
  it('some test', () => {
    render(<Input onChange={handleChange} onClick={handleClick} />);
  });
});
```

2020-10-09 15:08 UTC, hannut91 commented on src/Input.test.jsx
> +  const onClickAddTask = jest.fn();
`<Input />` 컴포넌트의 `onClick` 혹은  `onChange`를 다루는 함수이니 여기서는 `handleChangeTitle`과 `handleClickAddTask`라는 이름이 더 적절할 것 같아요

2020-10-10 14:23 UTC, hannut91 requested changes

2020-10-10 14:23 UTC, hannut91 commented on src/List.test.jsx
> +});
저라면 이렇게 작성할 것 같아요

```js
describe('List', () => {
  const renderList = (tasks) => render((
    <List
      tasks={tasks}
      onClickDelete={handleClick}
    />
  ));

  context('without tasks', () => {
    const tasks = [];

    it('shows empty message', () => {
      const { container } = renderList(tasks);

      expect(container).toHaveTextContent('할 일이 없어요!');
    });
  });

  context('with tasks', () => {
    const tasks = [
      { id: 1, title: '뭐라도 하기' },
      { id: 2, title: '코드숨 과제하기' },
    ];

    it('shows tasks', () => {
      const { container } = renderList(tasks);

      tasks.forEach(({title}) => {
        expect(container).toHaveTextContent(title);
      });
    });
  });
});
```

`describe-context-it`의 텍스트를 순서대로 읽으면 완전한 문장이 됩니다.
`List without tasks shows empty message`
`List with tasks shows tasks`
그리고 `context`를 이용해서 주어진 상황(Given)을 명시적으로 표현했습니다.

2020-10-12 06:40 UTC, koremp commented on src/List.test.jsx
> +});
PR 리뷰에 대한 알림이 안왔네요 ㅜ.ㅜ
```toHaveTextContent```같은 함수가 실행되지 않는 것에 대해 막혀서 어떤 함수가 작동이 안되고 되는지에 대해 테스팅 라이브러리의 Document와 직접 코드를 작성하면서 확인해보면서 습득이 필요한 것 같습니다!

2020-10-12 10:02 UTC, koremp commented
App.jsx의 test coverage를 100%로 만들기 위해서 React custom Hook을 테스트해야하는데 어떤 식으로 테스트할지 갈피를 못잡고 있습니다.

2021-01-17 13:00 UTC, closed without merging