[week3] todo 테스트 코드 작성
CodeSoom/week3-assignment-1 pull request #41
Opened 2020-10-07 14:53 UTC by shinseungyup

List 컴포넌트부터 테스트 작성 중입니다.

tasks가 여러 개 일 때는 어떻게 테스트를 할 지 아직 모르겠지만 일단 PR 먼저 하고 방법을 찾아보겠습니다.

2020-10-07 15:33 UTC, hannut91 commented
ㅎㅎ좋네요! 원래 너무 많은걸 한 번에 테스트하려고 하면 어렵습니다 ㅎㅎ tasks가 없으면 어떡하지? tasks가 null이면 어떡하지? 이런 것들을 생각하다보면 끝도없이 늘어나 머리가 아프기 때문이죠. 그래서 Happy path를 가장 먼저 테스트를 작성해야합니다. 복잡한 예외의 경우를 제외하고 모든게 올바르게 동작하는 경우를 먼저 테스트를 하는거에요. 실제로 구현도 이걸 먼저 하겠죠? 
그 다음에 음.. 혹시 tasks가 없으면 어떡하지? 지금은 모릅니다. 테스트가 없기 때문에 정의되어 있지 않은 거죠. 그 다음에 하나하나씩 구현해나가면 돌파해 나가실 수 있을거에요

2020-10-08 15:14 UTC, shinseungyup commented
오늘도 조금밖에 못하고 PR을 올리네요. 
말씀해주신대로 복잡하게 생각하지 않고 하나씩 테스트 코드를 작성해봤는데.. 이렇게 하는게 맞는건지 잘 모르겠네요
일단 List 컴포넌트는 하였고 내일 다른 컴포넌트 계속 올리겠습니다~

2020-10-09 15:26 UTC, hannut91 commented
테스트를 작성하실 때 `Given, When, Then`에 맞춰서 코드를 작성해보세요. 이러한 형식에 맞춰서 테스트를 작성하는 연습을 하면 좋은 테스트를 작성하는데 많은 도움이 됩니다. 

```js
describe('render', () => {
  context('tasks가 없을 떄', () => {
    // Given
    const tasks = [];

    it('빈 메세지를 표시합니다.', () => {
      // When
      const { container } = render(<SomeComponent />);

      // Then
      expect(container).toHaveTextContent('투두가 없습니다.');
    });
  });
  
  context('tasks가 있을 때', () => {
    // Given
    const tasks = [{ id: 1, task: '밥먹기' }];

    it('tasks 목록을 출력한다', () => {
      ...
    });
  });
});
```

그래서 차례대로 읽어보면 `render는 tasks가 없을 때 빈 메시지를 출력한다.`, `render는 tasks가 있을 때 tasks목록을 출력한다.`로 읽을 수 있습니다. 그래서 자연스러운 문장이 됩니다. 영어로 작성해도 마찬가지에요. 그래서 `context`안에는 `with, without, when`만 사용하도록 권장합니다.

See also
  - https://ko.javascript.info/testing-mocha
  - https://www.betterspecs.org/#contexts

2020-10-10 14:15 UTC, shinseungyup commented
말씀해주신 Given, When, Then에 따라 테스트 코드를 작성하도록 노력하겠습니다. describe, context, it 도 링크해주신 글 보고 무슨 의미인지 이해했습니다. 그래도 막상 테스트 코드를 작성하려고 하니 컴포넌트에서 어떤 것을 테스트 해야 하고 그것을 어떻게 테스트 코드로 표현해야 할지 어려웠습니다. 리뷰해주시면 참고해서 내일 더 수정해볼게요.

2020-10-10 14:39 UTC, hannut91 requested changes

2020-10-10 14:39 UTC, hannut91 commented on src/App.test.jsx
> +      expect(container).toHaveTextContent('테스트 코드 작성');
여기 위에 빈 줄을 추가해서 구분해주면 좋을 것 같아요.
그리고 `테스트 코드 작성`이라는 Magic literal대신에 `taskTitle`을 이용해서 표현해줄 수 있을까요?

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2020-10-10 14:39 UTC, hannut91 commented on src/Input.test.jsx
> +  const handleClick = jest.fn();
mock 함수들을 이용해서 테스트할 때 각 테스트마다 초기화를 해주는게 좋습니다. 그렇지 않으면 다른테스트에 의해서 다른 테스트들이 영향을 받게 됩니다.

```js
beforeEach(() => {
  jest.clearAllMocks();
});
```

See also
  - https://jestjs.io/docs/en/setup-teardown
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks

2020-10-10 14:39 UTC, hannut91 commented on src/Input.test.jsx
> +      expect(handleClick).toBeCalled();
코드를 문맥에따라 빈 줄로 구분하면 읽는 사람에게 더 도움이 됩니다.

2020-10-10 14:39 UTC, hannut91 commented on src/List.test.jsx
> +      expect(container).toHaveTextContent('공부 하기');
이 부분도 `tasks`를 이용해서 표현해줄 수 있을까요?

2020-10-11 12:44 UTC, shinseungyup commented on src/App.test.jsx
> +      expect(container).toHaveTextContent('테스트 코드 작성');
앞으로 Magic literal은 변수로 대체해서 쓰도록 할게요.

2020-10-11 12:46 UTC, shinseungyup commented on src/Input.test.jsx
> +  const handleClick = jest.fn();
네. 초기화 해야 한다는 것도 처음 알았네요. 코드 수정했습니다.

2020-10-11 12:49 UTC, shinseungyup commented on src/Input.test.jsx
> +      expect(handleClick).toBeCalled();
읽는 사람을 더 생각해서 코드 작성을 해야겠어요.  한 줄 띄우는 것도 의도를 갖고 작성하겠습니다.

2020-10-11 13:47 UTC, hannut91 approved these changes
과제를 잘 진행해주셨네요 ㅎㅎ 과제 풀이 영상을 보면서 테스트를 어떻게 작성하는지 복습해보시면 좋을 것 같습니다. 

이번 과제를 진행하면서 무엇을 배우셨나요? 어떤 것을 더 집중적으로 배우고 싶으신가요?

2020-10-11 13:47 UTC, hannut91 commented on src/App.test.jsx
> +      fireEvent.click(delBtn);
변수의 이름은 아주 자명하지 않으면 줄여쓰지 않는게 좋을 것 같아요 ㅎㅎ btn, del 관습적으로 많이 사용하지만 그래도 풀어써주는게 좋을 것 같습니다

2020-10-11 13:47 UTC, hannut91 commented on src/App.test.jsx
> +    it('task가 지워진다', () => {
테스트의 의도를 잘 작성해주신 것 같아요! 어떤 변화가 일어나는지 집중하면 테스트를 작성하기 더 쉬워지고, 왜 이 코드를 내가 사용해야하는지, 그래서 내가 무엇을 얻을 수 있는지 의도를 잘 드러낼 수 있어요.

2020-10-11 13:47 UTC, hannut91 commented
슬랙에 회고를 남겨주셨군요!

2020-10-11 13:47 UTC, merged